### ISSUE TITLE
[BUG] Game categories settings don't set categories properly

### ISSUE THREAD

**Issue by iamerror80** [Fledge68/WiiFlow_Lite#101]
Hi there !
A regression since Feb 11 commit : now when selecting several category checkboxes (in game categories settings), it only sets one of them in categories_lite.ini (the first or the the last checked depending on their order in the list) and erase the other ones.

I think "gameCats =+ cCh;" should be "gameCats += cCh;" in _setGameCategories.

**Comment by Fledge68** [comment]
thanks again! i love how you always seem to find the problem in the code. makes it easy for me.
