### ISSUE TITLE
Retroarch Dol files

### ISSUE THREAD

**Issue by Kokokool** [Fledge68/WiiFlow_Lite#106]
Hello:

Months ago a dev user release a bunch of DOL files from retroarch that allowed to load and run Mame 2003 complete romset for the wii.

Additionally, they fixed the way of load bigger neo geo files via Vram.

So what I did was, in source menu add the plugin and every was setting up ok, the problem was loading. I test in parallel retroarch via homebrew channel to test the dols, and no problem at all. 

But in wiiflow, the system just kicks you back to wiiflow. 

is there any chance to make the dol work in my wiiflow?

**Comment by Wiimpathy** [comment]
You also have copied the dol files in the right plugins folder right?

For mame2003:
**1a)**  in the MAME2003-WII-0.4.zip, copy the cores (mame2003_plus_coreA_libretro_wii.dol etc...) from /apps/retroarch-wii to the /WiiFlow/plugins/retroarch-wii folder.
Or
**1b)** You can also launch the dol from the standard folder used with the Homebrew Channel. For example, edit mameA.ini: **dolfile=sd:/apps/retroarch-wii/mame2003_plus_coreA_libretro_wii.dol**

**2)** Copy your games in sd:/roms/MAME2003/coreA or usb:/roms/MAME2003/coreA. Create the folders if they don't exist or edit romdir=...
**3)** Add the button in source_menu.ini. Here's mine, you may have a different number :
[BUTTON_19]
image=mame.png
image_s=mameb.png
source=plugin
magic=6d616d41
emuflow=4

Do step #3 for each core and change the magic number corresponding to the core.

Like it's said in the README, the dols from Alt_dols may have better performance/compat. And some games will run slower from an usb device(?!).


For NeoGeo, you'll also need to copy the dol in /WiiFlow/plugins/retroarch-wii or just edit the .ini file. 
If you want to use the one installed on sd card, edit the dol path in fba_neo.ini:
**dolfile=sd:/apps/retroarch-wii/fbalpha2012_neogeo_libretro_wii.dol**

If you load the games from USB, you must have the games cache files on USB too. You have to specify the new path in Retroarch. Go to Settings->Directory->System/Bios and then select usb:/retroarch/system/ folder.

**Comment by Kokokool** [comment]
Perfect!
Please helpme with the other questions I have.
Youre the best
bye!
