### ISSUE TITLE
Does not return to WiiFlow after launching roms

### ISSUE THREAD

**Issue by CrewMdk** [Fledge68/WiiFlow_Lite#107]
Since version 5.2.0 it does not return to WiiFlow when it leaves the emulator as RetroArch or any plugin, in version 5.1.0 there is no problem.
I have installed the Forwarder Channel with the WFLA ID and it loads from the USB:/apps/wiiflow/boot.dol.
If I delete the version 5.2.0 and pass the 5.1.0 if it does the function of returning to WiiFlow after closing an emulator or plugin launched from WiiFlow.

**Comment by Fledge68** [comment]
ummm it does for me.  do you have the hidden channel installed? or just the forwarder?

**Comment by CrewMdk** [comment]
> ummm it does for me. do you have the hidden channel installed? or just the forwarder?

 I have the forwarder channel installed.

**Comment by Fledge68** [comment]
You have to have the hidden channel installed to return from plugin emus.
Just the old original wiiflow mod.

**Comment by CrewMdk** [comment]
> You have to have the hidden channel installed to return from plugin emus. Just the old original wiiflow mod.

Installing the hidden channel (WiiFlowLoaderChannel v2 - WIIH.wad) already returns to WiiFlow after exit an plugin. Thanks for the help.
