### ISSUE TITLE
The text "Total Games" can not be translated.

### ISSUE THREAD

**Issue by CrewMdk** [Fledge68/WiiFlow_Lite#108]
Try the Italian and Spanish language and it does not matter how the text changes, there are no changes in WiiFlow.

![Jun-26-2019-09h09m38s](https://user-images.githubusercontent.com/10386171/60192601-b45ba080-97fb-11e9-81df-99ed560b640e.png)

**Comment by Fledge68** [comment]
thanks. i think i have fixed it. will try it out later and let you know.
