### ISSUE TITLE
[REQ]  New partition settings where you can choose sdhc partititon.

### ISSUE THREAD

**Issue by ableto288** [Fledge68/WiiFlow_Lite#109]
I have all my games in a SDHC wbfs partititon but i cant select it. Its like CFG USB loader, you can chose the partititon inside the sdhc.

sorry for my bad english, thanks for everything

**Comment by Fledge68** [comment]
sorry but no. all through out wiiflow code partition 0 is used as SD and 1 thru 8 as USB.  everything is so old they never expected you to have more than one partition on a SD card? in fact im so old i didn't even realize you could have more than one partition on a SD card LOL.

**Comment by gingerbeardman** [comment]
Today there's no reason to use WBFS partition. You should transition to FAT32. 

I used this tool to do the conversion in-place, without any data loss, it took a few seconds.
https://gbatemp.net/threads/wbfs2fat-py.291320/

**Comment by Fledge68** [comment]
Hey Matt! off topic here. but what do you think of the update coverflow pull request? i don't use 4:3. should i accept it?

**Comment by gingerbeardman** [comment]
I use 4:3 so i'll try to check it out this weekend
