### ISSUE TITLE
WiiSX (in SD) Loading games Through USB

### ISSUE THREAD

**Issue by Kokokool** [Fledge68/WiiFlow_Lite#110]
When im loading an ISO from WiiSX plugin, it last quite a bit to get to the main window. Sometimes when i press Load game, it crashes.

I test the same procedure but loading the dol from Wiixplorer to check if Wiisx is the problem, and guess what?, everithing works fine.

Some how loading  ISOs through Wiiflow and USB gests very slow and crashes. 

Any clues on that?

I have a 4.2U Wii with Masterpiece Pack Inside.

**Comment by Fledge68** [comment]
no clue. wiisx on wii isn't very good any way.
