### ISSUE TITLE
[Req] Deciphering Magic Numbers

### ISSUE THREAD

**Issue by jcuralli** [Fledge68/WiiFlow_Lite#114]
I’m trying to decipher how to retool the magic numbers I’m using to get the box shape I want. Is there a list somewhere of the magic number components and a list of what I need to change to alter the way boxes are rendered?

**Comment by Fledge68** [comment]
you need to check out tesuo shima's rhapsodii shima theme. mainly his platform.ini under [FLOWS] and his coverflows ini.

**Comment by jcuralli** [comment]
I did - I honestly should have closed this out earlier... I just got lazy. Thank you for the response!
