### ISSUE TITLE
[Suggestion] Add unencrypted wii game support if not already implemented.

### ISSUE THREAD

**Issue by ProfElements** [Fledge68/WiiFlow_Lite#116]
I would like you to add unencrypted wii game support, mostly because I use a program called [Nkit](https://gbatemp.net/threads/nkit-recover-to-redump-images-shrink-and-preserve-wii-and-gamecube-disc-images-as-playable.548479/) So that compressed nkit format is playable on real hardware instead of just emulator saving space while also preserving files in a compact and reversible format.

**Comment by gingerbeardman** [comment]
https://wiki.gbatemp.net/wiki/NKit

**Comment by Fledge68** [comment]
so where do i get the code to decompress nkit iso's?

**Comment by gingerbeardman** [comment]
Have asked https://gbatemp.net/threads/nkit-recover-to-redump-images-shrink-and-preserve-wii-and-gamecube-disc-images-as-playable.548479/#post-8804825

**Comment by ProfElements** [comment]
"Source will be released soon. It's not required though to understand the format. The format is just Wii decrypted and dehashed (RVT-H)." -nanook

**Comment by gingerbeardman** [comment]
@ProfElements yes, but it also said:

> Here is info on RVT-H courtesy of GerbilSoft (who also helped out on this project in the background for his incredible knowledge of dev formats)
https://github.com/GerbilSoft/rvthtool/blob/master/doc/disc_image.md

**Comment by ProfElements** [comment]
Thank you @gingerbeardman for the heads up, I apparently cant read. Thank you again. 👍

**Comment by gingerbeardman** [comment]
I just started using this format for my GC games (Nintendont supports it)

**Comment by ProfElements** [comment]
Any updates on this?

**Comment by gingerbeardman** [comment]
@ProfElements when I last discussed it with @Fledge68 the conclusion was that it would need the function to be programmed by somebody else, then it could be integrated into WFL.

My query about this at NKit thread goes unanswered: https://gbatemp.net/threads/nkit-recover-to-redump-images-shrink-and-preserve-wii-and-gamecube-disc-images-as-playable.548479/page-7#post-8971997

It's a lot of work to replace the legacy code for WBFS. Right now, if I'm not mistaken, there are zero loaders that support NKit. This is probably for the same reason.

**Comment by ProfElements** [comment]
Thank for the update! That is extremely saddening but reasonable. :+1:  Thank you again
