### ISSUE TITLE
Wiiflow resets categories when returning to game list

### ISSUE THREAD

**Issue by elmimmo** [Fledge68/WiiFlow_Lite#117]
When returning to Wiiflow from a game or a restart back to the game list, Wiiflow resets categories that were ON back to OFF.

This breaks Source Menu items that force a category, since that category is cleared when returning, and games not in that category become listed too.

Steps to reproduce:

1.	In source_menu.ini, set a source that forces a category, like:

		[BUTTON_7]
		autoboot=
		cat_page=1
		category=6
		image=arcade.png
		image_s=arcade.png
		magic=6d616d41,6d616d42,6d616d43,6d616d44,6d616d45,6d616d46,6d616d47
		source=plugin
		title=Arcade 1995-1999 (MAME)

2.	In Wiiflow Lite, go to Settings, Page 11 and set "Source menu on Start = No"
3.	Go to Source menu and select your newly created Source.
4.	Go to Categories and disable the forced category so that you can see all games for the associated plugins.
5.	Assign category 6 to some.
6.	Go back to Source menu and select the same Source. The games you assigned the category to should be listed.
7.	Exit Wiiflow Lite and Relaunch it.

Expected results:

The same list that was displayed before existing Wiiflow should come up.

Actual results:

All games for the associated plugins are listed, instead of the subset that were assigned category 6.

**Comment by Fledge68** [comment]
fixed in one of the latest commits. thanks for pointing this out.
