### ISSUE TITLE
[BUG] game doesn't load (sometimes)

### ISSUE THREAD

**Issue by gingerbeardman** [Fledge68/WiiFlow_Lite#12]
1. Click on game 
2. Make sure the banner is fullscreen (click on it)
3. Click Play
= black screen (not even the white loading bar)

But

1. Click on game 
2. Make sure you're in game cover and banner view
3. Click Play
= works

**Comment by Fledge68** [comment]
questions:
every game or just specific ones?
what type of game? wii? nand game? gc game?

**Comment by gingerbeardman** [comment]
seemed like every game (though I did not try every game)

Wii game loading from USB

- Skylanders Superchargers Racing
- GTI Club: Supermini Festa
- Driver San Francisco

**Comment by Fledge68** [comment]
have you tried v5.0.0? do they still crash?

**Comment by gingerbeardman** [comment]
Just tried 5.0.0 with GTI CLUB, no change, still crashes.

**Comment by gingerbeardman** [comment]
So looking into this more, my initial report was a red herring - it is unrelated to the banner. But something is toggling my ability to load games (or not).

Currently I cannot launch any game.

I'll add more info soon how to accurately reproduce.

**Comment by gingerbeardman** [comment]
OK, ignore my last comment, it is still an issue with the banner.

OK, having deleted my .ini earlier I realised I needed to set:
Startup Settings > Force cIOS Revision > 249

to be able to get any games to load on my setup.

GTI Club now loads OK (from game settings screen play button) with repeated attempts.

If I full screen the banner and click the play button underneath that, my games do not load.

Could it be that the play button under the full screen banner works differently in some way?

**Comment by gingerbeardman** [comment]
OK, I got into a state where the game would not load even from game settings (small banner view)

I can force the game to load by setting `IOS = 249` per game, rather than `AUTO`

But I have `Startup settings` > `cIOS = 249` which I thought means use 249 for all games? Is that not the case?

Maybe this is a misunderstanding on my part?

**Comment by gingerbeardman** [comment]
OK, that was the issue:

I needed to do _both_
1. force IOS = yes
2. cIOS = 249

I was only doing the second one

Perhaps changing cIOS away from auto should change force IOS to yes?

**Comment by Fledge68** [comment]
fyi, to clarify - startup settings are for wiiflow (lite) itself. it can use IOS58 for everything or you can force it to use a  specific cIOS (usually 249).
each game when launched will use its own IOS or cIOS to controll Input/Output for the game. when run each game has specific IOS to use and with it set to auto wiiflow uses that IOS to determine which cIOS to use. or you can set the game to use a specific cIOS.

I have no idea why a full screen banner would be stopping you from playing again. no one else has ever complained of this issue. the only thing i can think of is that you have a large amounts of games and there covers along with the full screen banner are causing you to run out of memory.

**Comment by gingerbeardman** [comment]
Forget about the full screen banner, it's not related.  

I have approx 80 Wii games and 25 GC games. 

I don't think the games are even starting to load when I hit the black screen. 

That said, setting `Force iOS = yes` solves this issue.

But I'm at a loss as to why, given your explanation above that that setting only applies to WFL. 

What IOS does WFL pick when set to Auto? IOS 58? Could that be unexpected on my Wii?

**Comment by Fledge68** [comment]
with force cios = yes then wiiflow loads cios 249 and uses it through out.

with force cios= no then wiiflow loads ios 58 but when it comes time to launch a wii game for example.
wiiflow changes from ios58 to cios249. during that time all devices including USB HDD are unmounted and after the switch remounted. some USB HDD have issues with this and don't want to remount or are too slow. mine is one of them so i always force cios yes. to keep wiiflow from unmounting and remounting my usb HDD.

**Comment by gingerbeardman** [comment]
I have no settled on `Force CIOS = yes` and `IOS = Auto` works for me.
