### ISSUE TITLE
"Exit To" screen: cursor directions are switched

### ISSUE THREAD

**Issue by gingerbeardman** [Fledge68/WiiFlow_Lite#120]
**To reproduce**
1. Press home
2. Choose "Exit to"
3. Use d-pad up/down

**Expected**
Cursor highlight should move as directed

**Actual**
Cursor highlight moves in the opposite direction to the one pressed

- d-pad Down moves the cursor up
- d-pad Up moves the cursor down

**Comment by Fledge68** [comment]
are you using a theme? or vWii on WiiU?
I just tested and it works perfect for me.

**Comment by gingerbeardman** [comment]
I am using Rhapsodii (not sure if the latest)

**Comment by Fledge68** [comment]
then it's because Rhapsodii has the buttons in a different order from top to bottom

**Comment by gingerbeardman** [comment]
I'll report it on their thread. 

Video: https://imgur.com/a/uW6HRUq

**Comment by Fledge68** [comment]
yep i see in your video its sys menu, hbc, bootmii, prii, neek
in wiiflow its hbc, sys menu, neek, prii, bootmii
