### ISSUE TITLE
[Bug] Cateories hidden issue

### ISSUE THREAD

**Issue by OoIceDeepoO** [Fledge68/WiiFlow_Lite#124]
Hi I created 51 categories and set the last ten to hidden. None of my games have any categories set at all. For some reason when I set any of the lower number categories to hidden, it hides everything. Every single game in the plugins section disappears. Doesn't matter if they have a category or not. (They are definitely not in the hidden category). This is a tricky bug, because hidden works some of the time. When I only had twenty categories, I would hide the first or second category and it would hide the respective games in that category. I LOVE the categories functionality. If you get around to fixing this stuff, I would love it so much. I might be able to help too. I am a c# programmer, but I can read through and try to fix if you want me to.

**Comment by Fledge68** [comment]
something is really messed up with your categories ini file or you don't understand that hidden is only when the checkbox is an 'X'. required is  a '+' and if games are not in that category then they will not show.

**Comment by OoIceDeepoO** [comment]
Hi Again,

I think I am using it right and I have had it working. 

My most detailed understanding in my own words. Is if a category is set to X, what that means is every game in that category becomes hidden.

What I am seeing is when I x, maybe over 10 categories, then even games not in the x categories are hidden.

I am for sure not saying my categories_lite.ini could not be malformed. Definitely possible, but as far as I could tell the application loads it in, then rewrites it back out, which means even if it was malformed, wouldn't it correct itself?

With this one I could do any of the following:
1) Provide video and ini
2) Try to figure out the exact conditions it happens, because it is more complicated then just marking a single category as an x. That worked for me, I had a category marked sys files, that I was using to hide the neogeo.zip and I had that as an x. It worked fine. It was only when I added over fifty categories and marked around 20 of them hidden, when almost none of my games were in any of the categories that they (all the games) disappeared. I started unhiding categories 1 by 1 till they reappeared. I unmarked maybe 10. So I thought it was the last category I unmarked that caused it. So, I marked another category hidden. All the games disappeared again. I tried a different category it happened again. It has either to do with having more than a certain number of categories hidden or something to do with how many categories I have.

This one is complicated for sure, who knows, maybe my whole install has a problem. 

I downloaded a new copy and copied with beyond compare (a dif tool) and none of the initial files were different. Tonight I will use a fresh install and see if I can duplicate this. Same with my other issue.

Wayne


-----Original Message-----

**Comment by OoIceDeepoO** [comment]
I tried this one with the clean install also. After the tests for the last issue. I edited the categories_lite.ini in notepad++ and added a total of 50 categories. All with the same generic names that the original file had. I then took it out of my computer and inserted into the Wii and started Wii Flow. I went to the categories section and marked 45-50 hidden. Checked my games and they were all there. I then, marked 35-50 hidden... all the games were gone. Keep in mind only a couple of games are in category 1 and category 2, due to my prior tests. I am definitely not using the + sign which I realize is an "and" operator, while the check box is an "or".

I am zipping and attaching the my categories_lite.ini in hopes it will get all teh way to you. If it does not let me know and I can try and upload it somewhere.

Wayne


-----Original Message-----

**Comment by Fledge68** [comment]
Ah ha! I think i see the problem.

you said - 'What I am seeing is when I x, maybe over 10 categories, then even games not in the x categories are hidden.'

and in menu.cpp initcf() the code says this:
char requiredCats[10];
char selectedCats[10];
char hiddenCats[10];
strcpy(requiredCats, m_cat.getString("GENERAL", "required_categories").c_str());
strcpy(selectedCats, m_cat.getString("GENERAL", "selected_categories").c_str());
strcpy(hiddenCats, m_cat.getString("GENERAL", "hidden_categories").c_str());
u8 numReqCats = strlen(requiredCats);
u8 numSelCats = strlen(selectedCats);
u8 numHidCats = strlen(hiddenCats);

as you can see I wasn't expecting anyone to select or hide more than 10 categories. I guess i figured that would be overkill. 

I'll look into rewriting the code in case someone like yourself decides they need to select or hide more than10 categories. :)

**Comment by Fledge68** [comment]
here try this - https://www.mediafire.com/file/apn28isky4rees6/wf5.3.0beta12bootdol.zip/file

if it works i'll commit it and we can close this issue.

**Comment by OoIceDeepoO** [comment]
Thank You so much I am playing with a games database and was going to generate a full categories ini for as many games as I could, with as much categorization as I could.

We will see if I ever finish it, I appreciate you looking into this.


-----Original Message-----

**Comment by OoIceDeepoO** [comment]
Shoot, I tested the new dol and had a strange result. I went to the categories screen and I could not hide or unhide anything, because the circles that you click on next to the category names were all not displaying at all. So, no circles to click on to toggle between check, plus, x and empty.

If you want, pics, vids or the ini let me know.

Wayne


-----Original Message-----

**Comment by Fledge68** [comment]
sorry i forgot i recently updated the checkbox images. here is another download. this one includes the imgs folder and bin folder. replace the ones you have.
https://www.mediafire.com/file/1zrlz8i8p64abbo/wfcategoriesfix.zip/file

**Comment by OoIceDeepoO** [comment]
Good job, this new one worked perfectly. I could not repeat the problem and I could not break it in any other way.

I think you have done it.

As I learn more about the Wii Flow, keep me in mind. I am happy to help you test.

Wayne


-----Original Message-----

**Comment by OoIceDeepoO** [comment]
Resolved for future version, see above... (Good job Fledge68
