### ISSUE TITLE
[BUG] Pressing B on Settings screen should take you back to menu not coverflow

### ISSUE THREAD

**Issue by gingerbeardman** [Fledge68/WiiFlow_Lite#126]
Reproduce:
- Press B on Settings screen 

Expected:
- should take you back to menu

Actual
- takes you to coverflow.

Notes
- If you're at sub-level settings page, it should take you up/back a level.

5.3b12

**Comment by Fledge68** [comment]
no I made it that way. just in case they changed certain settings i don't want the user to go back to the home menu and select plugin, reload cache, or open explorer and launch a dol.

maybe moving settings to home menu isn't such a good idea.

**Comment by gingerbeardman** [comment]
I don't think this issue is a big deal. It was just unexpected
