### ISSUE TITLE
vwii not loading games (black screen)

### ISSUE THREAD

**Issue by ashkitten** [Fledge68/WiiFlow_Lite#137]
i've been trying to migrate all my wii homebrew stuff over to the wiiu, and after following the guide on https://wiiu.hacks.guide i did a system transfer and copied various homebrew to the vwii. everything seems to work great, except when trying to load wii backups from sd card or usb i get a black screen or in some cases a dsi exception. i did manage to get mario kart wii to load, but only under very specific conditions -
- using usb
- "force ios version" set to something other than "auto" in main settings
- "ios" set to 251 in game settings

anything other than that seems to fail and kick me back to the wii menu or cause a black screen or dsi exception

**Comment by gingerbeardman** [comment]
Can you post a system info dump?

Maybe do ModMii to bring your vWii up-to-date?

**Comment by ashkitten** [comment]
hey, i'm not sure how to do a "system info dump". what is that? also, i thought modmii was only meant for real wiis and would brick a vwii

**Comment by gingerbeardman** [comment]
sysCheck 
https://gbatemp.net/threads/syscheck-hacksden-edition.356133/

ModMii - you are correct, sorry about that.

**Comment by ashkitten** [comment]
here is the `sysCheck.csv` on the sdcard after running

```
SysCheck HDE v2.4.0 HacksDen Edition by JoostinOnline, Double_A, R2-D2199, and Nano
...runs on vIOS58 (rev 6432).

Region: NTSC-U
System Menu 4.3U (v609)

Drive date: 06.28.2011
Homebrew Channel 1.1.2 running on IOS58

Hollywood v0x21
Console ID: 605917881
Console Type: vWii
Shop Channel Country: United States (49)
Boot2 v0
Found 62 titles.
Found 34 IOS on this console. 0 of them are stubs.

vIOS9 (rev 1290): No Patches
vIOS12 (rev 782): No Patches
vIOS13 (rev 1288): No Patches
vIOS14 (rev 1288): No Patches
vIOS15 (rev 1288): No Patches
vIOS17 (rev 1288): No Patches
vIOS21 (rev 1295): No Patches
vIOS22 (rev 1550): No Patches
vIOS28 (rev 2063): No Patches
vIOS31 (rev 3864): No Patches
vIOS33 (rev 3864): No Patches
vIOS34 (rev 3864): No Patches
vIOS35 (rev 3864): No Patches
vIOS36 (rev 3864): No Patches
vIOS37 (rev 5919): No Patches
vIOS38 (rev 4380): No Patches
vIOS41 (rev 3863): No Patches
vIOS43 (rev 3863): No Patches
vIOS45 (rev 3863): No Patches
vIOS46 (rev 3863): No Patches
vIOS48 (rev 4380): No Patches
vIOS53 (rev 5919): No Patches
vIOS55 (rev 5919): No Patches
vIOS56 (rev 5918): No Patches
vIOS57 (rev 6175): No Patches
vIOS58 (rev 6432): USB 2.0
vIOS59 (rev 9249): No Patches
vIOS62 (rev 6942): No Patches
vIOS80 (rev 7200): No Patches
vIOS249[56] (rev 21010, Info: d2x-v10beta52-vWii): NAND Access, USB 2.0
vIOS250[57] (rev 21010, Info: d2x-v10beta52-vWii): NAND Access, USB 2.0
vIOS251[58] (rev 21010, Info: d2x-v10beta52-vWii): NAND Access, USB 2.0
vIOS512 (rev 7): No Patches
vIOS513 (rev 1): No Patches
Report generated on 12/19/2019.
```

**Comment by Fledge68** [comment]
Do you have your USB HDD connected to the back of the WiiU via a Y cable for the extra power?

**Comment by ashkitten** [comment]
i realized that my hdd was not working due to power issues, so for lack of a Y cable i copied mario kart wii to a flash drive and tried with that

**Comment by Fledge68** [comment]
then i would say your problem is lack of a y cable. using the flash drive isn't any better and i would say you just got lucky to get mario kart wii to work.

**Comment by ashkitten** [comment]
huh. i'll try to get a y cable, but i'm having trouble finding one to get. would a powered usb sata adapter work?

**Comment by ashkitten** [comment]
i'm also interested in figuring out why it won't load from sd card either, by the way

**Comment by Fledge68** [comment]
as for SD what version of Wiiflow are you using? The latest beta's (14 and 15) have fixed issues with SD for some users.

**Comment by ashkitten** [comment]
i wasn't aware of any betas. i'm using the latest release 5.2.0

**Comment by ashkitten** [comment]
i looked at the forum thread and saw a mediafire link for beta 14, but it was broken so i built wiiflow lite myself from source and copied it over the old files (removed boot.elf since that was preventing it from showing up in the homebrew channel and didn't exist in the old files). it appears to have the same issue with loading from sd as before, though, unless you'd like me to try with a specific configuration?

**Comment by Fledge68** [comment]
nope, i guess you are just SOL. Join the small group out there that can't seem to get wiiflow 5 to work on wii u vwii.

All i can say is in startup settings you should have force cios yes/on and cios set to auto. and game setting IOS set to auto. works great for me and many others.

you might also try setting cios 249 to base 58. and if that don't work try using beta 53 instead of beta 52. but i'm really just guessing at options that may or may not work.

**Comment by ashkitten** [comment]
just tried all those suggestions, none worked. i'd like to try again with usb once i can do it properly. also, i don't think i got a response as to if a powered usb-sata adapter would help?

**Comment by Fledge68** [comment]
I've never tried a powered usb-sata adapter. you could try.

**Comment by ashkitten** [comment]
i got a y cable and tried it. would it help to post the wiiflow.log, by the way?

**Comment by ashkitten** [comment]
looks like i'm able to get games to load by setting the ios to 251 in the game settings? but installing an ios with base 58 to slot 249 doesn't work (a guess based on your previous suggestion)

**Comment by gingerbeardman** [comment]
But I thought you had Force IOS = yes and IOS = 251 in global settings?

**Comment by ashkitten** [comment]
it seems like the only thing that works is ios = 251 in game settings

**Comment by gingerbeardman** [comment]
Interesting. It would be worthwhile trying to find out what is specific about your setup that needs this.

**Comment by Fledge68** [comment]
If you can do the sd write log it would help alot.

**Comment by ashkitten** [comment]
just got back to this after a while. it looks like setting force ios revision 251 in the main settings works! i have force cios off because it was causing problems (don't remember exactly what, though)

**Comment by Fledge68** [comment]
I'm guessing that whatever cios you have installed in 249 doesn't work for some reason. maybe it's a bad install for some strange reason. they do happen some times.

I'm assuming since force cios is on and set to 251 that in all your game settings you can set the ios to auto?

**Comment by ashkitten** [comment]
yep!

for some reason it's giving me black screens sometimes anyway though, any idea why?

**Comment by ashkitten** [comment]
gonna close this since i seem to have gotten it working pretty consistently.

**Comment by gingerbeardman** [comment]
What did you change? For us all to learn from.

**Comment by ashkitten** [comment]
i'm not sure, honestly. i think it might've been using a usb wall adapter to power the drive instead of plugging it into the nearby switch dock that did it, but i've also messed around with other things i don't entirely remember

**Comment by gingerbeardman** [comment]
Good point, your drive might have not been getting enough power.

**Comment by gonefishing1975** [comment]
Hey
I have a question about playing Wii games in vWii on my Wii U. I open WiiFlow and when I try to play a Wii gamne the screen either goes black or an error dump shows up. I tried different CIOS settings but they just win;t work in WiiFlow. USB Loader GX seems to work. All my classic systems work in WiiFlow like NES, SNES etc. Any ideas why it won't work? It's the same setup I use on just the Wii and it works no issues at all. I turned off force CIOS, set it to 251 and still black
Thanks

**Comment by yllekz** [comment]
Hey folks, I am just getting black screens of death when trying to load games from the SD card in WiiFlow (latest version). Both Wii Sports and Mario Kart Wii suffered the same issue. All the fixes I've tried don't work and it's frustrating when the system doesn't give me any errors or logging to work with. Does this app just not work with games on the SD card or something?

**Comment by gingerbeardman** [comment]
App works fine from SD, that's the only way I use it personally. 

Turn on logging:
https://github.com/Fledge68/WiiFlow_Lite/issues/196#issuecomment-703176522 

Try the official support thread for assistance using WFL:
https://gbatemp.net/threads/wiiflow-lite.422685/
