### ISSUE TITLE
consider patching games to support gamecube controller adapter

### ISSUE THREAD

**Issue by ashkitten** [Fledge68/WiiFlow_Lite#141]
apparently, [this module](https://github.com/Chadderz121/wup-028-bslug) for the [brainslug game patching engine](https://github.com/Chadderz121/brainslug-wii) is able to patch any game which natively supports gamecube controllers to support the official nintendo usb adapter as well. i was wondering how feasible it would be to implement this functionality into wiiflow lite? i'm not sure exactly how brainslug works, but maybe it's possible to use it like a library here?

**Comment by Invictaz** [comment]
Second this

**Comment by gingerbeardman** [comment]
what are the benenefits of this?

**Comment by Invictaz** [comment]
Yes with the WUP-028 adapter @gingerbeardman

**Comment by Fledge68** [comment]
sorry not going to happen.
