### ISSUE TITLE
[DISCUSS] screen elements should be within Safe Zone

### ISSUE THREAD

**Issue by gingerbeardman** [Fledge68/WiiFlow_Lite#144]
This applies to the default theme and third-party themes like Rhapsodii (I'll cross post there).

In short, elements on the screen should be inside a "safe area" so they are not cut off with overscan on the Wii/TV settings.

Patterns and background can go outside of this area, as their cropping is not of any consequence.

The safe area could be as low as 608 x 448 so it would be good to check the default theme adheres to this.

References:
- https://web.archive.org/web/20080215151751/http://wiinintendo.net/2006/11/30/web-design-guide-for-opera-browser-on-wii/ cf. https://ar.al/823/
- https://en.m.wikipedia.org/wiki/Safe_area_(television)
- https://wiki.nesdev.com/w/index.php/Overscan
- http://gendev.spritesmind.net/forum/viewtopic.php?t=237&start=15
- http://forum.wiibrew.org/read.php?11,4412,4423

**Discussion**  
https://gbatemp.net/threads/wiiflow-lite-theme-rhapsodii.511833/page-7

**Comment by Fledge68** [comment]
so matt have you tried usb loader gx 'adjust overscan' settings? do they work for you?
thinking of adding them to wiiflow.

**Comment by gingerbeardman** [comment]
I will try those and let you know.

I've been given a new version of Rhapsodii that avoid the cropping, but I feel that the core issue (common to lots of homebrew, but interestingly not all) could be shared screen setup code? I'll take a look to see if I can come up with anything concrete. The wiibrew forum link above is a good starting point.
