### ISSUE TITLE
[Suggestion] Add Slippi as a Gamecube loader

### ISSUE THREAD

**Issue by AkinaYamito** [Fledge68/WiiFlow_Lite#145]
Can you add support for Nintendon't Slippi as a gamecube loader?

**Comment by gingerbeardman** [comment]
Can you provide a link to explain what Slippi is?

**Comment by AkinaYamito** [comment]
https://slippi.gg/faq

**Comment by AkinaYamito** [comment]
specifically [this](https://github.com/project-slippi/Nintendont/releases/download/v1.8/Nintendont-Slippi-1.8.zip) gamecube loader is what I am talking about

**Comment by gingerbeardman** [comment]
Does that build not work in place of regular Nintendont? That is, if you download it and rename it so it’s the same as the regular Nintendont does it work with WFL?

If not, how would you like to see support for it being added?

**Comment by gingerbeardman** [comment]
Basically, you need to provide enough information and reasoning that this becomes a no-brainer to add. Right now there's hardly any information and even less incentive.

**Comment by AkinaYamito** [comment]
This build does work in the place of regular nintendon't. If I place it in the nintendon't folder it works as expected. The problem is that it isn't a replacement for nintendon't and works best in tandem with it. Ideal situation is that I have nintendon't set as the main gamecube loader and then I set Slippi as the loader for just melee. The implementation is pretty simple basically I would like it to load the same as nintendon't just pointed at a different folder.

**Comment by Fledge68** [comment]
does it only work for one game? melee?

**Comment by AkinaYamito** [comment]
It can run any gamecube game. But it only has value if it is running melee. I've been trying to do this any other way but I have had no luck trying to convince wiiflow to load this as devolution (you could probably tell me why that was dumb) or as a plugin. Heck if you can tell me where in wiiflow it is decided how many gamecube loaders I get to have I will attempt this myself.

**Comment by Fledge68** [comment]
i suppose i could add it as a setting in wiiflow_lite.ini that you would have to manually set.

**Comment by AkinaYamito** [comment]
Yes that would be the best way. Do you need anymore info or want this closed?

**Comment by Fledge68** [comment]
could you please test this version of wiiflow

https://www.mediafire.com/file/82k6fivwecj24p4/wf5.4.1with_slippi.zip/file

edit wiiflow_lite.ini - under [GAMECUBE] add this line and save:
use_slippi=yes

make sure nintendont slippi is installed in apps/nintendont slippi/
this should work only with smash bros melee.

note: wiiflow 5 only sends boot arg to nintendont. it never modifies ninconfig.

**Comment by AkinaYamito** [comment]
can't get it to work. What is supposed to happen after I set the flag? Is Slippi supposed to show up as a loader only for melee as an individual game or is this supposed to bypass the ui entirely?

**Comment by Fledge68** [comment]
You need to set the loader to nintendont. Wiiflow will check if the game is
melee and if use slippi is yes. If so it will load nintendont via
apps/nintendont slippi.

**Comment by Fledge68** [comment]
ok fixed a little code error. try this one. 

https://www.mediafire.com/file/rzuumpk6m7a82ej/wf5.4.1.slippi_test2.zip/file

it works for me - sort of.  it starts nintendont slipp but takes a long time and then nintendont slippi gives me a stupid error - CheckForMultiGameAndRegion() = failed
and shows the path to melee's game.iso and then goes back to wiiflow after 10 seconds.

**Comment by Fledge68** [comment]
ok so i see another issue later in the code that i need to fix. will post test 3 soon.

**Comment by Fledge68** [comment]
test 3

https://www.mediafire.com/file/v5rqyhpl63vsu1i/wf5.4.1.slippi_test3.zip/file

ok with test 3 i get nintendont slippi to load and at normal speed. but the game does not auto boot and it takes a long time to detect devices. and eventually it gives me a warning message in the lower right that i need a specific version of smash bros melee for it to work. i can use my wiimote on the menu but once the game is launched i can only use a gamecube controller.

since the game didn't autoboot for me i'm wondering if slippi is accepting args boot from wiiflow.

**Comment by AkinaYamito** [comment]
test 2 works as intended for me

**Comment by Fledge68** [comment]
try test 3 please. it does have on little fix.

**Comment by AkinaYamito** [comment]
test 3 is perfect.

**Comment by AkinaYamito** [comment]
I don't know what else to say. I am assuming it works because my iso is scrubbed or something? Your end is literally perfect as far as I can tell.

**Comment by Fledge68** [comment]
ok good it works. as long as it works for you.
