### ISSUE TITLE
Launching Wii Games Causing System Freeze On 5.4.0 Loading From SD 

### ISSUE THREAD

**Issue by Astraliccc** [Fledge68/WiiFlow_Lite#146]
I'm pretty much at a dead end on getting 5.4.0 to be even remotely usable. I'm experiencing an issue with Wiiflow Lite where every time except once on cIOS 250 in 20+ attempts it causes my Wii U to freeze on a black screen with no error messages. This same issue has never occurred for me if I load 5.2.0 using identical settings and setup so it appears something changed in 5.4.0 broke it. Also not sure if it's normal but there's no background music in 5.4.0. I've also tried redownloading 5.4.0 several times to verify it wasn't a bad download.

Setup:
Display is set to 16:9 1080p in wii u menu.

Not using any forwarders.

Auto Load cIOS is enabled, I've verified my cIOS installs are good and it occurs on 249, 250 and 251 using the recommended settings for vwii modding. Save to emunand is disabled. The one time it did work it was Super Mario Galaxy on cIOS 250 and it loaded very quickly and worked normally.

SD Card:
512GB, Verified Genuine and fully operational in h2testw
Reads at 90MBps in a PC
A2 rated + Class 10 MicroSDXC using an SD card adapter (have tried multiple SD card adapters that are class 10 rated and it happens with all of them)
Have attempted with both FAT32 32kb and 64kb clusters.
Drive passes error checking and works flawlessly in everything else.
Write protection is off.

Games:
Testing with Wii Sports and Mario Galaxy + Mario Galaxy 2, verified in wii backup managers that they have no integrity issues.

An SSD is plugged into the back with a y cable but is used for Wii U games and same issue occurs with it unplugged.

**Comment by Fledge68** [comment]
https://www.mediafire.com/file/ghtc0bmqx2m17dt/wf5.4.1test1.zip/file

https://www.mediafire.com/file/gd4wedtgh8b81au/wf5.4.1test2.zip/file

let me know if either one works.

**Comment by Astraliccc** [comment]
Both freeze on a black screen like 5.4.0 for me. Tried all the cIOS versions as well on both.

**Comment by gingerbeardman** [comment]
Just to confirm you tested 5.2.0 recently with this exact setup?

**Comment by Fledge68** [comment]
yes please try 5.2.0 again to make sure it still works. otherwise I have no idea. basically test 2 above reverted the only change I made to SD card I/O since v5.2.0 and I was hoping would fix your issue.

on a side note I'm pretty sure the wii and wii homebrew only work with SD and SDHC cards. SDXC cards might be another story. but you said you are on wii u.

**Comment by Astraliccc** [comment]
Yep 5.2.0 works perfectly still and I’m doing clean installs each change.

**Comment by GABO1423** [comment]
I had a similar situation that I was able to fix in the following ways: stick to 5.2.0 and use the force cIOS feature (doesn't matter if its on auto or not), use the 5.4.1 vidfix version and use the force cIOS feature (again, it could be auto or with a number) or use the newest 5.4.2 beta WITHOUT the force cIOS feature enabled. Try those options and see if any of them works. Here are the links to the vidfix and 5.4.2 beta downloads:
5.4.1 vidfix: http://www.mediafire.com/file/i1h9mtu0p4gbiwf/wf5.4.1vidfix.zip/file
5.4.2 beta: http://www.mediafire.com/file/c8b62pei680myb5/wf5.4.2beta_binaries.zip/file
Before you install either of them, install the vanilla 5.4.1 version and replace the files. I recommend you test the vidfix version first.

**Comment by Fledge68** [comment]
have you tried the official 5.4.2 version? GABO1423 tried it and it workd for them. please let me know i would like to close this issue.

**Comment by user020** [comment]
I'm still getting this issue on 5.4.3 and have done on every version since 5.4.0 (5.2.0 works fine). Using vWii, loading WFL and games off a Sandisk Ultra Class 10 512GB SD card. Tried the following steps:

1. Perform fresh install of WFL 5.4.3
2. Run WFL from forwarder then New Super Mario Bros, game loads fine
3. Exit out of game back to Wii Menu, run WFL again without changing any settings
4. Run New Super Mario Bros again, crashes to black screen. Wii U requires power cycling

**Comment by GABO1423** [comment]
Try the force cIOS feature. Use it on Auto, 249, 250, 251. Also try booting up the games with the option off.

**Comment by GABO1423** [comment]
Do that and please report back with the results.

**Comment by user020** [comment]
Testing with New Super Mario Bros and Nights with a fresh install of WFL 5.4.3 again:
1. Force Load cIOS Off, Force cIOS Revision Auto - black screen
2. Force Load cIOS On, Force cIOS Revision Auto - black screen
3. Force Load cIOS On, Force cIOS Revision 249 - black screen
4. Force Load cIOS On, Force cIOS Revision 250 - black screen
5. Force Load cIOS On, Force cIOS Revision 251 - black screen

Rolled back to my existing installation of 5.2.0 (Force Load cIOS On, Force cIOS Revision 251) and everything worked as expected.

**Comment by Fledge68** [comment]
just to make sure. are you using any emunand for gamesaves?

really strange it would run the first time only.

**Comment by user020** [comment]
No I'm not (settings used are below).

NAND Emulation Settings:

Select NAND - default
NAND Emulation - Partial
Select Saves NAND - default
Saves NAND Emulation - Off
Saves NAND Partition - SD

Startup Settings

Force Load cIOS - On
Force cIOS - Revision - 251

Tried again today on 5.4.3 with exactly the same settings above as I have on 5.2.0. The first game I tried this time (Animal Crossing) worked but running another game (New Super Mario Bros) after rebooting led to a black screen.

**Comment by Fledge68** [comment]
so if you turn off wiiu and turn it back on then load wiiflow does it load the first game again?
is it only when you return to wiiflow after loading a game that any new game won't load?
This is really weird that the very first game loads and plays but after that every game won't load ever again.
