### ISSUE TITLE
Overscan controls

### ISSUE THREAD

**Issue by gingerbeardman** [Fledge68/WiiFlow_Lite#148]
You suggested you would add these.

I do think they would be useful.

**Comment by Fledge68** [comment]
but then i realized that setting the screen width and height (on page 5 or 6 of settings) did the same thing as usb loader gx's overscan settings.

**Comment by gingerbeardman** [comment]
I'll have to compare :)

**Comment by gingerbeardman** [comment]
Solved by getting pixel perfect display using Wii > HDMI > VGA on a 640x480 panel.
