### ISSUE TITLE
WFL stucks at black screen

### ISSUE THREAD

**Issue by niansa** [Fledge68/WiiFlow_Lite#149]
Hi, I was trying to get it to work on my console, however it stucks at an entirely black screen. When I hit the power button once the WFL startup screen appears but does not continue doing anything.

**Comment by gingerbeardman** [comment]
Tell us more.

How did you install it?

Did you copy the /wiiflow folder containing themes?

SD or USB? What format disc?

**Comment by niansa** [comment]
I waited 1 minute

I installed WFL to the apps folder as any other homebrew

Yes, I did copy the /wiiflow folder

CD card, no games yet

**Comment by gingerbeardman** [comment]
Try it again with at least one game?

**Comment by niansa** [comment]
Where do I have to store the games?

**Comment by gingerbeardman** [comment]
https://sites.google.com/site/wiiflowiki4/installing-wiiflow

**Comment by niansa** [comment]
Yeah thx, I'll try

**Comment by niansa** [comment]
I created the wbfs directory and added some games. The start animation appears directly now but then it gets stuck here:
![grafik](https://user-images.githubusercontent.com/20720267/75562557-0f0f6100-5a49-11ea-9a36-58fe6d2d16ee.png)

**Comment by niansa** [comment]
![grafik](https://user-images.githubusercontent.com/20720267/75563086-053a2d80-5a4a-11ea-820d-89dfbad35a7d.png)
Just a short question, is it intended to look like this?

**Comment by gingerbeardman** [comment]
I recommend ModMii to get your Wii mod operating perfectly. It gives you wizard and bespoke guide to set your mod perfectly.

You can give it a [sysCheck](https://gbatemp.net/threads/syscheck-hacksden-edition.356133/) CSV report to get a shorter bespoke guide.

Download: https://sourceforge.net/projects/modmii/
Support: https://gbatemp.net/threads/modmii-for-windows-official-support-topic.207126/

**Comment by niansa** [comment]
Thank you, worked!
