### ISSUE TITLE
[BUG] "Screensaver" option behaves oddly

### ISSUE THREAD

**Issue by gingerbeardman** [Fledge68/WiiFlow_Lite#15]
Go to 9/11

- Screensaver = Off
- Click
- Screensaver = Off, still
- Click 
- Screensaver = On

Go to another page, and back to 9/11

- Screensaver = Off

**Comment by Fledge68** [comment]
just checked. the first click is not changing the text. click it just once and the text doesn't change. goto another page and the text will update. not sure why yet

**Comment by gingerbeardman** [comment]
Deleting the .ini and starting over does not help

Sounds like a simple logic problem with these new settings.

**Comment by Fledge68** [comment]
no just another very weird issue with wiiflow. thanks for letting me know.
