### ISSUE TITLE
Splash screen flashes after booting 5.4.1

### ISSUE THREAD

**Issue by tictackiller** [Fledge68/WiiFlow_Lite#150]
Hey, the title says it all. Once wiiflow is booted the splash screen logo keeps popping up and going away about 2 times a second till I select a plug in from the menu then it stops and everything is fine. Only happens to me on 5.4.1. Updated everything from 5.4.0. except the covoerflow.ini and default.ini.
Other than that I LOVE WIIFLOW LITE!:)

**Comment by Fledge68** [comment]
Is this still a problem? did you fix it? did v5.4.2 fix it?

**Comment by tictackiller** [comment]
Problem is still there with 5.4.3

**Comment by Fledge68** [comment]
@gingerbeardman any idea why?

this is the weirdest thing i've ever heard. sounds to me like he might have source menu on start. but i would think the splash screen would stop being drawn and be replaced by the source menu background image.

**Comment by gingerbeardman** [comment]
Yeah I read this issue but have no idea about why it might happen. I'd suggest a clean install to be sure everything is as it should be?

**Comment by tictackiller** [comment]
It does only happen with source menu on start. I have always had this on pre 5.4.1 with no issues
 I have replaced the entire contents of: App, themes_lite, languages, plugins_data, source_menu folder.  Still no luck. What else should I try to replace? I have tried this on two different wiis.
If it helps, just after the splash screen disappears the screen flashes a green kind of static and then shows the source menu with the splash screen flickering

**Comment by gingerbeardman** [comment]
Can you try starting from a blank SD card?

Otherwise, I'd recommend ModMii to check your Wii CFW is configured optimally.

**Comment by Fledge68** [comment]
@tictackiller so after the splash screen appears do you ever see the animated wait graphics?
you never mention this.

**Comment by tictackiller** [comment]
The animated is the one with wiiflow in the center and covers glowing in and out of the sides?
The animated graphics is the splash screen that flashes. I will test on a fresh sd and report back. 

On a side note, not to complicate things, am I able to pair a new Wii mote on Wiiflow?

**Comment by Fledge68** [comment]
I think i know what your problem is. The splash screen is the first static
image you see then the animated loading images. With source on start most
people use sourceflow which turns off the animated images but you are using
the regular source menu. I believe the code doesnt shut off the animation
until you select a source which loads a coverflow. I will double check this
soon.

**Comment by Fledge68** [comment]
@tictackiller here try this wf5.4.3 boot.dol it should fix your problem.

https://www.mediafire.com/file/9zz8sm4xu6r1d99/wf5.4.3SM_fix.zip/file

**Comment by tictackiller** [comment]
The new boot works perfectly! 
And I can confirm that it was that I wasn’t using source flow. 
I also noticed that when using source flow when turning the Wii and pushing B it takes you back to the app you left off at. 
When not using source flow pushing B after starting wii takes you to an app that has no content. 
Thank you so much for your help!

**Comment by gingerbeardman** [comment]
The B button issue is covered in #126

**Comment by Fledge68** [comment]
I'll commit the fix soon. in the mean time I'm closing this.

**Comment by tictackiller** [comment]
I don’t think that is referring to the same B thing I’m talking about, 
It only happens again when source flow is off.
But not a big issue just was wondering if both were related.

**Comment by gingerbeardman** [comment]
Yes, I run with source flow off.

**Comment by Fledge68** [comment]
@tictackiller try this boot.dol
it should fix your issue with pressing B.

https://www.mediafire.com/file/c66ltmll72uypmd/wf5.4.3SM_fix2.zip/file

**Comment by tictackiller** [comment]
Works flawless! Thank you so much!
