### ISSUE TITLE
WiiFlow vWii Games boot to a Black screen.

### ISSUE THREAD

**Issue by GABO1423** [Fledge68/WiiFlow_Lite#151]
Yep, I'm one of the victims of this issue too.
Essentially, 90% of time I tried to boot up a game in the latest version of WiiFlow it ends up on a black screen, forcing me to unplug the console.
I then downgraded to version 5.2.0, and while it works better, it still ends up on a black screen 50% of the time.
cIOSes are correctly installed and I tried the force cIOS feature, no difference was made on version 5.4.1 but on version 5.2.0 it always ends on a black screen.
I'm loading games from a microSDXC card.
If you need additional information, please let me know.
Thanks in advance.

**Comment by gingerbeardman** [comment]
See: https://github.com/Fledge68/WiiFlow_Lite/issues/149

And please report back with the results of each test/suggestion.

**Comment by GABO1423** [comment]
Here's the problem, this is the vWii not the Wii, therfore ModMii will not help at all. What I can do, however, is perform a syscheck. I'll do that and report back with the results.

**Comment by gingerbeardman** [comment]
@GABO1423 maybe see what ModMii thinks of the SysCheck also?

**Comment by GABO1423** [comment]
Here's the SysCheck results:
Region: NTSC-U
System Menu 4.3U (v609)

Drive date: 06.28.2011
Homebrew Channel 1.1.2 running on IOS58

Console ID: 608774960
Console Type: vWii
Shop Channel Country: United States (49)
Boot2 v0
Found 137 titles.
Found 36 IOS on this console. 0 of them are stubs.

vIOS9 (rev 1290): No Patches
vIOS12 (rev 782): No Patches
vIOS13 (rev 1288): No Patches
vIOS14 (rev 1288): No Patches
vIOS15 (rev 1288): No Patches
vIOS17 (rev 1288): No Patches
vIOS21 (rev 1295): No Patches
vIOS22 (rev 1550): No Patches
vIOS28 (rev 2063): No Patches
vIOS31 (rev 3864): ES Identify, NAND Access
vIOS33 (rev 3864): NAND Access
vIOS34 (rev 3864): NAND Access
vIOS35 (rev 3864): NAND Access
vIOS36 (rev 3864): NAND Access
vIOS37 (rev 5919): NAND Access
vIOS38 (rev 4380): NAND Access
vIOS41 (rev 3863): NAND Access
vIOS43 (rev 3863): NAND Access
vIOS45 (rev 3863): NAND Access
vIOS46 (rev 3863): NAND Access
vIOS48 (rev 4380): NAND Access
vIOS53 (rev 5919): NAND Access
vIOS55 (rev 5919): NAND Access
vIOS56 (rev 5918): NAND Access
vIOS57 (rev 6175): NAND Access
vIOS58 (rev 6432): NAND Access, USB 2.0
vIOS59 (rev 9249): NAND Access
vIOS62 (rev 6942): NAND Access
vIOS80 (rev 7200): NAND Access
vIOS236 (rev 65535): NAND Access
vIOS248[56] (rev 21010, Info: d2x-v10beta52-vWii): NAND Access
vIOS249[56] (rev 21010, Info: d2x-v10beta52-vWii): NAND Access
vIOS250[57] (rev 21010, Info: d2x-v10beta52-vWii): NAND Access
vIOS251[58] (rev 21010, Info: d2x-v10beta52-vWii): NAND Access
vIOS512 (rev 7): No Patches
vIOS513 (rev 1): No Patches

**Comment by GABO1423** [comment]
> @GABO1423 maybe see what ModMii thinks of the SysCheck also?

Sorry, but I believe that ModMii is intended just for the regular Wii consoles and I don't believe that ModMii is intended for the vWii (Wii U) so I don't think that in this case, ModMii is an option.

**Comment by gingerbeardman** [comment]
@GABO1423 ModMii is a Windows app that can, amongst other things, scan SysCheck results CSV files and give you a verdict on what could be more optimal. It can also prepare a bunch of WADs to install to enact that advice of improving your Wii setup (which you are correct should only be installed on a Wii, _not_ a vWii). 

So, please, prepare a SysCheck CSV and run it through ModMii on Windows and see what it says. I'm not an expert on interpreting SysCheck results, but ModMii is.

**Comment by gingerbeardman** [comment]
Also, perhaps the issue is the microSD card? Try another and/or check that it is formatted with 32KB block size.

**Comment by gingerbeardman** [comment]
Also can you try WFL 5.2.0? See: https://github.com/Fledge68/WiiFlow_Lite/issues/146

**Comment by gingerbeardman** [comment]
Also, I'd be interested to know the results of 5.2 and latest WFL with `Force CIOS = yes` and `IOS = Auto` settings.

**Comment by GABO1423** [comment]
> Also, perhaps the issue is the microSD card? Try another and/or check that it is formatted with 32KB block size.

No, because this SD card worked flawlessly with CFG USB Loader and still works well on WiiFlow 5.2.0 (besides the occasional black screens) as well as Nintendont, and it is already formatted correctly. 
> Also, I'd be interested to know the results of 5.2 and latest WFL with `Force CIOS = yes` and `IOS = Auto` settings.

I mentioned the results on the first post, no difference was made on version 5.4.1 while on version 5.2.0 it always ended on a black screen.


> @GABO1423 ModMii is a Windows app that can, amongst other things, scan SysCheck results CSV files and give you a verdict on what is wrong/right with your Wii setup.
> 
> (It can also prepare a bunch of WADs to install to enact that advice of improving your Wii setup, which you are correct should only be installed on a Wii, _not_ a vWii).
> 
> So, please, prepare a SysCheck CSV and run it through ModMii on Windows and see what it says. I'm not an expert on interpreting SysCheck results, but ModMii is.

I'll try that and report back with the results.

**Comment by GABO1423** [comment]
These are the results: 
Your unique list of WADs to install are as follows:
IOS11v16174(IOS60v6174[FS-ES-NP-VP-DIP])
IOS20v16174(IOS60v6174[FS-ES-NP-VP-DIP])
IOS30v16174(IOS60v6174[FS-ES-NP-VP-DIP])
IOS40v16174(IOS60v6174[FS-ES-NP-VP-DIP])
IOS50v16174(IOS60v6174[FS-ES-NP-VP-DIP])
IOS52v16174(IOS60v6174[FS-ES-NP-VP-DIP])
IOS60v16174(IOS60v6174[FS-ES-NP-VP-DIP])
IOS70v16174(IOS60v6174[FS-ES-NP-VP-DIP])
IOS80v16174(IOS60v6174[FS-ES-NP-VP-DIP])
cIOS202[60]-v5.1R
cIOS222[38]-v4
cIOS223[37-38]-v4
cIOS224[57]-v5.1R
cIOS249[57]-d2x-v8-final
cIOS250[56]-d2x-v8-final
RVL-mios-v10
IOS9-64-v1034
IOS12-64-v526
IOS13-64-v1032
IOS14-64-v1032
IOS15-64-v1032
IOS17-64-v1032
IOS21-64-v1039
IOS22-64-v1294
IOS28-64-v1807
IOS31-64-v3608
IOS33-64-v3608
IOS34-64-v3608
IOS35-64-v3608
IOS36-64-v3608
IOS37-64-v5663
IOS38-64-v4124
IOS41-64-v3607
IOS43-64-v3607
IOS45-64-v3607
IOS46-64-v3607
IOS48-64-v4124
IOS53-64-v5663
IOS55-64-v5663
IOS56-64-v5662
IOS57-64-v5919
IOS58-64-v6176
IOS61-64-v5662
IOS62-64-v6430

**Comment by GABO1423** [comment]
But again, since I can't install anything from ModMii on my vWii, I don't think that this is going to be useful.

**Comment by GABO1423** [comment]
So I decided to retry the tests with the force cIOS feature, these are the new results:
5.4.1:
249: Black Screen
250: Black Screen
251: Black Screen
Auto: Black Screen
Disabled: 50/50 chance of it working.
5.4.0:
249: Black Screen. 
250: Black Screen. 
251: Black Screen. 
Auto: Black Screen. 
Disabled: 50/50 chance of it working. 
5.2.0:
249: Works! 
250: Works! 
251: Works! 
Auto: Works! 
Disabled: Black Screen. 
For these tests, I deleted WiiFlow and reinstalled it manually before moving to a another version. That is probably the main reason that 5.2.0 offered WAY different results than before. So for now I'll stick to 5.2.0.

**Comment by GABO1423** [comment]
However, why the new versions don't work? I think that should be something to take a look at.

**Comment by GABO1423** [comment]
I'll close this issue for now, since I got WiiFlow to work at all.

**Comment by gingerbeardman** [comment]
Thanks for your extensive testing!

If you have a little more time could you test these two: https://github.com/Fledge68/WiiFlow_Lite/issues/146#issuecomment-584913993

**Comment by GABO1423** [comment]
Unfortunately, both of those links are dead.

**Comment by gingerbeardman** [comment]
Ah, any ideas @Fledge68

**Comment by Fledge68** [comment]
Try the 5.4.2vidfix dowload. Or the 5.4.2 beta compiled with the latest
devkitpro. Both downloads can be found on the wiiflow lite gbatemp thread.
Both of them were compiled with the optimization flag -o2 instead of -os.
One user did report that it fixed hard drive issues for them. Im on my
phone so i dont have the links handy.

**Comment by GABO1423** [comment]
Sure thing! I'll report back with the results.

**Comment by Fledge68** [comment]
The beta compiled with the latest devkitpro will also require the new bin
files as well.

**Comment by GABO1423** [comment]
Here are the results:
5.4.2 Beta:
Disabled: Works!
Auto: Black Screen.
249: Black Screen.
250: Black Screen.
251: Black Screen.
I wasn't able to find where exactly the 5.4.2 vidfix was, so I only tested the beta. But this has been the best results I got out of anything above 5.2.0.

**Comment by GABO1423** [comment]
These results have been very interesting indeed, 5.2.0 worked flawlessly if force cIOS is used at all while  the 5.4.2 beta works flawlessly if I don't use force cIOS at all. While 5.4.0 and 5.4.1 don't work at all with force cIOS and it is almost unusable for loading games from an SD card.

**Comment by Fledge68** [comment]
5.4.2vidfix is actually titled 5.4.1vidfix.

i assume that disabled means force cios = off?
strange that works but none of the cios choices work. 

for starters with force cios off it means that when you launch a game wiiflow has to switch from IOS58 to a cios. when it does that it unmounts all devices and remounts them after the switch. maybe your device needed that remount or extra time.

**Comment by GABO1423** [comment]
Yes, disabled means the options is turned off.
I'll test the vidfix and report back with the results.

**Comment by GABO1423** [comment]
Here are the results of the vidfix version:
Auto: Works!
249: Works!
250: Works!
251: Works!
Disabled: Works! (Strangely, the first boot took a decent amount of time but after that it was fast)

Overall, the results are comparable to 5.2.0, because both of them booted the games FAST. However, the simple fact that all of the options worked, makes this the best results out of any version I tested.

**Comment by Fledge68** [comment]
hmmm ok. very odd. i'm surprised the newest one with compiled with the latest devkitpro doesn't work the same as the vidfix one. stick with the vidfix for now. i do have 5.4.2 almost ready. hopefully it work for you.

**Comment by GABO1423** [comment]
Thanks! The only thing that sucks is that it now does not detect my cheat codes at all, while the other versions did. That is another issue entirely, but just wanted to let you know. Hopefully 5.4.2 works just as well as the vidfix version.

**Comment by GABO1423** [comment]
UPDATE:
Ok, now the vidfix version is working much like 5.4.0 and 5.4.1, now all options have a 50/50 chance of working. same applies to the 5.4.2 beta. I'll stick to 5.2.0 until the new release.

**Comment by gingerbeardman** [comment]
Thanks so much for sticking with this @GABO1423 !

**Comment by Fledge68** [comment]
please try v5.4.2. i reverted a change that might have affected things for you.

**Comment by GABO1423** [comment]
Alright, I'll try it and report the results.

**Comment by GABO1423** [comment]
Here are the results:
Disabled: Works!
Auto: Works! (However, the first try ended in a Black Screen, after that it worked flawlessly)
249: Works!
250: Works!
251: Works!

**Comment by GABO1423** [comment]
What was the change you reverted? Because it seems that change was the culprit of WiiFlow screwing up on my vWii.

**Comment by GABO1423** [comment]
Nevertheless, 5.4.2 works great!

**Comment by Fledge68** [comment]
Ok good hopefully its not 50 50 like other times

**Comment by GABO1423** [comment]
No kidding, if that DOES happen somehow (hopefully, it won't) I'll reopen this issue.

**Comment by GABO1423** [comment]
So... this issue happened again on the newest 5.4.4 version, here is the new behavior:
Disabled: Works!
AUTO: Black screen.
249: Black screen.
250: Black screen.
251: Black screen.

**Comment by GABO1423** [comment]
For SD cards users, version 5.4.3 is still the best one to use.

**Comment by Fledge68** [comment]
first - If its working with force cios disabled whats the problem? just use force cios off.

second - i changed nothing to do with sd and usb mounting. you did change the bins in the bin folder?

**Comment by GABO1423** [comment]
First - Nothing, but it is still worth mentioning.
Second - Yes, I changed the bin folder.

**Comment by OoIceDeepoO** [comment]
I am using wiiflow on a wii and I have a small piece of info that might help. I was getting the black screens, so I updated my wiiflow install and I was not getting them initially, but then more and more games were getting them. It seemed like some games I would log into once and then I would get it. Then to make things super weird, every third game that legitimately loaded when I would push start to exit out, the exiting menu would be in one of the Asian languages. All my languages in wiiflow and the wii were still set to English. Here is the interesting part though. If I go and delete the wiiflow file in the NAND, it all works again and I can start the cycle all over. So, apparently something written in that save file causes the black screens for those games.

**Comment by GABO1423** [comment]
@OoIceDeepoO What you are describing has almost nothing to do with my experiences besides the black screen issues. Especially since the black screen appears on all games without fail unless I change the force cIOS settings. In reality, the newest version of WiiFlow works perfectly fine with that feature turned off. The main reason this issue is not closed is just so that @Fledge68 knows that while the issue is not as severe as before, it is still present and could be fixed in a future version should he want to. But I still appreciate the information that was shared and I'm glad you were able to fix the black screen issues you had.

**Comment by gonefishing1975** [comment]
Hey
I have a question about playing Wii games in vWii on my Wii U. I open WiiFlow and when I try to play a Wii gamne the screen either goes black or an error dump shows up. I tried different CIOS settings but they just win;t work in WiiFlow. USB Loader GX seems to work. All my classic systems work in WiiFlow like NES, SNES etc. Any ideas why it won't work? It's the same setup I use on just the Wii and it works no issues at all

**Comment by gingerbeardman** [comment]
@gonefishing1975 please start your own issue rather than posting your issues to multiple existing issues

**Comment by hazbeans** [comment]
same here,  idk what to do

**Comment by gingerbeardman** [comment]
@hazbeans the only think you can do is confirm all your setup as something somewhere is wrong
