### ISSUE TITLE
WiiFlow 5.4.2 can't detect cheat codes.

### ISSUE THREAD

**Issue by GABO1423** [Fledge68/WiiFlow_Lite#153]
Yep, from one fatal issue to one that's not as bad.
WiiFlow 5.4.1 to 5.2.0 detected the cheat codes that I had perfectly, but now on 5.4.2 it just displays the message: "Downloaded cheat file has no cheats!"  when it clearly does. The same message appears when I download the cheat codes for a game directly from WiiFlow. Any idea what could be causing this issue? Thanks in advance. (P.S Thanks anyway for fixing my other issue with 5.4.2 @Fledge68 , although I have this new issue, I'll take it over the Black Screen shenanigans)

**Comment by Fledge68** [comment]
Ill look into it

**Comment by Fledge68** [comment]
do the text files that downloaded actually have cheats? that message means a cheat txt file was downloaded but doesn't actually contain any cheats. this sometimes happens.
 does this happen all the time?

@gingerbeardman does this happen for you?

**Comment by GABO1423** [comment]
Yes, it does have cheats. It just does not detect them whatsoever, the only thing WiiFlow knows is that there is a file in there. And if that was the issue, then why do the cheats work on versions lower than 5.4.2?

**Comment by gingerbeardman** [comment]
I tried downloading some cheats this week and they both displayed that message, I assumed (perhaps wrongly) that there were no cheats for those games.


I believe I'm still on 5.4.0 (does it say on WFL about screen, I can check).

**Comment by gingerbeardman** [comment]
Just confirmed this (we're all at home anyway, right?)

1. I was on 5.4.0 and downloaded cheats for a game successfully
1. Confirm there are cheats listed in the UI for that game
1. Update to 5.4.2 (including new bins)
1. Go to cheats on the previously chosen game
1. Shows as "Downloaded cheat file has no cheats!"

ps: it's still not possible to re-download cheats for a game, I had previously mentioned this but forgot to file an issue. So see #155

**Comment by Fledge68** [comment]
Im at work. Wally world. Ill fix it this weekend. Something is compiling
differently.  I didnt change that code.

**Comment by gingerbeardman** [comment]
For that message to display the following checks have to fail

https://github.com/Fledge68/WiiFlow_Lite/blob/95a8bfda0573693e3a0ab95103f63dc7ac0c971b/source/menu/menu_cheat.cpp#L219

https://github.com/Fledge68/WiiFlow_Lite/blob/95a8bfda0573693e3a0ab95103f63dc7ac0c971b/source/menu/menu_cheat.cpp#L250

perhaps something funky compiling out of this line:

https://github.com/Fledge68/WiiFlow_Lite/blob/95a8bfda0573693e3a0ab95103f63dc7ac0c971b/source/menu/menu_cheat.cpp#L54

**Comment by GABO1423** [comment]
Speaking of the issue you have opened, I tried the workaround in 5.4.2 and the results weren't different. I also found this issue to be present on both the 5.4.1 vidfix and the 5.4.2 beta that I tested previously. So something had to change from the vidfix version onward.

**Comment by Fledge68** [comment]
try this boot.dol - https://www.mediafire.com/file/m14ktaeot356lw4/wf5.4.2cheatfix.zip/file

it works for me.

i found an error in:
`bool GCTCheats::IsCode(const std::string& str)
{
	if (str[8] == ' ' && str.size() >= 17)
	{
		// accept strings longer than 17 in case there is a comment on the same line as the code
		char part1[9];
		char part2[9];
		snprintf(part1,sizeof(part1),"%c%c%c%c%c%c%c%c",str[0],str[1],str[2],str[3],str[4],str[5],str[6],str[7]);
		snprintf(part1,sizeof(part2),"%c%c%c%c%c%c%c%c",str[9],str[10],str[11],str[12],str[13],str[14],str[15],str[16]);
		if ((strtok(part1,"0123456789ABCDEFabcdef") == NULL) && (strtok(part2,"0123456789ABCDEFabcdef") == NULL))
			return true;
	}
	return false;
}`

the second snprintf should be snprintf(**part2**,sizeof(part2) not snprintf(**part1**,sizeof(part2)

I checked the history of gct.cpp and it doesn't even show where this was changed. apparently its been this way for a long time which makes me wonder how in the heck cheats even worked before and why all  of sudden they stopped?

**Comment by GABO1423** [comment]
Yep, this fixed it.

**Comment by game174master** [comment]
Can you please re-upload the file? The original link you have is broken.
