### ISSUE TITLE
Not possible for cheats to be re-downloaded

### ISSUE THREAD

**Issue by gingerbeardman** [Fledge68/WiiFlow_Lite#155]
1. Download cheats for a game
2. Notice outside of WFL that there are new cheats for a game
3. Try to re-download the cheats for that game

Workaround
1. manually delete cheat file outside of WFL
1. download cheats again using WFL

**Comment by Fledge68** [comment]
- also noted that holding 1/x and pressing 2/y will delete the current cheat files so you can re download if there's a need to.

https://github.com/Fledge68/WiiFlow_Lite/commit/c80b3a327731dad139c60efb7c825684b19a5cee
