### ISSUE TITLE
[BUG] Downloaded cheats file contains no cheats

### ISSUE THREAD

**Issue by volt72** [Fledge68/WiiFlow_Lite#156]
I am currently using the v5.4.2 March 19th 2020 update and everything works as intended besides downloading cheat files, downloading or adding them manually results in the same error (Downloaded cheats file contains no cheats). I took a look at the files wiiflow_lite downloaded and they look fine so I am not too sure what the issue is.

**Comment by Fledge68** [comment]
see issue #153 
its been fixed and i provided a link in my last comment.
