### ISSUE TITLE
Wii64 black screen, wii64 or wiilite?

### ISSUE THREAD

**Issue by tictackiller** [Fledge68/WiiFlow_Lite#161]
everytime I load a rom with wii64 1.2 the screen goes black, but the audio still plays and I can get to wii64 menu, just no video works. 
I have everything on USB. No sd.  
This may be a wii64 problem? 
Thank you.

**Comment by gingerbeardman** [comment]
Does it work when using Wii64 outside of WFL?

Does your TV support the video output of Wii64?

**Comment by tictackiller** [comment]
Alright so after hours of testing I’ve determined that Wii64 1.2 works awesome if booted from the SD card in both wiiflow and browser 
When booting from wii64 from usb it doesn’t work in wiiflow or home brew browser. 
So looks like a wii64 problem, any guide how to tell it to boot from usb not sd? 
Thank you. You can close this.

**Comment by gingerbeardman** [comment]
No idea, sorry.

Also, have you tried Not64?
