### ISSUE TITLE
can't save directly on sd emunand?

### ISSUE THREAD

**Issue by sechiand** [Fledge68/WiiFlow_Lite#162]
Excellent well developed program, I can't save EMUNAND directly to SD in the desired folder, apparently it needs a subfolder (default or other ..).
It is possible to save directly under the SD folder: / nand /?
Attention SD: / nand / not SD: / nands /
Unfortunately I am forced to this setting to adapt to other Loaders already present that are no longer in development on which I have no options (CFG usb loader).
Is there an option to put in the config file for my path?
Thanks

**Comment by Fledge68** [comment]
wiiflow is made to let users have more than one emunand. and each nand needs to be in a subfolder of nands.

so unfortunately you cant save your emunand in just a folder named nand.
can you change the path that cfg loader uses?

**Comment by sechiand** [comment]
Unfortunately no CFG Loader is an old and abandoned project and there is no option to change the directory, it is fixed on SD: / nand.
To solve this problem the only way would be to go back to the WIFLOW4.2.2-R1076 version which allows the choice of the directory, but I am sorry to use an older version.
It is not possible to modify the loader to be able to manually set the directory, doesn't it seem like a bad idea?

**Comment by Fledge68** [comment]
Why do you want to use an old and abandoned project (CFG Loader)? why not use wiiflow 5 or the latest usb loader gx?

or another question why do you need two different loaders for your emu nand? why not choose one or the other?

**Comment by sechiand** [comment]
Because it's done well and I'm fond of it, it's the first.
I use multiple Loaders because when one does not work for a game it is easy and fast to try with another and it doesn't cost me anything to keep them.
I also like that they are different and each has its strengths and weaknesses.
Loader GX allows you to freely set all directories, it's a nice plus.
However, that's okay, thanks anyway, it doesn't matter, I thought it was a small change, if there are problems, leave it alone.
Hi,
Andrew
