### ISSUE TITLE
Large split wbfs games not fully deleted

### ISSUE THREAD

**Issue by gingerbeardman** [Fledge68/WiiFlow_Lite#163]
I recently deleted NHL2K10 from my drive using WFL remove game (cross icon) option. 

It only deleted the first 4GB wbfs part. The smaller wbf1 part and containing folder remain. 

I had to delete those manually. And then go through my drive looking for other similar remains.

**Comment by Fledge68** [comment]
can you please try this fix?

https://www.mediafire.com/file/nibbepgu4i4nlib/wf5.4.4_deletefix.zip/file

**Comment by gingerbeardman** [comment]
will do so this evening!

**Comment by Fledge68** [comment]
have you had time yet?

**Comment by gingerbeardman** [comment]
sorry, not yet been working (from home) all day and just about to go straight to bed.

**Comment by gingerbeardman** [comment]
it works!

Thanks

**Comment by Fledge68** [comment]
Thanks.
