### ISSUE TITLE
Untracked files when trying to build

### ISSUE THREAD

**Issue by guitaristtom** [Fledge68/WiiFlow_Lite#167]
After trying to build, all of a sudden I have a bunch of untracked files in my local copy of the project. These _might_ need to be added in to the `.gitignore` file.

```
[~/Documents/wii_references/WiiFlow_Lite]$ gits                                                                                                                                                                                   
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	resources/app_booter/app_booter.elf
	resources/app_booter/build/
	resources/extldr/boot.elf
	resources/extldr/cache.o
	resources/extldr/crt0.o
	resources/extldr/ios.o
	resources/extldr/main.o
	resources/extldr/memory.o
	resources/extldr/string.o
	resources/extldr/usbgecko.o
	resources/extldr/utils.o
	resources/wiiflow_game_booter/booter.elf
	resources/wiiflow_game_booter/build/
	source/loader/alt_ios_gen.h

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by Fledge68** [comment]
does this commit fix your issue?

https://github.com/Fledge68/WiiFlow_Lite/commit/0a14c3a05c704bcbf48087556fe2ebdb2bdc62e6

**Comment by guitaristtom** [comment]
Mostly, thank you. 

It's still mentioning about the out folder, which _if I remember right_ should be completely excluded for C variant languages. I might be wrong though.

![Screenshot from 2020-04-16 17-34-50](https://user-images.githubusercontent.com/6890628/79519395-9d936e00-8008-11ea-8927-7a307c63f1a9.png)

**Comment by Fledge68** [comment]
I don't want to add the bins and dol files to the ignore.
