### ISSUE TITLE
The wiiflow channel does not open

### ISSUE THREAD

**Issue by wuniversales** [Fledge68/WiiFlow_Lite#169]
When started it returns to the main menu of the wii, it does not start wiiflow.

I have the games on the sd card, and the wiiflow files are loaded from the usb, I think that is the error of the channel.

My WiiFlow version: 5.4.3

Could you fix it?
Any help in case it's my problem?
Thank you

**Comment by gingerbeardman** [comment]
What channel are you using?

**Comment by wuniversales** [comment]
I have used the installer "WiiFlow_Channel_Installer_v1.1.zip".

https://code.google.com/archive/p/wiiflow/downloads

But you have that problem ...

**Comment by Fledge68** [comment]
when you run your channel do you ever see the wiiflow graphic (splash screen)?

if not then its not a wiiflow problem. its your channel or your missing ios 58 or you don't have a apps/wiiflow folder with boot.dol inside.

have you even tried launching wiiflow via the hbc?

**Comment by wuniversales** [comment]
Through the homebrew channel, wiiflow works correctly.

But the channel does not start, you don't even see the loading logo.

The wii transition appears, and you go to the main menu.

I leave here all the information on my console.
https://pastebin.com/raw/1bq1C0Ha

IOS 58 is patched with D2x8 ...

Any solution to this?

**Comment by gingerbeardman** [comment]
Use a different channel.

**Comment by wuniversales** [comment]
I have tried with wiki themes
https://sites.google.com/site/wiiflowiki4/forwarder-channels
I have downloaded and installed the "WiiFlow pack 1 fixed" wads.
But keep doing the same ...

The route is correct since in the homebrew channel the application works correctly ...

**Comment by Fledge68** [comment]
just to clarify - are you on a wii or wii u?

I would uninstall the wiiflow channel. and reboot your wii before installing it again.

**Comment by gingerbeardman** [comment]
> The route is correct since in the homebrew channel the application works correctly ...

forwarders look for a specific path, if this does not exist then the channel will not run

HBC uses whatever path you have put the files in, it doesn't care.

so, what are your WFL folders called?

**Comment by wuniversales** [comment]
> just to clarify - are you on a wii or wii u?

It's a wii, it's not a wii u

> I would uninstall the wiiflow channel. and reboot your wii before installing it again.

Nothing, it doesn't want to work.

> so, what are your WFL folders called?

It's all like the "wiiflow_v5.4.3.zip" zip found in
https://github.com/Fledge68/WiiFlow_Lite/releases

At the root of the usb are the "apps" folders with their respective subdirectories, and the "wiiflow" folder, also with their respective subdirectories.

I have removed some trout ios, in case it was that, but nothing at all ...
The channels still do not work ...

I leave here the new report.

https://pastebin.com/raw/XvAM1ZSN

**Comment by Fledge68** [comment]
sorry I have no idea why your forwarder channel is not working.

how did you uninstall it?
what did you use to install it? what wad manager?

I guess you'll just have to use the homebrew channel.

**Comment by gingerbeardman** [comment]
one last thing to try is to use ModMii to get your Wii mods up-to-date

https://gbatemp.net/threads/modmii-for-windows-official-support-topic.207126/

**Comment by wuniversales** [comment]
Nothing, there is no way, I do not understand what happens, with other channels "forwarder" this does not happen to me ...
I'm about to create a channel "forwarder"

**Comment by SoNDRD** [comment]
WiiFlow Channel Installer 1.1 by Fix94. It works for me

**Comment by wuniversales** [comment]
Is there a way to make a channel not a forwarder?
In other words, integrate the program into the wii.

I see that there are several files that the wii is loading.
Can't you put all of that together into a simple "boot.dol"?

It would be nice if it were optional to load those files, that is.
For example, have a default theme, and optionally read other themes on the card, or the usb.

**Comment by Fledge68** [comment]
the reason wii use forwarders now is because if i release i new version of wiiflow. you don't have uninstall and install a new channel every time. you just simply replace the apps/wiiflow folder contents.
plus a forwarder takes up less of your nand free space.

I think you need to get and use anytitle deleter to find your wiiflow channel and completely delete all of its contents.

then try wiiflow channel installer again.

**Comment by wuniversales** [comment]
> the reason we use forwarders now is because if i release i new version of wiiflow. you don't have uninstall and install a new channel every time. you just simply replace the apps/wiiflow folder contents.
plus a forwarder takes up less of your nand free space.

Well, honestly, I prefer to have an integrated channel, although it takes up more space.

So it is not necessary to have a pendrive and an SD card inserted in the console, it would be enough to have a single device (the USB / SD of the games, or both with games) connected ... or not even that, start the disk channel without devices connected ...

Also, with the size issue, you could compress the "boot.dol" with DollZ, so that the file doesn't take up as much space.
It is not the first time that I use DollZ to compress, the application is quite useful and works correctly.

First I compress the "boot.dol" with DollZ, and then I create the WAD (Compressed too) based on that file.

This makes it easier to create a wad (I can create the wad with CustomizeMii).

Obviously, currently I cannot create the integrated channel, since it is mandatory to load external files, so the integrated channel would not work, I would like the loading of external files to be optional ...

Could not load default theme images in "boot.dol" using base64?
All current png from "/apps/wiiflow/imgs" could be removed and changed to base64.
In addition, base 64 images can also be optimized ...
https://www.base64-image.de/

The fact of integrating all this in "boot.dol" does not mean that the forwarder channel stops working, it simply enables the possibility of creating wads without having to insert the USB or SD.

> I think you need to get and use anytitle deleter to find your wiiflow channel and completely delete all of its contents.

I will try to use "anytitle deleter" to solve the forwarder. :)

**Comment by gingerbeardman** [comment]
@wuniversales you have lots of ideas, you should try to implement some of them and file a PR
