### ISSUE TITLE
5.4.2/v5.4.3 not respecting wiiflow_lite.ini

### ISSUE THREAD

**Issue by bcg62** [Fledge68/WiiFlow_Lite#170]
Did something change here? 5.4.1 works for me (some odd flashing at boot, which reloading cache fixes) but when trying to use anything newer it seems my ini is not loaded. 

willflow opens with no graphics/images, its very hard to see anything or navigate, i can manage to get into the path settings which are all pointing to usb even though my config is as follows:

```
[GENERAL]
auto_hide_icons=yes
banner_in_settings=yes
box_mode=yes
cat_startpage=1
cf_locked=yes
cover_buffer=20
cover_prio=4294950906
cover_use_hq=yes
custom_banner_url=http://banner.rc24.xyz/{gameid}.bnr
data_on_usb=no
delete_cover_and_game=no
dir_backgrounds=sd:/wiiflow/backgrounds
dir_banner_cache=sd:/wiiflow/cache/banners
dir_box_covers=sd:/wiiflow/boxcovers
dir_cache=sd:/wiiflow/cache
dir_cart=sd:/wiiflow/cart_disk
dir_cheat=sd:/wiiflow/codes/gct
dir_coverflows=sd:/wiiflow/themes_lite/coverflows
dir_custom_banners=sd:/wiiflow/custom_banners
dir_fanart=sd:/wiiflow/fanart
dir_flat_covers=sd:/wiiflow/covers
dir_help=sd:/wiiflow/help
dir_languages=sd:/wiiflow/languages
dir_list_cache=sd:/wiiflow/cache/lists
dir_music=sd:/wiiflow/music
dir_plugins=sd:/wiiflow/plugins
dir_plugins_data=sd:/wiiflow/plugins_data
dir_screenshot=sd:/wiiflow/screenshots
dir_settings=sd:/wiiflow/settings
dir_snap=sd:/wiiflow/snapshots
dir_source=sd:/wiiflow/source_menu
dir_themes_lite=sd:/wiiflow/themes_lite
dir_trailers=sd:/wiiflow/trailers
dir_txtcheat=sd:/wiiflow/codes
dir_wip=sd:/wiiflow/codes/wip
display_music_info=no
dump_list=no
exit_to=0
game_language=0
hideviews=no
idle_standby=no
language=Default
main_background=
max_fsaa=3
multisource=no
music_fade_rate=8
parent_code=
random_select=yes
randomize_music=yes
returnto=
rumble=yes
save_favorites_mode=no
screensaver_disabled=no
screensaver_idle_seconds=30
sd_only=no
sound_volume_bnr=255
sound_volume_coverflow=255
sound_volume_gui=255
sound_volume_music=255
source_on_start=yes
sources=1
theme=Default
tv_height=468
tv_width=640
tv_x=0
tv_y=0
update_cache=no
url_custom_flat_covers=http://art.gametdb.com/{console}/cover2/{loc}/{gameid}.png
url_custom_full_covers=http://art.gametdb.com/{console}/coverfullHQ2/{loc}/{gameid}.png
url_flat_covers=http://art.gametdb.com/{console}/cover/{loc}/{gameid}.png
url_full_covers=http://art.gametdb.com/{console}/coverfullHQ/{loc}/{gameid}.png|http://art.gametdb.com/{console}/coverfull/{loc}/{gameid}.png
video_mode=1
wiimote_gestures=no
```

thanks.

**Comment by Fledge68** [comment]
so in 5.4.2 i did revert a change to how wiiflow reads the sd card.

your problem sounds like the same problem a user on gbatemp had. his solution was to download wiiflow start configurator. run it and either set force cios on or off. most likely off will work for you.
then exit it and try wiiflow. if it doesn't work then try force cios on.

wf start configurator - http://www.mediafire.com/file/2h1stwpdvd3r04q/wf_start_config.zip/file

**Comment by gingerbeardman** [comment]
I may sound like a broken record, but if you're on a Wii (not Wii U) then use ModMii to get your Wii mods up-to-date. 

https://gbatemp.net/threads/modmii-for-windows-official-support-topic.207126/

If you're on Wii U you can do a sysycheck and use ModMii on a PC to recommend changes.

**Comment by bcg62** [comment]
To try and further troubleshoot:

Removed:
/apps/wiiflow
/wiiflow

deleted wiiflow save data from wii settings.

installed v5.4.3 fresh.

Ran with my HD disconnected, first load no images, no menu, hardly visible UI. - all paths expecting USB and not SD.

Changing the settings to:
Force Load cios: off
Force cIOS Revsion: auto
usb port 0
mount sd only: no  

wiiflow loads from SD but there is this blue flashing untill I reload cache or change source. 

These setting also do not detect my USB HD.

Im on a WiiU. Everything was working as expected on v5.4.1. GC/Wii games are loading without issue off ubs on ULGX.

**Comment by bcg62** [comment]
```
SysCheck HDE v2.4.0 HacksDen Edition by JoostinOnline, Double_A, R2-D2199, and Nano
...runs on vIOS58 (rev 6432).

Region: NTSC-U
System Menu 4.3U (v609)

Drive date: 08.21.2013
Homebrew Channel 1.1.2 running on IOS58

Hollywood v0x21
Console Type: vWii
Shop Channel Country: United States (49)
Boot2 v0
Found 54 titles.
Found 34 IOS on this console. 0 of them are stubs.

vIOS9 (rev 1290): No Patches
vIOS12 (rev 782): No Patches
vIOS13 (rev 1288): No Patches
vIOS14 (rev 1288): No Patches
vIOS15 (rev 1288): No Patches
vIOS17 (rev 1288): No Patches
vIOS21 (rev 1295): No Patches
vIOS22 (rev 1550): No Patches
vIOS28 (rev 2063): No Patches
vIOS31 (rev 3864): No Patches
vIOS33 (rev 3864): No Patches
vIOS34 (rev 3864): No Patches
vIOS35 (rev 3864): No Patches
vIOS36 (rev 3864): No Patches
vIOS37 (rev 5919): No Patches
vIOS38 (rev 4380): No Patches
vIOS41 (rev 3863): No Patches
vIOS43 (rev 3863): No Patches
vIOS45 (rev 3863): No Patches
vIOS46 (rev 3863): No Patches
vIOS48 (rev 4380): No Patches
vIOS53 (rev 5919): No Patches
vIOS55 (rev 5919): No Patches
vIOS56 (rev 5918): No Patches
vIOS57 (rev 6175): No Patches
vIOS58 (rev 6432): USB 2.0
vIOS59 (rev 9249): No Patches
vIOS62 (rev 6942): No Patches
vIOS80 (rev 7200): No Patches
vIOS249[56] (rev 21010, Info: d2x-v10beta53-alt-vWii): NAND Access, USB 2.0
vIOS250[57] (rev 21010, Info: d2x-v10beta53-alt-vWii): NAND Access, USB 2.0
vIOS251[58] (rev 21010, Info: d2x-v10beta53-alt-vWii): NAND Access, USB 2.0
vIOS512 (rev 7): No Patches
vIOS513 (rev 1): No Patches
Report generated on 04/20/2020.
```

**Comment by bcg62** [comment]
Debug log output shows me its trying to read my 2TB wiiu drive and not my drive for wii/gc. I'll have to see if changing the usb # helps.

is `Error: IOS_OPEN(/shared2/menu/FaceLib/RFL_DB.dat, 1) -106` normal?

```
Welcome to WiiFlow WFL 5.4.3!
This is the debug output.
WiiU
vWii Mode
AHBPROT disabled = yes
IOS58 v6432
patched isfs_permissions 1 times.
patched es_setuid 1 times.
patched es_identify 1 times.
patched hash_check 0 times.
patched new_hash_check 1 times.
Init ISFS
Found WiiFlow Save
Loading IOS Settings from wiiflow save
Using IOS58
FAT Partition at sd: mounted.
Changing USB port to port 0....
 * * * * * * * * * * * *
 * HDD Information
 * Sectors: 3906963455
 * Size [Sector Size]: 1.856 TB [512]
 * * * * * * * * * * * *
Running sound thread
Wiiflow boot.dol Location: sd:/apps/wiiflow
Data Directory: sd:/wiiflow
Wii Games Directory: %s:/wbfs
Nintendont found
GameCube Games Directory: %s:/games
Loading cIOS map
Found d2x base 56 in slot 249
Found d2x base 57 in slot 250
Found d2x base 58 in slot 251
Setting Wii games partition to: 1
emu nand path = sd:/vwiinands/default
saves nand path = sd:/vwiinands/default
Error: IOS_OPEN(/shared2/menu/FaceLib/RFL_DB.dat, 1) -106
Bootup completed!
Creating Gamelist
Adding wii list
Games found: 0
Saving IOS Settings to wiiflow save
error msg: Press 'A' to reload WiiFlow
Cleanup Coverflow
Stopping sound thread
Stopped sound thread
MEM1_freesize(): 8703984
MEM2_freesize(): 42458752
IOS58 v6432```

**Comment by bcg62** [comment]
Unplugging my WiiU HD correctly loads my wii/gc HD. Can they not be connected at the same time? I thought this previously used to work?.

Aside from both HD's connected at the same time, in this configuration, the only existing oddity is the flashing screen at startup.

**Comment by bcg62** [comment]
Setting `Source Menu on start` from yes to no resolves the flashing.

**Comment by Fledge68** [comment]
ok haha the blue flashing with source on start is an issue that's been fixed in v5.4.4 which i just released today.

setting force cios to off makes wiiflow use ios58. ios58 tends to not work with everyones usb HDD. force cios to on works better but you are having trouble with cios 249 mounting your sd card.
most likely because you are using d2x-v10beta53-alt-vWii which has issues and is not recommended. you should use d2x beta 52.

**Comment by Fledge68** [comment]
also it sounds like you have 2 usb hdd - one for wii u and one for wii and have both connected at same time. if so that doesn't always work and i think you have to have the wii drive in a specific port. you should really try wiiflow with just the wii drive connected. plus i hope you are using y cables for extra power to the drives.

**Comment by bcg62** [comment]
@Fledge68 Thanks, I will try 5.4.4 shortly.

Right - ios58 does not work for me in ULGX, setting 249/250 does....Everything is working for me now, If I run in to further issues i'll try beta52.

Yes I have 2 drives, both on Y cables.  Ideally i'd like to have them both plugged in at all times to avoid messing with the console and having it in a ready state for anything I'd like to do. I'll be adding ustealth to the wii/gc drive shortly (havent tested it yet).

**Comment by bcg62** [comment]
5.4.4 is good as well.

**Comment by Fledge68** [comment]
ok good to know
