### ISSUE TITLE
WFL 5.4.3 Unable to load USB (unable to progress through sources)

### ISSUE THREAD

**Issue by xmusjackson** [Fledge68/WiiFlow_Lite#171]
I've been using the old wiiflow 4.2.1 until today when I wanted proper nintendont compatibility. I was able to get nintendont to autoboot GameCube games but I've run into a different issue. Once I change the source to GameCube, I'm unable to get back to Wii games due to an exception. I press the source button to Wii channels, then plugins, then to Homebrew apps. If I press once more on the source button, which at this point is a USB icon, wiiflow throws an exception and reloads. I tried setting up a source menu but the Wii button just seems to try to load from USB, throwing another exception. 
System menu: 4.3u
d2x cios v10 installed in 249 base 56 and 250 base 57
Wiiflow 5.4.3 was downloaded from the releases page on this git.
Edit: I forgot to mention I did a clean install of wiiflow, removing the old /apps/wiiflow and /wiiflow directories before adding the new ones.

**Comment by gingerbeardman** [comment]
Just to understand your setup, do you have any USB device plugged in at all? 

If you are running only from SD card, are all your settings pointing to SD and not USB?

**Comment by Fledge68** [comment]
do you have any wii games in a wbfs folder?
if so are they on SD or USB?
and do you use USB at all?

**Comment by xmusjackson** [comment]
There are a few games in the wbfs folder on my SD card. I used to use a USB for games before I upgraded to a 128GB SD, and for a short period I was playing games from both SD and USB. Wiiflow 4.2.1 was loading games from USB and when there was no USB present it would just show no games found. I tried plugging a USB formatted to fat32 into each port in the back, but no luck.

**Comment by Fledge68** [comment]
try wiiflow 5.4.4 but don't use your current wiiflow_lite.ini. move it or rename it so wiiflow 5.4.4 will create a new one.

i just released wiiflow 5.4.4 today and it has a small fix that might even fix your issue.

keep in mind. if you start wiiflow without a usb hdd connected the sd only flag should be set true. to use usb hdd you will need to go to main settings>start settings and turn off sd only.

**Comment by xmusjackson** [comment]
Can confirm, 5.4.4 fixed my issue. Thanks!
