### ISSUE TITLE
[BUG] "Show source menu at startup"

### ISSUE THREAD

**Issue by wuniversales** [Fledge68/WiiFlow_Lite#175]
Do not allow the option "Show source menu at startup" to be activated if there is no source menu available.

**Comment by Fledge68** [comment]
its not font menu.
its source menu.

but thanks for forcing me to look into this because i do see a couple minor things to fix if there is no source menu and this option is set to on. and no i can't just not show it because that would leave a strange empty line on that config page.

**Comment by wuniversales** [comment]
Well, I have translated it from Spanish, but yes, that's what I mean, thanks
