### ISSUE TITLE
opción para juegos en pantalla principal

### ISSUE THREAD

**Issue by hdi2000** [Fledge68/WiiFlow_Lite#177]
Estaría bien tener la opción de que los últimos juegos jugados se mostraran juntos, independientemente de poder usar los favoritos.

**Comment by gingerbeardman** [comment]
> **option for home screen games**
> It would be nice to have the option of the last games played being displayed together, regardless of being able to use the favorites.

**Comment by Fledge68** [comment]
would be nice but aint gonna happen.
