### ISSUE TITLE
Wiiflow unable to load cheats to gamecube games with cheats

### ISSUE THREAD

**Issue by patxielsucio** [Fledge68/WiiFlow_Lite#183]
When i try to load gc games such as Mario sunshine or Zelda Wind waker with cheats nintendont doesent load and shows error CheckForMultiGameAndRegion()  failed.
 Then when i look into the flash drive /games folder where roms are supposed to be i find lots of corrupted files inside.

**Comment by Fledge68** [comment]
this is not a wiiflow issue. its nintendonts.

see here https://github.com/FIX94/Nintendont/issues/361
