### ISSUE TITLE
Issues compiling Latest-ppc-and-libogc branch

### ISSUE THREAD

**Issue by Ntemis** [Fledge68/WiiFlow_Lite#187]
linking ... booter.elf
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/10.1.0/../../../../powerpc-eabi/bin/ld: /opt/devkitpro/libogc/lib/wii/libogc.a(video.o):(.data.TVPal524ProgAa+0x0): multiple definition of `TVPal524ProgAa'; videopatch.o:(.data.TVPal524ProgAa+0x0): first defined here
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/10.1.0/../../../../powerpc-eabi/bin/ld: /opt/devkitpro/libogc/lib/wii/libogc.a(video.o):(.data.TVPal528ProgSoft+0x0): multiple definition of `TVPal528ProgSoft'; videopatch.o:(.data.TVPal528ProgSoft+0x0): first defined here
/opt/devkitpro/devkitPPC/lib/gcc/powerpc-eabi/10.1.0/../../../../powerpc-eabi/bin/ld: /opt/devkitpro/libogc/lib/wii/libogc.a(video.o):(.data.TVPal528Prog+0x0): multiple definition of `TVPal528Prog'; videopatch.o:(.data.TVPal528Prog+0x0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [/opt/devkitpro/devkitPPC/wii_rules:30: /home/demetris/Desktop/WiiFlow_Lite/resources/wiiflow_game_booter/booter.elf] Error 1
make[1]: *** [/home/demetris/Desktop/WiiFlow_Lite/resources/wiiflow_game_booter/Makefile:92: build] Error 2
make: *** [Makefile:12: all] Error 2

**Comment by Fledge68** [comment]
try removing line #76 of resources/wiiflow_game_booter/makefile

remove this line - 					-I$(CURDIR)/$(BUILD) \

**Comment by Fledge68** [comment]
are you on windows?

did you do a clean install of devkitpro?
what are you using to compile wiiflow?

**Comment by Ntemis** [comment]
Am on Linux (Ubuntu 20.04 LTS) and i used dkp-pacman to install the devkitpro

**Comment by Ntemis** [comment]
diff --git a/resources/wiiflow_game_booter/Makefile b/resources/wiiflow_game_booter/Makefile
index d4d2ded3..85bcd681 100644
--- a/resources/wiiflow_game_booter/Makefile
+++ b/resources/wiiflow_game_booter/Makefile
@@ -73,7 +73,6 @@ export OFILES :=      $(CPPFILES:.cpp=.o) $(CFILES:.c=.o) $(sFILES:.s=.o) $(SFILES:.S
 #---------------------------------------------------------------------------------
 export INCLUDE :=      $(foreach dir,$(INCLUDES), -I$(CURDIR)/$(dir)) \
                                        $(foreach dir,$(LIBDIRS),-I$(dir)/include) \
-                                       -I$(CURDIR)/$(BUILD) \
                                        -I$(LIBOGC_INC)
 
 #---------------------------------------------------------------------------------

**Comment by Ntemis** [comment]
Same issue http://dpaste.com/1FRCA90

**Comment by Fledge68** [comment]
37?

restore that line in the makefile (or revert it if you know how)

in resources/wiiflow_game_booter/videopatch.c try adding static before each of the 3 video modes.

lines 10, 45, and 80.

**Comment by Ntemis** [comment]
http://dpaste.com/1T07M56

**Comment by Fledge68** [comment]
ok i see now libogc was updated to 2.0.0 and one  of the changes is - Add missing render modes, fix PAL timings

so that's why i don't get the error. so in videopatch.c add /* before the first video mode line 10
and add line 114 */
this will comment those out since they are now part of libogc

**Comment by Ntemis** [comment]
you did it! thank you

**Comment by Fledge68** [comment]
thanks to you informing me that devkitpro was updated. your welcome.

**Comment by Ntemis** [comment]
PRO support! :+1:

**Comment by eku** [comment]
Hi @Fledge68 I see you did not correct it in videopatch.c. Any shedule to do so?
