### ISSUE TITLE
The WiiFlow dont sees Wii games.

### ISSUE THREAD

**Issue by gegemon2012** [Fledge68/WiiFlow_Lite#188]
Hello!
Help solve the problem. As I understand it, it has a single character ...
Background.
I bought a Wii RVL-001 4.3E PAL without a soft mode.
I installed the softmod using ModMii 6.5.1 together with usb loader GX 3.0 r1272.
Put Priiloader_v0_8_2 in nand boot2 and made backup nand.
Installed / updated IOS / cIOS using PimpMyWii, d2x-cIOS-Installer, ModMiiLite v1.7, MMM over Install/ubdate IOS command - syscheck gx report and PimpMyWii attached.
Problem.
I use usb 3.0 hdd 500gb, two sections - one fat32/ntfs with games in WBFS format, and the second - ntfs without games.
Sees only gamecube games although I checked the "Wii games".
I threw off the games on the flash drive with which I installed the softmod - micro sdhc 32gb samsung, but still only sees the gamecube games.
I threw off games in WBFS format on a usb 2.0 apacer 8gb fat32 flash drive, but still only sees gamecube games.
Put WiiFlow, played with the settings, but still only sees the gamecube games.
HOWEVER, through the file explorer of the WiiFlow loader, he sees and launches a folder with Wii games ...
Help me solving this problem?
[Attached.zip](https://github.com/Fledge68/WiiFlow_Lite/files/4850264/Attached.zip)

P.S. My version WiiFlow - 5.4.6.

**Comment by gingerbeardman** [comment]
can you confirm that your Wii games are in a folder in root of storage at `/wbfs`

**Comment by gegemon2012** [comment]
> 
> 
> can you confirm that your Wii games are in a folder in root of storage at eg `D:\wbfs` that contains one folder per game? you can use a backup manager to make this easier.
Thanks very much!
Your advice really helped me)

**Comment by Fledge68** [comment]
so problem solved? we can close this issue?

**Comment by gegemon2012** [comment]
> 
> 
> so problem solved? we can close this issue?

Yes. Problem is solved!
