### ISSUE TITLE
No cIOS Found

### ISSUE THREAD

**Issue by HotDog1135** [Fledge68/WiiFlow_Lite#189]
I have the black screen problem with my vWii. I tried multiple other releases. When trying 5.4.2, there was an error message saying that there isn't a cIOS file. Can someone help me?

**Comment by HotDog1135** [comment]
I tried using d2x cIOS to get them but they all fail.

**Comment by Fledge68** [comment]
make sure you are installing the vwii d2x cios.
the regular wii d2x cios will not install on wii u vwii.

**Comment by HotDog1135** [comment]
Sorry for the late response. After some trial and error, it finally worked. Thanks @Fledge68
