### ISSUE TITLE
[REQ/BUG] Apply Game Settings to Autoboot Titles

### ISSUE THREAD

**Issue by Hakaisha** [Fledge68/WiiFlow_Lite#190]
Wii, WiiWare, and Gamecube games launch successfully from autoboot buttons in SourceFlow/Menu, but without individual game settings applied.

The game settings I'm referring to are things such as cheats, widescreen patch, IOS, neeK2o, etc. These game settings are correctly applied if the game is launched from the GAME/selected screen, but are seemingly bypassed if the game is autobooted from SourceFlow.

Plugin games and homebrew apps launched with autoboot largely do not share this issue, as their settings are usually handled by the external dol they're booted with.

I am aware this isn't a popular method of loading games, but I am hopeful to change that with Symphonii. The autoboots are a very useful tool to create quick and easy access to your favorite games, regardless of their platform. I personally keep a small collection of autoboot games in their own ini, selectable from the base menu. 

I wasn't sure whether to report this is as a bug or a request, as I do not know if this is the intended function. Either way, I do very much like the idea of being able to autoboot games with their settings intact, if possible.

**Comment by Fledge68** [comment]
noted. and I see the problem. thanks for pointing this out. I didn't even realize it.

**Comment by Fledge68** [comment]
hey can you test this one - https://www.mediafire.com/file/rufeh8it2clh2ms/wfl5_autoboot_test_1_.zip/file

**Comment by Hakaisha** [comment]
Hey, Fledge. Thanks for the reply! Using the test_1 dol, I tested out several autoboots from the different source groups (GCN, Wii, NES plugin, homebrew, NAND).

I have good news and bad news.

The good news is the game settings are now properly applied to Wii, GCN and NAND titles. 

The bad news is I'm now getting a lot of Exception DSI errors and frozen WiiFlow loading animations when booting any title (using any source, from both CoverFlow and Autoboot). Sometimes games do boot properly, sometimes they don't. 

- Thought it was maybe just Autoboot, and decided to boot from CoverFlow instead - DSI exception
- Maybe it's the game settings/cheats? Turned off all game settings - DSI exception
- Maybe it's a cache issue? Reload cache and boot title from CoverFlow or Autoboot - DSI exception
- Force cIOS 249, base 57 d2x v10beta52 at startup is On as usual

There must be some specific situation happening that makes the titles boot properly sometimes, but I'm still unsure what it could be. Right now I can click the game and let WFL crash and reboot a few times, until it finally works without doing anything different.
