### ISSUE TITLE
WiiFlow Black screen when playing Wii games on Wii U in vWii

### ISSUE THREAD

**Issue by gonefishing1975** [Fledge68/WiiFlow_Lite#191]
Hey
I have a question about playing Wii games in vWii on my Wii U. I open WiiFlow and when I try to play a Wii gamne the screen either goes black or an error dump shows up. I tried different CIOS settings but they just win;t work in WiiFlow. USB Loader GX seems to work. All my classic systems work in WiiFlow like NES, SNES etc. Any ideas why it won't work? It's the same setup I use on just the Wii and it works no issues at all

**Comment by Fledge68** [comment]
do not use d2x v10 beta53 alt.
only use d2x v10 beta52. and make sure they are for vwii
also use base 57 or 58.

if that don't work in wiiflow go to main settings>startup settings and set force cios to off or no.

if that don't work you are SOL.

fyi I do have a usb HDD that I have to unplug before i switch to vwii. once I'm in vwii i can then plug it in and it will work with wiiflow. don't ask me why i have no idea.

**Comment by gonefishing1975** [comment]
I used dsx v10 beta 52 vwii. When i ran cios installer i did the setup below 

Procedure for IOS56:
- at "Select cIOS" press right and select "d2x-v10-beta52-vWii" or "d2xv10-beta53-alt-vWii" (not recommended)
- at "Select cIOS base" select "56"
- at "Select cIOS slot" select "249"
press A to install → cIOS 249 installed.

Repeat the above procedure for IOS57:
- at "Select cIOS" press right and select "d2x-v10-beta52-vWii" or "d2xv10-beta53-alt-vWii" (not recommended)
- at "Select cIOS base" select "57"
- at "Select cIOS slot" select "250"
press A to install → cIOS 250 installed.

Repeat the above procedure for IOS58:
- at "Select cIOS" press right and select "d2x-v10-beta52-vWii" or "d2xv10-beta53-alt-vWii" (not recommended)
- at "Select cIOS base" select "58"
- at "Select cIOS slot" select "251"
press A to install → cIOS 251 installed.

**Comment by gonefishing1975** [comment]
I did find this post 


5.4.1:
249: Black Screen
250: Black Screen
251: Black Screen
Auto: Black Screen
Disabled: 50/50 chance of it working.
5.4.0:
249: Black Screen.
250: Black Screen.
251: Black Screen.
Auto: Black Screen.
Disabled: 50/50 chance of it working.
5.2.0:
249: Works!
250: Works!
251: Works!
Auto: Works!

**Comment by Fledge68** [comment]
then i guess you are stuck with 5.2.0

**Comment by gonefishing1975** [comment]
> then i guess you are stuck with 5.2.0

I din't get to try this yet but it was in another post by another user. Is this a possible fix?

**Comment by gingerbeardman** [comment]
@gonefishing1975 from the other threads you have seen, please try everything you think is relevant. 

are you using USB, SD? you could also capture a SysCheck log, and run it through ModMii on your PC to see what holes/quirks there are in your setup.

as for the above, why only post half the results? from the same thread: all subsequent versions to that point in time were reported as working.

5.4.2 https://github.com/Fledge68/WiiFlow_Lite/issues/151#issuecomment-601461543
5.4.3 https://github.com/Fledge68/WiiFlow_Lite/issues/151#issuecomment-616845890
5.4.4 https://github.com/Fledge68/WiiFlow_Lite/issues/151#issuecomment-616845362

**Comment by gingerbeardman** [comment]
> I din't get to try this yet but it was in another post by another user. Is this a possible fix?

we don't know exactly what your problem is, and all versions of WFL are reported as working.

please help us help you.

**Comment by gonefishing1975** [comment]
Seems to work with Force Load CIOS to off and Force CIOS Revision to 250 for 3 3 games I tested

**Comment by unresolvedsymbol** [comment]
You can plug your Wii U USB into the front ports to prevent vWii from seeing them, and WiiFlow subsequently freezing before game load.

**Comment by Fledge68** [comment]
for all those vwii users who say wiiflow v5.2.0 works and any version 5.4.0 onward they have issues.
here is a folder of wiiflow beta commits between version 5.2.0 and 5.40. each one includes the boot.dol and ext_booter.bin. the booter.bin goes in the bins folder of course.
I suggest you download and use 5.2.0 release first. then simply download and plug the boot dol and booter bin to the appropriate folders and try again. be sure to backup your wiiflow stuff before hand.
let me know which downloads work and which don't. maybe this way we can finally figure out what commit between 5.2.0 and 5.4.0 messed things up.

here's the downloads - https://www.mediafire.com/folder/vldp2pufn1r3l/

**Comment by Fledge68** [comment]
this has been fixed by blackb0x (wiidev) in a recent commit so i'm closing it.

**Comment by opmartin** [comment]
I'm experiencing this issue on 5.5.0. I've tried various settings for Force CIOS but nothing works.

**Comment by gingerbeardman** [comment]
@opmartin Given that this issue has long since been fixed and closed, please confirm your setup (see above for which d2x to use and not use) and see https://github.com/Fledge68/WiiFlow_Lite/issues/191#issuecomment-662688195
