### ISSUE TITLE
Crashes when using 900+ games

### ISSUE THREAD

**Issue by Nosen92** [Fledge68/WiiFlow_Lite#193]
Wiiflow instantly crashes (memory dump) when trying to read a hdd with 900+ wbfs games on it.

The same hdd worked fine when it contained 600-700 wbfs games.

Removing any games to reduce the number back to 600 makes wiiflow operate normally again.

HDD formatted as NTFS.

**Comment by Fledge68** [comment]
did you expect there to be no limit? 900+ is an insane amount of wii games. I didn't even know there was that many released for the wii.

so basically there's nothing i can do about this. you've reached your limit at 600-700.

**Comment by Nosen92** [comment]
It may be tough to implement but I don't see how it would be technically impossible.

For instance, the original xbox can handle cover flow of its entire library using a variety of different dashboards.

**Comment by wiidev** [comment]
@Nosen92 Have you tried other loaders? I'd be interested to know if you experience crashes with them too.

**Comment by MarsBars06** [comment]
@Nosen92 It could be that the amount of games is too much for the cache to handle?

**Comment by MarsBars06** [comment]
@Nosen92 
Try the following:
- Try freeing up space on the device which the cache is stored in (most likely your SD card)
- Check the covers for the games; are they the right size?  Are they in the right format?  Are they corrupted?
Hope that helps.

**Comment by LordRofl** [comment]
Nosen92 did something wrong, i have 452 GC and 1209 Wii Games functional with WFL.
