### ISSUE TITLE
Support for new GoldenEye 007 Online (cheat setup)

### ISSUE THREAD

**Issue by gingerbeardman** [Fledge68/WiiFlow_Lite#194]
There's a new way to play _GoldenEye 007_ online. It uses a custom `/codes/SJBE52.gct` file and also a `/gameconfig.txt` which seems to contain patching instructions. 

More info on the Google Doc linked from here: https://gamefaqs.gamespot.com/boards/997757-goldeneye-007/78607431

I've had it working using:
1. Configurable USB Loader
2. USB Loader GX

Apparently it also works using:
1. NeoGamma (from WBFS partition)
2. Gecko OS (from game disc)

Obviously I'd rather use WFL as I use it for everything else and enjoy features like _480p Fix_. 

So I was wondering what's missing for it to work from WFL?

**Comment by Fledge68** [comment]
recently on wiiflow lite gbatemp thread C2PO had issues with gameconfig.txt and using cheats with wiiflow.

I suggest you read all of his posts starting from here - https://gbatemp.net/threads/wiiflow-lite.422685/page-149

maybe it can be of help.

**Comment by gingerbeardman** [comment]
Thanks! That was useful. 

Files need to be as follows:
- `/wiiflow/codes/gameconfig.txt`
- `/wiiflow/codes/gct/SJBE52.gct`

**Comment by gingerbeardman** [comment]
Hi @Fledge68 I hope this finds you well!

Back in August 2020 the GCT for GoldenEye New Server was about 4KB. That worked in WFL just fine.

The latest GCT is 10KB in size. Does not work in WFL, game launches to black screen.

I have one from in between those dates that is 6KB. This works fine in WFL.

So I think there's a size limit somewhere?

I the code I see `#define MAX_GCT_SIZE 2056` but I don't see that being used anywhere?

Am I missing something?
