### ISSUE TITLE
Kirby's Return to Dream Land in SD freeze

### ISSUE THREAD

**Issue by TeenTin** [Fledge68/WiiFlow_Lite#197]
WiiFlow Lite can start Kirby's Return to Dream Land in **SD**, but the game freezes when loading or creating a save.

However, if the game is loaded from **USB**, there are **no problems** at all.

**Comment by gingerbeardman** [comment]
Please only start one issue related to your problem

**Comment by TeenTin** [comment]
I have two different problems.

**Comment by TeenTin** [comment]
I have two different problems.

Matt Sephton <notifications@github.com> 於 2020年8月9日 週日 下午4:57寫道：

**Comment by Fledge68** [comment]
once the game starts it is in the hands of the cIOS. seems the cios you are using has trouble with the sd card or something else.
anyway, try a different cios but this is not wiiflow related so i'm closing it.

**Comment by iGom** [comment]
> once the game starts it is in the hands of the cIOS. seems the cios you are using has trouble with the sd card or something else. anyway, try a different cios but this is not wiiflow related so i'm closing it.

None of any cios worked for me, tested with 5.5.4 commit [1239b90](https://github.com/Fledge68/WiiFlow_Lite/commit/1239b907518adf438fc76eddab78698587f49327) the only solution I discovered to work was to make save file in the Dolphin and copy to the Wii

**Comment by gingerbeardman** [comment]
@iGom see [the comment directly above](https://github.com/Fledge68/WiiFlow_Lite/issues/331#issuecomment-1476577065), even with a save it will freeze at the next cut scene
