### ISSUE TITLE
Games randomly freeze

### ISSUE THREAD

**Issue by MarsBars06** [Fledge68/WiiFlow_Lite#198]
Hello,
I don't know whether this is just me this happens to, but sometimes my games just randomly freeze after they load.
Equipment and software I'm using:
- Wiiflow Lite v.5.4.6 (running of front 2GB SD)
- HDD - 320GB Samsung desktop HDD connected to the WII using a HDD enclosure
- cIOS 236, 249 and 250 installed
- ISOs were ripped with CleanRip(v.2.0.0-datel2)
The ISOs work fine under the Dolphin emulator
Can anybody help please?
Thanks

**Comment by gingerbeardman** [comment]
more information needed please.

> after they load.

at what point? please give some examples.

> sometimes

same place with same game every time?

**Comment by MarsBars06** [comment]
@gingerbeardman As I said, it just does it without warning, happens with all the games.
Before it freezes, I notice that if I'm playing, the BGM stops.
Sometimes it freezes when it's loading but the sound stays on; the loading graphic and the sound loop keeps going forever and doesn't stop.
In both cases, the HDD light just stays on, it doesn't flicker like it does when it's being read.
Thanks for the fast response BTW.

**Comment by gingerbeardman** [comment]
I would recommend trying a different drive, make sure it is correctly formatted. This should rule out some things.

**Comment by MarsBars06** [comment]
@gingerbeardman I'm using a 8GB SanDisk flash drive and now Wiiflow is refusing to load; it just stays at the Wiiflow splash screen.
I've been reading up and there is a anti-sleep cIOS that can be installed with d2x in slots 249 and 250.  I think this is the problem but I don't know which revision needs to be used.  Do you know by any chance?
Thanks.

**Comment by gingerbeardman** [comment]
So did you try a different drive?

We only recommend specific CIOS versions.

**Comment by MarsBars06** [comment]
@gingerbeardman Are those only for Wii U; I'm using the normal Wii.

**Comment by gingerbeardman** [comment]
It's the same for both

See https://wii.guide/cios.html

**Comment by MarsBars06** [comment]
@gingerbeardman Sorry for the trouble.
I just installed the latest d2x cIOS in slots 249 and 250.  It doesn't freeze at all now with the external HDD.
Sorry about the bother and thanks for the help and fast responses.

**Comment by gingerbeardman** [comment]
@MarsBars06 no trouble at all! Glad you got it working. 

Have fun!
