### ISSUE TITLE
2-disc GC games can not load

### ISSUE THREAD

**Issue by TeenTin** [Fledge68/WiiFlow_Lite#199]
WiiFlow Lite works fine with GC games through Nintendont. However, I find that GC games with 2-disc do not work. I have tried Metal Gear Solid and Resident Evil, both are 2-disc games, but fail. When starting the games, I am prompted to pick disc 1 or disc 2. But when I pick disc 1 (or disc 2), I get a black screen and I need to long press the power button to turn off the system. 

P.S.1  When Nintendont is loaded by HBC, both games work perfectly.
P.S.2  The order version of nintendont (e.g. v4.4x) works with WFL, while the latest version v6.4x fails.

**Comment by Fledge68** [comment]
truly mind blowing. I just checked the code and I can't find anything wrong with it. 

gingerbeardman can you confirm his issue?

seems to me wiiflow changes nothing if you select disc 1 and thus should play a game just like a normal gc game.

**Comment by TeenTin** [comment]
I have everything in SD.  No USB HD at all.  Is this related ?

**Comment by TeenTin** [comment]
As I have mentioned, order version of nintendont (e.g. v4.4x) does work.

**Comment by gingerbeardman** [comment]
I'll check in the morning (2AM here) I think I have one dual disc GC game.

**Comment by gingerbeardman** [comment]
I have one GC game, Freaky Flyers, that uses 2 discs. 

They're in the same folder:
- game.iso
- disc2.iso

Both launch fine from WFL (5.4.6)

There's the usual black screen for several seconds whilst Nintendont starts. 

https://imgur.com/a/2FJbPCM

**Comment by TeenTin** [comment]
Oh... so what's wrong in my situation ?  Because of specific games ?  I may want to try Freaky Flyers then...

**Comment by TeenTin** [comment]
@gingerbeardman I have seen your video, I find that my screen to pick disc is different from yours.

https://imgur.com/N5GPlfX

**Comment by gingerbeardman** [comment]
Perhaps we are using different versions of Rhapsodii? I don't think it would matter. 

But I'm interested to know which version of WFL and Rhapsodii you are using.

**Comment by TeenTin** [comment]
How to check ?

**Comment by TeenTin** [comment]
Danimal Master Pack (v5.4)

**Comment by gingerbeardman** [comment]
With Freaky Fliers the game boots in the same way if I pick disc 1 or disc 2. 

I don't know how it would be if I used my original discs. I don't have them here right now. 

Do you have a game that boots differently with disc 2?

**Comment by TeenTin** [comment]
I just have Metal Gear Solid and Resident Evil, and both disc 1 and disc 2 give the same result (i.e. black screen).

**Comment by TeenTin** [comment]
I will try go back to the default theme and test...

**Comment by TeenTin** [comment]
Tested.

- Go back to default theme : 2-disc games work !
- Switch to Rhapsodii theme again : 2-disc games still work !!

I am very surprised that a theme can mess thing up.  Probably the "Danimal Master Pack" has customized the Rhapsodii theme making **strange cache** to cause the problem.

Problem is solved now.  Thank you very much gingerbeardman and Fledge68.  You both are very helpful !
