### ISSUE TITLE
Satellaview magic bug

### ISSUE THREAD

**Issue by Edu789** [Fledge68/WiiFlow_Lite#203]
When using the magic 534E4542 from Satellaview, when you enter to choose the games, you just keep charging, and you don't leave that, you have to turn off the Wii

**Comment by Fledge68** [comment]
if i understand you - it sounds like the BS bios is starting and you enter the house to select a game but what do you mean by keep charging? it appears you are using snes9xgx?

**Comment by Edu789** [comment]
No, in the Wiiflow menu, when I go to the Satellaview source menu, it is loading the same when you add a new plugin, the black screen with the words Wiiflow in the middle ...
I'm using Snes9gx

**Comment by Fledge68** [comment]
so when you are select Satellaview on the source menu it never shows the covers of the games?

**Comment by Edu789** [comment]
No, there is only that black screen written Wiiflow in the center and the covers on both sides moving...

**Comment by Fledge68** [comment]
This is very odd. It works for me. I have satellaview games and can see the covers and can launch them just fine.
the only thing i can think is you must have a corrupted file somewhere (a rom, a cover, a database file) or your usb pen drive has an issue and maybe you should try a different device.
