### ISSUE TITLE
Turn off hd and flash drive in safe mode

### ISSUE THREAD

**Issue by Edu789** [Fledge68/WiiFlow_Lite#204]
Would it be possible to add in a future update, in the option of total shutdown of Wiiflow, to turn off the Hard Disk and Pen Drive in safe mode?

**Comment by gingerbeardman** [comment]
What is safe mode?

**Comment by Edu789** [comment]
It's like when you disconnect Hard Disk or Flash Drive from the pc ...

**Comment by gingerbeardman** [comment]
OK, i think you mean that the WFL should send the sleep command to the drive just before it does Wii shutdown?

**Comment by Edu789** [comment]
Yes, exactly...

**Comment by Fledge68** [comment]
complete shutdown or standby? if standby - no it can not . that's up to the wii and it chooses to keep them on.

**Comment by gingerbeardman** [comment]
In full shutdown the drive should go to sleep on its own (because no power or activity) at least my Western Digital Passport does.

**Comment by Fledge68** [comment]
so if his usb pen drive or hdd is still running after shutdown then he must have his wii set for standby mode. otherwise they will shutdown as well when the we shuts down.

basically there's nothing wiiflow can do about this so i'm closing this.
