### ISSUE TITLE
Doesn't allow loading game under WiiVC 

### ISSUE THREAD

**Issue by unresolvedsymbol** [Fledge68/WiiFlow_Lite#206]
I see that the gamepad is supported, but whenever I inject all I get is an error about not being able to load games in virtual console mode... So why even implement libdrc? Or what's the proper way to inject?

**Comment by Fledge68** [comment]
you can only launch homebrew and gc games via nintendont when launching wiiflow via wiivc inject. wii games and nand games require a cios and cios do not work via wiivc.

**Comment by unresolvedsymbol** [comment]
Ah that explains it. What if we installed cIOS over the IOS WiiVC loads with?
