### ISSUE TITLE
Geckocodes.org -> GameHacking.org

### ISSUE THREAD

**Issue by eku** [Fledge68/WiiFlow_Lite#209]
James0x57 has stopped the cheats database GeckoCodes.org and refers to GameHacking.org as successor.

Time to adapt WiiFLow Lite to new source for cheat download.

**Comment by wiidev** [comment]
GameHacking.org doesn't have all of the codes yet and it doesn't provide a way for applications to download cheats via game IDs.

WiiFlow and Dolphin are using [a mirror of geckocodes.org instead](https://github.com/Fledge68/WiiFlow_Lite/commit/9362fd978985b4e676834bbd517a2db15d068266).
