### ISSUE TITLE
Cant compile master with latest devkitpro

### ISSUE THREAD

**Issue by Ntemis** [Fledge68/WiiFlow_Lite#215]
https://dpaste.com/BT549DMAZ

**Comment by Ntemis** [comment]
Fixing videopatch.c but still errors out here:
https://dpaste.com/FXTZ7TJCX

**Comment by Fledge68** [comment]
use this branch - https://github.com/Fledge68/WiiFlow_Lite/tree/Latest-ppc-and-libogc
if you want to compile with the latest devkitpro.

but i haven't updated it with any of the new changes for a while now.
some day i will update it.

**Comment by Ntemis** [comment]
yes it looked abandoned thats why i tried master
