### ISSUE TITLE
Option to support private servers other than Wiimmfi?

### ISSUE THREAD

**Issue by vaguerant** [Fledge68/WiiFlow_Lite#217]
The "Private Server (Wiimmfi)" option in Wiiflow seems unnecessarily limited. In USB Loader GX, the similar option "Private Server" has three states: `OFF`, `NoSSL only`, and `Wiimmfi.de`. On Wiiflow, it's Wiimmfi or nothing.

I don't have anything against Wiimmfi, I just feel it would be nice if Wiiflow supported other private servers as well--not even at the level of dedicated support that Wiimmfi has, but just enough that users of other servers aren't pushed to other loaders.

**Comment by gingerbeardman** [comment]
What is the use case for this?

**Comment by vaguerant** [comment]
Connecting to any of the other private servers, e.g.: https://github.com/barronwaffles/dwc_network_server_emulator/wiki/List-of-Servers

The DWC network server emulator is open source, so there are the public servers above, and then anybody who wants to can host their own instance as well, e.g. for their friends and family or whatever.

The usual way people take advantage of these servers is to change the DNS on their Wii (or Wii U or DS) to one offered by the private server they want to connect to. On DS, that's all that has to be done, since the SSL code on DS is broken enough that it can be bypassed easily. On Wii (and vWii), you need a no-SSL patch on the games themselves (either applied manually or by a USB loader) so that the Wii won't reject the connections to a non-Nintendo server. The Wiimmfi patch does this, too, it's just that it goes further by patching the `nintendowifi.net` strings to point to `wiimmfi.de` as well.

What I'm asking for is a mode which performs only the SSL patch (editing the URLs to use `http` instead of `https`), while leaving the server strings like `nintendowifi.net` unchanged, since those are handled by the custom DNS. This would allow people to use any private server of their choice by changing their DNS settings, rather than limiting them to Wiimmfi only.

**Comment by gingerbeardman** [comment]
I understand how the servers works. But I'm not seeing a specific use case?

In order for somebody to spend time adding this there needs to be some measurement of how useful it will be for users. For example, yours is the first request about this in years.

To contrast, we know how many people use Wiimmfi (lots).

**Comment by vaguerant** [comment]
Well then firstly, that's not what the term "use case" means. A use case is the specific scenario in which something can be used, i.e. the answer I gave above: the use case for this feature is accessing other servers, end of use case. It sounds like what you're looking for are usage statistics.

I don't know the answer to that and it's somewhat unknowable, since not all private servers are public or share their usage statistics publicly. Anecdotally, I'm guessing it's a lot fewer people than are on Wiimmfi, since that is the de facto standard. There is probably some chicken and egg here, as the only USB loader under current development (Wiiflow) doesn't support non-Wiimmfi private servers, which probably discourages people from using them, which discourages the Wiiflow developers from including support, which discourages people from using them, ...

So in lieu of those hard numbers, a couple of reasons in favor of adding it:
a) Future-proofing. If Wiimmfi ever goes down (in 10 years, 30 years, whenever), support for a non-server-specific way to connect to open private servers in general would mean that Wiiflow doesn't immediately become useless for online play.
b) This feature is already *in* Wiiflow, it's just not exposed separately from the Wiimmfi setting in the GUI. The `https`->`http` patch that already exists is doing exactly this:

https://github.com/Fledge68/WiiFlow_Lite/blob/7eeaf4e0535d020db010eedaaae99661a2aedb05/resources/wiiflow_game_booter/source/patchcode.c#L648-L660

I think the feature is reasonably achievable and would be useful to some subset of users both now and in the future. If the team disagrees or feels that subset is not large enough to warrant the effort, then that's a shame but it's just the nature of feature requests, so oh well.

**Comment by gingerbeardman** [comment]
By use case I meant things like "most Smash players don't use Wiimmfi" or "altWFC is a better option than Wiimmfi for playing GoldenEye". I just made those two up, so I have no idea if they're true or not.

Future proofing is a good idea, but it's work on a feature that may never be needed and so in my personal experience always drops down the list of priorities. But I agree it's a good reason to add this.

That said, I'm sure a PR with this change/proposal would be merged if you have the time and inclination.

**Comment by Fledge68** [comment]
i just checked usb loader gx code and wiiflow (lites) code. they both use the same code to patch the dols wifi connections. the both do the no ssl which basically just changes all https to http. but wiiflow also changes all domains from nintendowifi.net to wiimmfi.de.
i should be able to add just no ssl option.

although i know blackb0x has added other domains to his enhanced version of usb loader gx. (AltWFC and BenFi)

**Comment by Fledge68** [comment]
@vaguerant I know its been a while. I hope you are still there and get this message.

I need you to test this wfl build. download and extract wfl 5.4.8 release.

then download this - http://www.mediafire.com/file/bopmwiatangw0ls/wfl5.4.9beta3.zip/file
and replace those 2 files.
the Private Server option should now allow you to select - Off, No SSL, and Wiimmfi. if using rhapsodii shima theme the button may look a little weird until the theme is updated but it should still work.

please let me know it it's working for you.

**Comment by vaguerant** [comment]
Unfortunately I can't seem to test with this build; I get the (static) Wiiflow logo, then the animated loading screen, and then a DSI Exception:

![2020_11_24 2_30 AM Office Lens](https://user-images.githubusercontent.com/5259025/99981478-8c5fda80-2dfd-11eb-98cd-f25f5b8959c7.jpg)

I first tried updating over my current Wiiflow WFL (5.4.7-->5.4.8-->5.4.9beta3) but when that didn't work, I entirely deleted the Wiiflow folders from both the root and apps folder and started from scratch, but I got the same result regardless.

I'm running a PAL WII U and haven't done anything exotic to my vWii NAND, just installed the Homebrew Channel and cIOSes 249 and 250.

**Comment by Fledge68** [comment]
my bad i forgot i made a change in beta2 that causes that crash if dvdskin_clear.png is missing from the imgs folder.
so download  beta 2 here and use only the imgs folder and contents.
https://www.mediafire.com/file/ulnjzarjh2g3lov/wfl5.4.9beta2.zip/file

now it should work

**Comment by vaguerant** [comment]
Success! I am now able to use other private servers in the beta build. The only exception to this is NAND titles (real or emulated), which don't have the private server option in their settings, but I assume that's the expected behavior. Thanks very much for this, I really appreciate it. I'm happy to consider this issue closed, but I'll leave that up to you. Thanks again!

**Comment by Fledge68** [comment]
so nand titles also need the private server option? do they in usb loader gx?

**Comment by vaguerant** [comment]
They do in USB Loader GX, yes. A lot of WiiWare has online support; e.g. Bomberman Blast, Dr. Mario Online RX, Excitebike World Rally, Mega Man 9 and 10, Tetris Party, Uno. In USBLGX it works exactly the same as for disc games, just enabling Wiimmfi/NoSSL and connecting as normal.

**Comment by Fledge68** [comment]
hmmm. ill look into adding it to wiiflow.

**Comment by Fledge68** [comment]
@vaguerant can you test beta 4 and tell me if private server works for wiiware games?
https://www.mediafire.com/file/mg2c2u1qfzo3zvh/wfl5.4.9beta4.zip/file

@gingerbeardman can you test beta 4 and tell me if the 480p pixel patch works for wiiware/vc games?
note: i do know for some reason you have to turn the apploader option ON (pg 4 i think). for some reason with it off the wii just freezes on a black screen. with apploader ON 480p pixel patch ON works for me but i can't tell any difference in the images.

**Comment by gingerbeardman** [comment]
Will try over the next day or so.

**Comment by vaguerant** [comment]
@Fledge68 Just confirmed private servers working perfectly in WiiWare with the new beta, nice work!

**Comment by gingerbeardman** [comment]
I loaded beta 4 onto my SD card last night but ran out of time to test 480p. Will do so today.
