### ISSUE TITLE
WiiFlow Lite 5.4.7 can not load wii game backup from sd card

### ISSUE THREAD

**Issue by best3140** [Fledge68/WiiFlow_Lite#219]
i use 
- wii Japan firmware version 4.3J
- not install any cIOS
- 16 GB Sandisk sd card contain only we ski(USA) game backup iso rip from cleanup
- set video to (system or ntsc) not sure
when try to play game it will load to black screen and try to read disc. if have disc in drive it will run normal.
if no disc in drive it still alway black screen.
have any suggest .

Best Regards,

**Comment by Fledge68** [comment]
you have to have a cIOS installed to play wii games
and you can't use ISO you have to use wii backup manager to convert the ISO into wbfs files.

**Comment by best3140** [comment]
today i install cIOS to 249, 250 and 251 and test both usb and sd card
i can load game on usb card normal different between usb and sd load
are usb load it will show progress load bar but on sd card it immediate 
load black screen with out show progress bar. any suggestions to check ?

**Comment by Fledge68** [comment]
when you switch from usb to sd are you going to main settings>game partitions and changing the wii games partition to sd?

**Comment by best3140** [comment]
Yes I change it. Today I try again by change NAND emulation to partial, save nand emulation to off, use real nand config to on l, use real nand miis to on.
Game can load normally on sd card.
