### ISSUE TITLE
Cant open my gamecube games

### ISSUE THREAD

**Issue by joaozin121** [Fledge68/WiiFlow_Lite#225]
When i try to open the gamecube games say the loader dont find the gamecube launcher, my games is on SD, with my Wii games, on the "games" folder, and Nintendont is on app folder, if a open the nintendont works fine, only wiiflow cant find the loader.

**Comment by Fledge68** [comment]
make sure you didn't make a spelling mistake for your nintendont apps folder.

sd:/apps/nintendont/boot.dol

also maybe dont use a capital N.   Also make sure you have nintendont set as the GC launcher. It should be by default but maybe you changed once and forgot. if its set to devolution then of course wiiflow won't find the gamecube launcher.

in main settings go to page 3 i think and select gamecube settings and set the loader to nintendont. also select a game and go in the game settings and make sure the loader is set to default or nintendont.
