### ISSUE TITLE
Latest version not launching games for some cIOSes, not loading at all for others

### ISSUE THREAD

**Issue by Hallowizer** [Fledge68/WiiFlow_Lite#227]
Hi! I’ve been using WiiFlow for a while now without issues, on cIOS v6 in slots 249, 250, and 251, but when I updated to the latest version a few days ago, games stopped launching. I tried changing the cIOS to v10 beta52 (same slots) like the guide I was reading said to do, but nothing changed. I then changed it to v10 beta53 (same slots again), and now WiiFlow doesn’t get any further than the loading screen where the covers are animated behind the logo. Is there a different revision I should be using for the latest version?

Guide I used: https://wii.guide/cios.html

**Comment by gingerbeardman** [comment]
Did you upgrade all WiiFlow files that are included in the zip when moving to the latest version? Specifically the bins folder should not be skipped.

**Comment by Hallowizer** [comment]
Not sure, I just got it from the Open Shop Channel. Should I pull out the wiiflow folder and let wiiflow generate a new one?

**Comment by gingerbeardman** [comment]
OK, so use the latest version from this repo release page: https://github.com/Fledge68/WiiFlow_Lite/releases

for CIOS see here https://github.com/Fledge68/WiiFlow_Lite/issues/1#issuecomment-485188388
