### ISSUE TITLE
[BUG] Progress bar percentage report seems off?

### ISSUE THREAD

**Issue by gingerbeardman** [Fledge68/WiiFlow_Lite#23]
Look at this, taken during "download all" with zero existing cover images:

![img_4056](https://user-images.githubusercontent.com/49612/48635343-c9e42e80-e9bf-11e8-93bd-9fa4189a40b2.jpg)

![img_4057](https://user-images.githubusercontent.com/49612/48635351-cf417900-e9bf-11e8-9e8b-4f3f1a5160c0.jpg)

**Comment by Fledge68** [comment]
so did it download all of the covers or were some missing?
i can see a mistake in the code that doesn't count for the covers that didn't download.

**Comment by gingerbeardman** [comment]
Some were indeed missing.

In fact, regardless of how many times I did this it never got them all. I did it on my computer instead

**Comment by gingerbeardman** [comment]
also applies to "converting covers" process on first launch (or empty cache)

**Comment by gingerbeardman** [comment]
converting covers seems to get to 50% when all covers are converted and then races to 100% after the process is finished?
