### ISSUE TITLE
[REQ] More Supported Audio Formats

### ISSUE THREAD

**Issue by Emerald-Fox** [Fledge68/WiiFlow_Lite#230]
From what I can find on the Wiki and online, WiiFlow only supports MP3 and OGG for background music, could more formats such as WAV, FLAC, M4A, etc. be added?  If there's already more than just MP3 and OGG support, could you possibly update the Wiki and/or WiiFlow's help screen to have a list of supported audio formats?

**Comment by gingerbeardman** [comment]
See:
https://github.com/Fledge68/WiiFlow_Lite/blob/f9f23f9048640f1519aa01d8763500e914b4657d/source/music/SoundHandler.cpp#L29-L33
