### ISSUE TITLE
[REQ] Unlocked Cover Colors

### ISSUE THREAD

**Issue by Emerald-Fox** [Fledge68/WiiFlow_Lite#231]
I've recently found out WiiFlow has a hard limit of only 6 choices of cover colors, could you implement the ability to do any hexadecimal color possible?

**Comment by Fledge68** [comment]
no not possible. the color choices are not actually a color. the color choices tell wiiflow which dvdskin color image to use. these skins are used to draw the part of the dvd case that snaps together. look in the  out/imgs folder for 

dvdskin.png
dvdskin_black.png
dvdskin_greenone.png
dvdskin_greentwo.png
dvdskin_red.png
dvdskin_yellow.png

these were created for wii game covers
dvdskin_clear.png was recently added for cd jewel case covers.

**Comment by Emerald-Fox** [comment]
Ah I didn't know that, is there a way to add more though manually?

**Comment by Hakaisha** [comment]
I just recolor/edit the dvdskin texture in GIMP, then use the modified texture to replace a dvdskin I don't use.  Greenone and Greentwo are my usual swap outs for custom dvdskins.

dvdskin_greenone.png serves as a good base to use for colorizing, being neither too dark or too light. Just be sure to convert it to RGB first, as it is currently an Indexed image that only utilizes a small palette of green colors to keep the file size smaller. 

Quick GIMP instructions:
- Once the image is opened, select 'Image' on the top tab, then scroll down to select 'RGB'
- To change the color, select 'Colors', scroll down to 'Colorize', then skew the Hue, Saturation and Lightness values to your liking

If you want to go into further detail, I have written out a diagram of how the dvdskin texture behaves and wraps around the case in WiiFlow. It is what I used in finalizing some details in the clear skin. You may find it useful in customizing the dvdskin to look how you want:
![wfl-dvdskin-diagram](https://user-images.githubusercontent.com/39748198/101304199-52330780-3805-11eb-987b-355093234c32.png)
