### ISSUE TITLE
version 5.4.8 wiiflow lite + priiloader v.9 = no autoload wiiflow.

### ISSUE THREAD

**Issue by wiirdo** [Fledge68/WiiFlow_Lite#234]
Hey community, I have installed the cios mod cIOS d2x v10 beta52,  installled bootmii/priiloader v.9. Trying to set priiloader to load wiiiflow 5.4.8 on boot. Wont do it. Will load/autoload usbloadergx from Priiloader. Wiiflow starts/runs fine from homebrew channel. Would like to use wiiflow as primary os environment. Thanks in advance!

**Comment by Fledge68** [comment]
install a wiiflow forwarder channel if you haven't already.
then download this - https://www.mediafire.com/file/tj13pbiab8whsgq/Priiloader-Forwader-Loader-DWFA.dol/file
put it on the root of your SD card and set priiloader to launch it.

**Comment by wiirdo** [comment]
Much appreciated! Thx!
