### ISSUE TITLE
[REQ] Include GC2Wiimote 

### ISSUE THREAD

**Issue by Invictaz** [Fledge68/WiiFlow_Lite#235]
We cannot use a Gamecube controller on various Wii and Gamecube games now on the WiiU as the WUP-028 OEM adapter only works in several games. I hope you can include GC2Wiimote which emulates a Wiimote and allows us to do that. BBloader for Wii already has GC2Wiimote but that does not work on Wiiu.

https://bitbuilt.net/forums/index.php?threads/gc2wiimote-beta.2945/
https://gbatemp.net/threads/wiimote-emulation-through-gamecube-controller.520194/

**Comment by Fledge68** [comment]
not possible on wii and wii u vwii. once a wii game is launched it is controlled by the cIOS and nintendont controls the GC games. wiiflow stops working once the game is launched.

plus it appears to me the only reason BBloader can use GC2Wiimote is because its integrated into Hiidra which is basically a new version of neek2o which the guy says is a wii kernal.

funny thing is I never heard of BBloader, GC2Wiimote, and Hiidra.

**Comment by Invictaz** [comment]
It "is" now running on Wii, so why do you say it's not possible on Wii?
As for WiiU, can a new Wii kernel be loaded?

**Comment by Fledge68** [comment]
Hiidra runs on the wii and BBloader is a special loader to run on Hiidra.

I suppose wiiflow could be made to run on hiidra too but that would take a lot of work and time. but free time is very short for me now.

**Comment by Fledge68** [comment]
so here's what i see with BBloader.

the download includes apps/bbloader and apps/nintendont (which i'm not sure if they are allowed to include nintendont in their download).
also in the root:/bbloader folder is a hiidra folder with bins and elfs similar to neek2o (sneek/uneek).

the installer in the apps/bbloader folder is a dol that basically makes sure your wii has all the proper up to date IOS installed and may even patch them (similar to pimp-my-wii). plus it installs priiloader and sets it to autoboot bbloader on wii startup. hopefully they made their own version of priiloader.

BBloader is designed to use hiidra (probably dip.elf) to launch wii games. which hiidra has gc2wiimote integrated in it. gc games are launched via nintendont which has its own way of using the gc controller.

hiidra is similar to neek2o but apparently doesn't use/need a emunand. it somehow still uses the system nand. which makes me wonder if hiidra is more of a special cios that doesn't need to be installed.

the trick would be to get wiiflow to launch games via hiidra. i can't find any hiidra source code. what args would i send to hiidra?

but again there's the lack of time right now.

**Comment by Fledge68** [comment]
further more. GC2Wiimote requires a GC controller to be plugged in a GC port which the wii u does not have. the wii u vwii will require a cios patched/coded to get input from a USB HID device such as the WUP-028 OEM adapter. I know nothing about coding a cios.
