### ISSUE TITLE
Duplicate games in coverflow

### ISSUE THREAD

**Issue by diesse** [Fledge68/WiiFlow_Lite#236]
Hi, I installed latest version of WiiFlow Lite and worked flawlessly, with both wii and gc games loaded from 128gb SDXC internal SD.
Suddenly, the last game in coverflow appears three times and some games do not appear at all, even if the reported game count is correct.
I tried to clean 'wiiflow save' from NAND, delete and recreate from scratch both SD:/wiiflow and SD:/apps/wiiflow folders but the problem persists.
Even deleting the duplicate game from SD:/wbfs, another game became duplicated three times.
WiiFlow file explorer correctly shows all games (even the missing ones), and the SD filesystem check (from windows) reported no errors.

**Comment by Fledge68** [comment]
this is all very odd. no one else has any problem like this.

are you sure you don't have favorites ON or some sort of Category ON?

**Comment by diesse** [comment]
No, favourites and categories are both disabled.
I see some posts in reddit reporting similar issues, but without responses or solutions.
Is deleting SD:apps/wiiflow and SD:/wiiflow enough to clean all data, or do i need to do something more to perform a fresh install?

**Comment by Fledge68** [comment]
thats it unless you have the wiiflow folders on USB also.

**Comment by diesse** [comment]
I re-checked games with Wii Backup Manager and found that two wbfs got corrupted.
This caused the duplicate games issue, recreating the wbfs solved the problem.
Thanks for your support!
