### ISSUE TITLE
wiiflow 5.4.8  stuck on "Wiiflow" logo

### ISSUE THREAD

**Issue by DiameterEffect** [Fledge68/WiiFlow_Lite#237]
is there any fix to this? I tried to downgrade to 5.4.7 and still doesn't work. Is there a fix to this?

Im using a 4.3 USA wii and I have a RVL-036 Black wii remote with motion plus inside.

**Comment by gingerbeardman** [comment]
Please confirm your setup and list details here.

We need to confirm there is a problem before there can be a fix.

**Comment by Fledge68** [comment]
yes wii need a lot more info.

wiiflow logo - is that that image or the animated image?
are you using SD, USB, or both?
is wiiflow installed on SD or USB?
are you using a USB flash/pen drive or a USB HDD?
are you on wii or wii u?
how are you launching wiiflow? via hbc? or via forwarder channel installed on system menu?
after you answer these we will probably have more questions or need a syscheck.

**Comment by DiameterEffect** [comment]
> yes 'wii' need a lot more info.
> 
> wiiflow logo - is that that image or the animated image?
> are you using SD, USB, or both?
> is wiiflow installed on SD or USB?
> are you using a USB flash/pen drive or a USB HDD?
> are you on wii or wii u?
> how are you launching wiiflow? via hbc? or via forwarder channel installed on system menu?
> after you answer these we will probably have more questions or need a syscheck.

I'm using a Wii, Wii flow is installed on the SD card, I'm using my USB stick and SD card to play my games, I'm launching homebrew from the forwarder I tried launching homebrew in the prii loader settings but it still does the same thing. Let me address my issue more, the Wii flow logo is jus there there's no animated logo or anything its just a still logo, not loading or doing anything. I installed the homebrew channel VIA  the internet method, I'm not so sure since it was a while ago.

**Comment by gingerbeardman** [comment]
Can you describe how you installed WFL? 
Where did you get the files? 
How did you put them on your SD - what files did you put where?

**Comment by DiameterEffect** [comment]
> * Does your modded Wii meet the requirements for WFL (the installed IOS versions)?
> * Can you describe how you installed WFL?
> * Where did you get the files?
> * How did you put the WFL files on your SD - what files did you put where?
What are the requirements for WFL?
I got the files from this github and extract it using winrar, after it was done extracting I went in the clicked apps and wii flow is there, currently in C:\Users\name\Desktop\wiiflow_v5.4.7\apps, copied wii flow onto my SD card and put  it into my apps folder.

**Comment by gingerbeardman** [comment]
what CIOS do you have installed on your Wii?

you can do a syscheck and paste a link to it here.

**Comment by DiameterEffect** [comment]
> what CIOSes do you have installed on your Wii?
> 
> you can do a syscheck and paste a link to it here.

currently dont have my wii with me sorry, i'll reply back here when I have it with me

**Comment by DiameterEffect** [comment]
> what CIOSes do you have installed on your Wii?
> 
> you can do a syscheck and paste a link to it here.

alright heres the syscheck

SysCheck HDE v2.4.0 HacksDen Edition by JoostinOnline, Double_A, R2-D2199, and Nano
...runs on IOS58 (rev 6176).

Region: NTSC-U
System Menu 4.3U (v513)
Priiloader installed
Drive date: 12.07.2010
Homebrew Channel 1.1.2 running on IOS58

Hollywood v0x21
Console ID: 170928809
Console Type: Wii
Shop Channel Country: United States (49)
Boot2 v4
Found 99 titles.
Found 48 IOS on this console. 15 of them are stubs.

IOS3 (rev 65280): Stub
IOS4 (rev 65280): Stub
IOS9 (rev 1034): No Patches
IOS10 (rev 768): Stub
IOS11 (rev 256): Stub
IOS12 (rev 526): No Patches
IOS13 (rev 1032): No Patches
IOS14 (rev 1032): No Patches
IOS15 (rev 1032): No Patches
IOS16 (rev 512): Stub
IOS17 (rev 1032): No Patches
IOS20 (rev 256): Stub
IOS21 (rev 1039): No Patches
IOS22 (rev 1294): No Patches
IOS28 (rev 1807): No Patches
IOS30 (rev 2816): Stub
IOS31 (rev 3608): No Patches
IOS33 (rev 3608): No Patches
IOS34 (rev 3608): No Patches
IOS35 (rev 3608): No Patches
IOS36 (rev 3608): No Patches
IOS37 (rev 5663): No Patches
IOS38 (rev 4124): No Patches
IOS40 (rev 3072): Stub
IOS41 (rev 3607): No Patches
IOS43 (rev 3607): No Patches
IOS45 (rev 3607): No Patches
IOS46 (rev 3607): No Patches
IOS48 (rev 4124): No Patches
IOS50 (rev 5120): Stub
IOS51 (rev 4864): Stub
IOS52 (rev 5888): Stub
IOS53 (rev 5663): No Patches
IOS55 (rev 5663): No Patches
IOS56 (rev 5662): No Patches
IOS57 (rev 5919): No Patches
IOS58 (rev 6176): USB 2.0
IOS60 (rev 6400): Stub
IOS61 (rev 5662): No Patches
IOS62 (rev 6430): No Patches
IOS70 (rev 6912): Stub
IOS80 (rev 6944): No Patches
IOS222 (rev 65280): Stub
IOS223 (rev 65280): Stub
IOS249[57] (rev 65535, Info: d2x-v10beta52): Trucha Bug, NAND Access, USB 2.0
IOS250[56] (rev 65535, Info: d2x-v10beta52): Trucha Bug, NAND Access, USB 2.0
IOS251[58] (rev 65535, Info: d2x-v10beta52): Trucha Bug, NAND Access, USB 2.0
IOS254 (rev 65281): BootMii
BC v6
MIOS v10
Report generated on 01/16/2021.

**Comment by gingerbeardman** [comment]
Next try is debug log:
> so when you use your sd card you can set wiiflow to output a debug log to sd.
> 
> open wiiflow_lite.ini in a text editor (notepad++) and under [DEBUG] set sd_write_log=yes and save. run wiiflow and try to launch a wii game with emunand gamesave. exit wiiflow if you need to. now on the root of the sd card should be a file named wiiflow.log
> 
> copy and paste it here

**Comment by DiameterEffect** [comment]
> Next try is debug log:
> 
> > so when you use your sd card you can set wiiflow to output a debug log to sd.
> > open wiiflow_lite.ini in a text editor (eg. notepad++) and under [DEBUG] set sd_write_log=yes and save. run wiiflow and try to launch. exit wiiflow if you need to. now on the root of the sd card should be a file named wiiflow.log
> > copy and paste it here

I'm in C:\Users\name\Desktop\wiiflow_v5.4.8\apps\wiiflow and I dont see no wiiflow_lite.ini

and i donwloaded the 5.4.8 zip file too, and check the other folder and dont see a ini file.

**Comment by gingerbeardman** [comment]
You should be looking on your SD card, the ini is created by WFL.

**Comment by DiameterEffect** [comment]
I just checked the SD card and dont see a ini file. Only ini file i see is for priiloader and bootmii.

**Comment by DiameterEffect** [comment]
Okay it just started working now, I have zero clue what I did but it just started working all of a sudden, it got pass the animated wii flow logo and now i can see the games on my SD card, but theres one issue. Whenever I select USB and go try and play a game on there it just shows the 3d wii cover and freezes, any solution? or should i create a new issue since this isnt related to the wii flow logo anymore.

**Comment by gingerbeardman** [comment]
please create a new issue

**Comment by DiameterEffect** [comment]
Alright closing
