### ISSUE TITLE
Wiiflow 5.4.8 freezes when selecting a wii game

### ISSUE THREAD

**Issue by DiameterEffect** [Fledge68/WiiFlow_Lite#238]
Whenever I select USB and go try and play a game on there it just shows the 3d wii cover and freezes, any solution? 

I have a RVL-036 Black wii remote with motion plus inside.
I am using a 4.3U wii
I got my Wii flow  installed on the SD card, I'm using my USB stick and SD card to play my games, I'm launching homebrew from the forwarder.

**Comment by gingerbeardman** [comment]
lots more questions about your USB:

- which port is it plugged into on your Wii?
- how is it formatted?
- does it work with any other launchers?

probably more

**Comment by DiameterEffect** [comment]
1. the bottom one
2. NTFS(that might be the problem?)
3. Yes it does work with other launchers such as CFG.

**Comment by macomarivas** [comment]
Hi, it freezes when the game file (wbfs) is read only (NTFS partition, 32K cluster size). Works fine with CFG.

**Comment by DiameterEffect** [comment]
> Hi, it freezes when the game file (wbfs) is marked has **read only** (NTFS partition, 32K cluster size). Works fine with CFG.

Ah yes, then I should format my hdd to fat32 then

**Comment by DiameterEffect** [comment]
> Whenever I select USB and go try and play a game on there it just shows the 3d wii cover and freezes, any solution?
> 
> I have a RVL-036 Black wii remote with motion plus inside.
> I am using a 4.3U wii
> I got my Wii flow installed on the SD card, I'm using my USB stick and SD card to play my games, I'm launching homebrew from the forwarder.
well i just ended up using the [enhanced version of usb loader gx](https://gbatemp.net/attachments/usbloadergx_r1272_mod_v4-7z.240235/), since my original intention for wii flow was to use cheats, but it seems like usb loader gx works like a charm.
