### ISSUE TITLE
[BUG] hard crashes when using default folder name for game RZ8JG9

### ISSUE THREAD

**Issue by gingerbeardman** [Fledge68/WiiFlow_Lite#24]
https://www.gametdb.com/Wii/RZ8JG9

**This folder name causes hard crash**
`Simple 2000 Series Wii Vol. 1: The Table Game [RZ8JG9]`

> It's the type of hard crash that does not end in a reload to get back to WFL.

**Workaround**
If I rename the folder to `The Table Game [RZ8JG9]` then the game will launch OK.

**Comment by Fledge68** [comment]
possibly because of the colon ':'
or maybe the name is too many characters long. i'll look into it when i find time.

**Comment by gingerbeardman** [comment]
I think you've got it, too long. I remember seeing it truncated somewhere on screen (though maybe not in WFL)

**Comment by Fledge68** [comment]
the file path is probably set to 64.
so the filename plus usb:/wbfs/+54+length of filename
yep that would be too long.
right now i'm trying to figure out the best way to stop the bg music thread while downloading covers.

**Comment by Fledge68** [comment]
well i just check and all filepath's are set to 1024 chars
and titles are 64 chars
try putting the ':' and/or '.' back in but keep the title of the folder short 
try  naming it Vol. 1: The Table Game [RZ9JG9]

**Comment by gingerbeardman** [comment]
So I cannot use WiiXplorer to rename the folder to include the `:`

But renaming to `Vol. 1 - The Table Game [RZ8JG9]` causes the crash, so I think it's the period character?

**Comment by Fledge68** [comment]
thanks for checking. not sure what to do about it yet. for now i suggest not including periods or colons in folder names.
to be certain you could just add random periods to other folders and see if those games crash too.

**Comment by gingerbeardman** [comment]
I can confirm adding a period in any game folder name will result in this crash.

**Comment by gingerbeardman** [comment]
However, I have another game with a period and that works fine?

- `MX vs. ATV: Untamed [RMXE78]` = OK

**Comment by Fledge68** [comment]
strange indeed.

**Comment by Fledge68** [comment]
hey Matt, do you know if this issue still happens?

**Comment by gingerbeardman** [comment]
Will check it out soon

**Comment by gingerbeardman** [comment]
Just tried `Conduit 2.0 [SC2E8P]` folder name and it no longer crashes.
