### ISSUE TITLE
Cryptic docs

### ISSUE THREAD

**Issue by mabushey** [Fledge68/WiiFlow_Lite#240]
> Put it in apps/wiiflow and use wiiflow forwarder's to launch it via the wii system menu.

What is "it?" The /data directory? The entire git repo? 
What is a `wiiflow forwarder`? I currently am using WiiFlow 4.2.1, it came as a zip archive with a dir structure of `/apps/wiiflow/` with no `wiiflow forwarder`. Unzip to the SDcard root and it works...

**Comment by gingerbeardman** [comment]
You should be downloading the latest release, not the GitHub source repo.
https://github.com/Fledge68/WiiFlow_Lite/releases/tag/5.4.8

Then everything will make sense.

> forwarders can be found on wiiflowiki4. 
quick google: https://sites.google.com/site/wiiflowiki4/
