### ISSUE TITLE
return to WiiFLow Lite after exiting a game

### ISSUE THREAD

**Issue by ctny** [Fledge68/WiiFlow_Lite#242]
Running WiiFlow Lite on vWii in Wii U... In settings page 4/14, "Exit To" has 3 options -- "System Menu", "HBC", "Wii U Menu". Can you add an "Exit to WiiFlow Menu" option, so when leaving a game, users don't need to launch WiiFlow Lite again?

**Comment by ctny** [comment]
Ah, I figured it out... 
1. install wiiflow channel installer v1.1
2. in WiiFlow Lite, set "Exit to = system menu" and "return to channel = WiiFlow", both gather... I was just looking at "Exit to"

**Comment by gingerbeardman** [comment]
Well done.

Please close this issue if you've resolved it.
