### ISSUE TITLE
[BUG] Loader stalls when exiting back from emunand title

### ISSUE THREAD

**Issue by Emerald-Fox** [Fledge68/WiiFlow_Lite#243]
WFL 5.4.9 beta 1 consistently hard stalls (can't exit without hard shutting down the system) when returning to the loader after exiting from a title installed on an emunand. note: I'm exiting to the real nand to load back into WFL.
WFL loads fine when the system is rebooted and also when loading into WFL after playing a title installed on the real nand (though sometimes I do still get stalls from that, but it's way less common than when exiting from an emunand title)

**Comment by gingerbeardman** [comment]
can you provide a log?

https://github.com/Fledge68/WiiFlow_Lite/issues/196#issuecomment-703176522
