### ISSUE TITLE
Unable to launch House of the Dead 2 & 3 Return

### ISSUE THREAD

**Issue by user020** [Fledge68/WiiFlow_Lite#245]
Launching House of the Dead 2 & 3 Return on vWii with WFL 5.4.8 and default game settings (IOS Auto, Video mode Default etc) displays the WiiFlow logo momentarily but the white progress bar on black screen doesn't appear. The vWii then reboots to the home menu without any errors. Other games launch without any issues. Any ideas what might be causing this and/or what settings I need to change?

**Comment by gingerbeardman** [comment]
Could you try to get a log?

**Comment by user020** [comment]
Sure, here you go:

[wiiflow.log](https://github.com/Fledge68/WiiFlow_Lite/files/6034387/wiiflow.log)

**Comment by user020** [comment]
Tried a different copy of the game, now working.
