### ISSUE TITLE
Wii flow

### ISSUE THREAD

**Issue by mujaid** [Fledge68/WiiFlow_Lite#246]
@Fledge68 when are you going ti release a new update of wiiflow_lite?

**Comment by KcrPL** [comment]
This should be closed and marked as invalid. Issues should only be used to... report issues.

**Comment by Fledge68** [comment]
hopefully some time this month.  but if you can't wait select 'Actions' above and choose the top workflow. then look on bottom of page for artifacts and download wiiflow_lite. and yes KcrPL is right -- next time ask this on gbatemp not here.
