### ISSUE TITLE
Kiki Trick (ID ST3J01) crashes my WiiFlow Lite on vWii

### ISSUE THREAD

**Issue by Phil1023** [Fledge68/WiiFlow_Lite#249]
Hi,
I'm trying to get the game Kiki Trick to work (ID ST3J01) on WiiFlow Lite. I have a WiiU so I'm in the vWii. I have no issues with other games (even other Japanese games).

The game is recognized, I can see the preview screen and sound. Then after selecting play, I see the progress bar (white on black) and then the WiiU crashes.

I have attached a log file with 3 entries: 
[wiiflow.log](https://github.com/Fledge68/WiiFlow_Lite/files/6095749/wiiflow.log)

The first is starting of another game in Japanese Chibi-Robo! (ID R24J01). It plays fine.

The second is Kiki Trick, but there was the following error ("Error: IOS_OPEN(/shared2/menu/FaceLib/RFL_DB.dat, 1) -106"), and google told me, that it had something to do with the Mii. I did not have one created at the time. The screen just stays blank.

The third entry is with a Mii created beforehand. Now the WiiU still crashes, but I get the following screen (in Japanese).
![IMG_9254_exp](https://user-images.githubusercontent.com/71966500/110215045-f893b500-7ea7-11eb-97b2-29998920ca42.jpg)
It translates to "An error has occurred, press the eject button remove the disc and turn of the power to the console."

I've got the game working on Dolphin on PC with the same image file, but obviously I'd like to play it on the intended hardware :)

Thanks for your help in advance!

**Comment by gingerbeardman** [comment]
Have you checked your dump MD5 checksum to prove it's a good dump? 

Have you tried from a different SD card or HDD?

**Comment by Phil1023** [comment]
Is there an official list of the MD5 checksums I can check it against?

I'll try it with another HDD soon and report back.

**Comment by gingerbeardman** [comment]
Most Wii drive manager Windows apps offers checking hash/validity.

**Comment by Phil1023** [comment]
Sorry for the late reply. It seems that the image I had was indeed corrupted.
Interestingly it ran on Dolphin though (with the same checksum). I didn't check with a Windows App, but created a new image that I tested successfully.
Thanks for the help!
