### ISSUE TITLE
Genesis Plus GX and NintendontMMMod

### ISSUE THREAD

**Issue by Edu789** [Fledge68/WiiFlow_Lite#254]
The latest versions of Genesis Plus GX (commits 269b0e8) and NintendontMMMod (v6.492) do not work as a Wiiflow Lite plugin ...
Genesis Plus Gx gives the following dsi error when starting the game:
https://github.com/Edu789/Edu/blob/ee2f876433d73d0c642c336abb069dc52027927d/20210314_210933.jpg
I talked to the dev's Genesis Plus Gx and he said the problem could be Wiiflow ...
https://github.com/ekeeke/Genesis-Plus-GX/issues/357#issuecomment-802835074
Nintendont works normally through Usb Loader Gx and Homebrew Channel, but through Wiiflow it hangs on a black screen.
NintendontMMMod is a modified version of the official Nintendont.

**Comment by gingerbeardman** [comment]
- Please check your Wii is modded correctly, maybe mod it again using ModMii
- Provide a SysyCheck

**Comment by Fledge68** [comment]
i seem to recall the latest version of genplus gx does not work as a plugin unless it is on SD and maybe even the games. seems like its mentioned in tetsuo's plugin package thread on gbatemp.

nintendont and any mod of it shouldn't be used as a plugin.

**Comment by Edu789** [comment]
> i seem to recall the latest version of genplus gx does not work as a plugin unless it is on SD and maybe even the games. seems like its mentioned in tetsuo's plugin package thread on gbatemp.
> 
> nintendont and any mod of it shouldn't be used as a plugin.



> i seem to recall the latest version of genplus gx does not work as a plugin unless it is on SD and maybe even the games. seems like its mentioned in tetsuo's plugin package thread on gbatemp.
> 
> nintendont and any mod of it shouldn't be used as a plugin.

The Genesis Plus Gx dev said the problem is not with Wiiflow.
The official version of Nintendont works normally on Wiiflow.

**Comment by Edu789** [comment]
https://github.com/ekeeke/Genesis-Plus-GX/issues/357#issuecomment-811015687

**Comment by Edu789** [comment]
https://github.com/ekeeke/Genesis-Plus-GX/issues/357#issuecomment-811015687

**Comment by Fledge68** [comment]
thank you for informing me of this and helping ekeeke find and fix the problem.
