### ISSUE TITLE
Template for issues would make a big difference

### ISSUE THREAD

**Issue by gingerbeardman** [Fledge68/WiiFlow_Lite#255]
It's a repo option:
- https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

This will allow us to do some initial triage:
- usage requests: prompt to go to GBATemp thread
- bug reports: prompt users to check some things and provide syscheck
- template for bug reports and issues

I'm happy to edit and maintain the templates.

**Comment by gingerbeardman** [comment]
I was happy to delegate.

BTW, I also lack the rights to do this on this repo. 

In other repos I've created two:
1. bug report
2. feature request

But I think here, given there will be little ongoing development of new features, I think just one for bug report will be enough.

What info should the bug report issue ask for? Bare essentials is best. Too much will scare people away.

**Comment by takoyaki99** [comment]
I think the bug report feature is good, as long as people fill it out.
Too many people on the atmosphere (Switch CFW) repository just delete the whole thing and just say what their issue is with little to no information.
I think a bare-minimum report would be good.

Something like (here's just a list of questions I think would help)
```
Wii or vWii?
What revision of Wii (if Wii is owned)
What System Menu?
SD card/USB specs?
What cIOS do you have installed?
What version of WiiFlow do you use?
Can you provide a SysCheck?

```etc etc

**Comment by Fledge68** [comment]
@gingerbeardman what do think of the issues template? do i need change something? or add something? or can we close this issue?

**Comment by gingerbeardman** [comment]
Looks good to me!
