### ISSUE TITLE
Infinite loading when opening wiiflow

### ISSUE THREAD

**Issue by hugozgt** [Fledge68/WiiFlow_Lite#256]
there is a issue exactly like this but its kinda dead so im making a new one. So when i open wiiflow it just loads infinitly. i have tried downloading latest version and 5.4.7 and it did not work either. is there anyone who knows how to fix this?

**Comment by gingerbeardman** [comment]
We need to know about your setup.

Things to check
- WFL is set up correctly
- Wii is modded correctly
- Hard drive is connected correctly

WFL works, so the error is on your side during install/setup.

**Comment by hugozgt** [comment]
> We need to know about your setup.
> 
> Things to check
> 
> * WFL is set up correctly
> * Wii is modded correctly
> * Hard drive is connected correctly
> 
> WFL works, so the error is on your side during install/setup.

i fixed the issue! i just had to factory reset my wii and download homebrew again but now it works thanks for the help

**Comment by hugozgt** [comment]
never mind does not work again

**Comment by Pow3rTow3r** [comment]
I have the same problem and looking for a solution. Wiiflow 5.4.9 beta4 gets stuck at "WiiFlow title screen" and will not load contents from hard drive. Only way to get it to work is to run USB Loader GX first then launch Wiiflow. I am running a 5.5.5 WiiU modified with CBHC and a modified vWii per the instructions on wiiu.hacks.guide. I have my Wii and Gamecube games loaded onto a FAT32 2TB HDD with a y-cable.

**Comment by gingerbeardman** [comment]
Can you confirm the hard drive is formatted with MBR partition scheme? If not, you'll need to convert it.

https://github.com/Fledge68/WiiFlow_Lite/issues/210#issuecomment-718021359

**Comment by Pow3rTow3r** [comment]
How do I verify this? Can I do this within Disc Management? Please forgive my ignorance with this kind of thing. Thank you for your help.

**Comment by gingerbeardman** [comment]
Yes, see here https://www.howtogeek.com/245610/how-to-check-if-a-disk-uses-gpt-or-mbr-and-how-to-convert-between-the-two/

**Comment by Rooklz** [comment]
I'm having the same issue however it only happens when using the Wiiflow forwarder and not from launching from HBC itself. The Wiiflow forwarder works occasionally but half of the time it will just stay stuck at the [Wiiflow logo](https://i.imgur.com/IZkCAnr.png). 

When launched from HBC it loads instantly and works perfectly.

**Comment by Rooklz** [comment]
> 
> 
> I'm having the same issue however it only happens when using the Wiiflow forwarder and not from launching from HBC itself. The Wiiflow forwarder works occasionally but half of the time it will just stay stuck at the [Wiiflow logo](https://i.imgur.com/IZkCAnr.png).
> 
> When launched from HBC it loads instantly and works perfectly.

should have noted my USB drive is FAT32 MBR and is 2TB

**Comment by Rooklz** [comment]
SysCheck HDE v2.4.0 HacksDen Edition by JoostinOnline, Double_A, R2-D2199, and Nano
...runs on IOS58 (rev 6176).

Region: NTSC-U
System Menu 4.3U (v513)
Priiloader installed
Drive date: 02.13.2007
Homebrew Channel 1.1.2 running on IOS58

Hollywood v0x11
Console ID: 105607447
Console Type: Wii
Shop Channel Country: United States (49)
Boot2 v4
Found 69 titles.
Found 47 IOS on this console. 14 of them are stubs.

IOS4 (rev 65280): Stub
IOS9 (rev 1034): No Patches
IOS10 (rev 768): Stub
IOS11 (rev 256): Stub
IOS12 (rev 526): No Patches
IOS13 (rev 1032): No Patches
IOS14 (rev 1032): No Patches
IOS15 (rev 1032): No Patches
IOS16 (rev 512): Stub
IOS17 (rev 1032): No Patches
IOS20 (rev 256): Stub
IOS21 (rev 1039): No Patches
IOS22 (rev 1294): No Patches
IOS28 (rev 1807): No Patches
IOS30 (rev 2816): Stub
IOS31 (rev 3608): Trucha Bug, ES Identify, NAND Access
IOS33 (rev 3608): No Patches
IOS34 (rev 3608): No Patches
IOS35 (rev 3608): No Patches
IOS36 (rev 3608): No Patches
IOS37 (rev 5663): No Patches
IOS38 (rev 4124): No Patches
IOS40 (rev 3072): Stub
IOS41 (rev 3607): No Patches
IOS43 (rev 3607): No Patches
IOS45 (rev 3607): No Patches
IOS46 (rev 3607): No Patches
IOS48 (rev 4124): No Patches
IOS50 (rev 5120): Stub
IOS51 (rev 4864): Stub
IOS52 (rev 5888): Stub
IOS53 (rev 5663): No Patches
IOS55 (rev 5663): No Patches
IOS56 (rev 5662): No Patches
IOS57 (rev 5919): No Patches
IOS58 (rev 6176): USB 2.0
IOS60 (rev 6400): Stub
IOS61 (rev 5662): No Patches
IOS62 (rev 6430): No Patches
IOS70 (rev 6912): Stub
IOS80 (rev 6944): Trucha Bug, NAND Access
IOS222 (rev 65280): Stub
IOS223 (rev 65280): Stub
IOS249[57] (rev 65535, Info: d2x-v10beta52): Trucha Bug, NAND Access, USB 2.0
IOS250[56] (rev 65535, Info: d2x-v10beta52): Trucha Bug, NAND Access, USB 2.0
IOS251[38] (rev 65535, Info: d2x-v10beta52): Trucha Bug, ES Identify, NAND Access
IOS254 (rev 65281): BootMii
BC v6
MIOS v10

here is my syscheck, im using a rvl-001 wii

**Comment by online-stuff** [comment]
I'm having this issue too..

First using a 256GB flash drive, now using a 1TB hard drive..  Yes formatted MBR, as NTFS.

All games were loaded using WiiBackupManager_Build78...  Sometimes it would be fine..  Then I'd add some more games and it would simply stop loading..  It gets stuck (crashes?) on the first splash screen..  My hard drive flashes when there is activity..  It simply stops doing anything.  Wiimote turns off when launching and will not re-connect..  Holding the power button on the Wii will eventually turn it off.

I was using the October 2020 version, updated to the April 2021 version, no change.

Is it possible it has to do with which games are on the storage it is loading?

USBLoaderGX so far seems to work, but WiiFlow_Lite crashes..

Does it save any log files (to the SD card) when starting that can be checked to see what is going on?

**Comment by gingerbeardman** [comment]
Open `wiiflow_lite.ini` in a text editor and under `[DEBUG]` set `sd_write_log=yes` and save.

Run WFL and try to reproduce your problem. Exit WFL or reboot if you need to.

Now on the root of the sd card should be a file named `wiiflow.log` which will show where the problem happened.

**Comment by online-stuff** [comment]
> Now on the root of the sd card should be a file named `wiiflow.log` which will show where the problem happened.
> 
> For it to not work and now work after you used another app is... bizarre?

Awesome.  Exactly what I was looking to find.

Bizarre, I agree, but it is what it is..  Next time it happens, I will not forget this..  I'll try to reproduce it.   Thank you.

**Comment by Pow3rTow3r** [comment]
> Yes, see here https://www.howtogeek.com/245610/how-to-check-if-a-disk-uses-gpt-or-mbr-and-how-to-convert-between-the-two/
> 
> Just check info, do not make any changes.

Sorry for late response, I just checked via Windows Disc Management, my drive is set up as MBR partition. And I forgot to add my drive is a 2TB WD drive formatted as FAT32.

**Comment by gingerbeardman** [comment]
I have a feeling it may be some 2TB limit, will look into it.

**Comment by Pow3rTow3r** [comment]
Any word on this? I'd really love to be able to use WiiFlow on my vWii on WiiU.

**Comment by gingerbeardman** [comment]
It's in the queue waiting for free time.

**Comment by online-stuff** [comment]
> 
> 
> It's in the queue waiting for free time.

So this is a known issue?  Are the logs needed when this happens?  Or has the cause already been found?

Is there a work-around until it is fixed?

**Comment by gingerbeardman** [comment]
Please post your log (see above) if you're suffering from the exact issue.

**Comment by Bastastic** [comment]
2TB is the limit yes, I have the same issue. Could I pay somebody to fix it? I am willing to make a donation to the dev. https://gbatemp.net/threads/vwii-wiiflow-doesnt-work-with-hdd-but-usb-loader-gx-does.589640/

**Comment by Bastastic** [comment]
https://github.com/Fledge68/WiiFlow_Lite/issues/218

Here they think IOS58 should be forced (like in USB Loader GX)

**Comment by gingerbeardman** [comment]
@Bastastic is your drive formatted as MBR? What is exact drove/partition size?

**Comment by Pow3rTow3r** [comment]
Okay, I have left my WiiU alone for awhile out of frustration with WiiFlow crashing and got an email yesterday the issue was closed. Was/has there been any concensus on the issue of WiiFlow Lite 5.4.9 not working? If not, is it possible to install an earlier build that may be more stable on my WiiU?

**Comment by gingerbeardman** [comment]
@Pow3rTow3r use a partition smaller than 2TB on your drive.
