### ISSUE TITLE
Wiiflow not rendering correctly.

### ISSUE THREAD

**Issue by sthetix** [Fledge68/WiiFlow_Lite#257]
https://user-images.githubusercontent.com/22261135/112718323-d203ef80-8f24-11eb-855d-317c4b507397.mp4

Hi, i just tried Wiiflow on the korean wii, and this is what i got. 

It is not rendering correctly. Is it a bug?

I used  Wiiflow 5.4.8

Thanks

**Comment by gingerbeardman** [comment]
I believe you're missing theme files.

Check your installation (file copying).

**Comment by sthetix** [comment]
No it isnt. The theme files are there.

**Comment by gingerbeardman** [comment]
What is the contents of your WFL languages folder and what language do you have it set to in WFL ini file?

**Comment by Fledge68** [comment]
translation_author=DDinghoya

maybe he can help. he authored the korean.ini for the language folder.

**Comment by sthetix** [comment]
Fixed by editing the ini file and set the language to english

**Comment by andot** [comment]
I found all of the korean, chinese and japnese languages can't display correctly. I think the necessary fonts may be missing.
