### ISSUE TITLE
Wii flow cheat issue

### ISSUE THREAD

**Issue by DaGreYBoi** [Fledge68/WiiFlow_Lite#259]
When I download cheats straight from the Wii using Wii flow and I use them return to dreamland  freezes is there something wrong, iam using newest version 5.4.something it has lite  
When I got rid of cheats everything worked fine and it didint` freeze at the same place again help

**Comment by gingerbeardman** [comment]
Maybe the cheat is causing the freeze?

**Comment by DaGreYBoi** [comment]
Thx that helped

**Comment by DaGreYBoi** [comment]
Thx now I can play again
