### ISSUE TITLE
[BUG] Refresh cache does not pick up new games when using plugin view

### ISSUE THREAD

**Issue by gingerbeardman** [Fledge68/WiiFlow_Lite#26]
I noticed this because I added some new games but they were not listed in coverflow. 

- Plugin view
- Refresh cache
= no new games added

- Wii view
- Refresh cache 
= new games found

- GC view
- Refresh cache 
= new games found

**Comment by Fledge68** [comment]
so when you were in plugin view - did you select the plugin for the roms you added?
reload cache for plugin view does not reload every plugin list - just the current one you are viewing.

**Comment by gingerbeardman** [comment]
Yes, if I am understanding you correctly. 

My usual way of running is to tick both Wii and GC plugins so I can see all those games in one list. 

I added two Wii games and then tried refreshing. No dice. 

I had to switch to Wii source and then refresh to get them to appear. 

Thanks for all your hard work on this! ✌️

**Comment by gingerbeardman** [comment]
Verified fix
