### ISSUE TITLE
Custom Private Server URL

### ISSUE THREAD

**Issue by DraconicNEO** [Fledge68/WiiFlow_Lite#261]
I think that We should add an option for a Custom URL for Private servers into Wiiflow lite, similar to what is present in the [latest version of USBLoaderGX](https://github.com/wiidev/usbloadergx). Basically an option where you have a Private server option called 'custom' and below there would be a field you can put the custom URL into. This would allow people to connect to servers other than Wiimmfi without requiring reconfiguration of DNS settings, which is good if we're targeting vWii users.

I am aware that there was an Issue a while back regarding having a NoSSL feature for allowing private servers via DNS #217

**Comment by gingerbeardman** [comment]
As with #217 could you please give us some information as to how this feature may be used? Which Custom URLs? Why is it good for vWii users?

This will enable us to gauge the work involved and also to test the feature.

**Comment by DraconicNEO** [comment]
> As with #217 could you please give us some information as to how this feature may be used? Which Custom URLs? Why is it good for vWii users?
> 
> This will enable us to gauge demand, estimate the work involved, and also to test the feature.

Custom URLs like Altwfc.net or newwfc.xyz but Also a Field for custom URLs as in [Enter the URL into this Field] That way as new different servers come out people can use these without you having to update them and/or people can add their own **private** server (servers that aren't publicly available) URL

**Comment by Fledge68** [comment]
unfortunately wiiflow never has had a onscreen keyboard to type things like this. currently with the NoSSL feature you can pre patch your game to use a different URL of your choice.

the best i could do is add the choice for CUSTOM and you would have to manually add the custom url to wiiflow_lite.ini. or manually change wiiflow_lite.ini if you need to change to another URL.

**Comment by gingerbeardman** [comment]
FWIW I use WiiXplorer file manager to edit my `wiiflow_lite.ini` file on device.

**Comment by DraconicNEO** [comment]
> unfortunately wiiflow never has had a onscreen keyboard to type things like this. currently with the NoSSL feature you can pre patch your game to use a different URL of your choice.
> 
Directly patching the game takes away the whole purpose of even having the URL patcher built in, because if you patch the game URLs you can also apply a NoSSL patch

> the best i could do is add the choice for CUSTOM and you would have to manually add the custom url to wiiflow_lite.ini. or manually change wiiflow_lite.ini if you need to change to another URL.

That was what I was thinking, possibly multiple custom server slots that way you could add multiple and select between them depending on which ones you want to use. 

They absolutely should be user-defined though since preset URLs may become obsolete if domain names change.

**Comment by DraconicNEO** [comment]
> FWIW I use [WiiXplorer](https://wiibrew.org/wiki/WiiXplorer) file manager to edit my `wiiflow_lite.ini` file on Wii without need for a PC/etc.

That never even occured to me that you can do that. I would've thought that you'd need a PC or Android Phone to do it.

I suggested this because a custom server string is still easy to change than using the DNS settings since those can't be swapped quickly, especially on a Wii U (No access to settings from vWii.

**Comment by Fledge68** [comment]
hey are you still around? i have a test build for you to try.

**Comment by DraconicNEO** [comment]
> 
> 
> hey are you still around? i have a test build for you to try.

Sorry I missed your reply I've been a bit busy with life lately. Glad to see that you added more servers to the list of Private servers. Although I feel like it still needs an option to input a String like what USBLoaderGX has, that way if a new server came out the app wouldn't need to constantly be re-updated to add more and more servers. But I'm not complaining you still did a good job.

**Comment by Fledge68** [comment]
the app doesn't need to be re-updated. you just need to modify wiiflow_lite.ini with a text editor (notepad++) and add or delete servers. just edit this part:

[CUSTOM_SERVERS]
servers=AltWFC|NewWFC
AltWFC_url=zwei.moe
NewWFC_url=newwfc.xyz

the servers are separated by '|'.
use the server name before '_url='

**Comment by DraconicNEO** [comment]
> 
> 
> @DraconicNEO the app doesn't need to be re-updated. you just need to modify wiiflow_lite.ini with a text editor (notepad++) and add or delete servers. just edit this part:
> 
> [CUSTOM_SERVERS] servers=AltWFC|NewWFC AltWFC_url=zwei.moe NewWFC_url=newwfc.xyz
> 
> the servers are separated by '|'. use the server name before '_url='

Oh that's very handy. Maybe even better than USBLoaderGX's Private server System.
