### ISSUE TITLE
RVZ support?  Maybe at least on vWii?

### ISSUE THREAD

**Issue by NintendoManiac64** [Fledge68/WiiFlow_Lite#264]
RVZ is a new lossless format by the Dolphin devs, and I'm wondering just how possible would it be to have support for it?

Relevant blog post: https://dolphin-emu.org/blog/2020/07/05/dolphin-progress-report-may-and-june-2020/

Now unlike scrubbed ISOs, it actually needs a bit of extra CPU to actually decompress, so for all I know support may only be practical on vWii if it also takes advantage of the Wii U's extra CPU grunt and/or cores (I recall early Wii U homebrew attempts unlocking all three cores in Wii mode running at 729MHz).

But according to the Dolphin devs, the real bottleneck is likely memory.

Relevant Dolphin forum discussion: https://forums.dolphin-emu.org/Thread-dolphin-progress-report?pid=510572#pid510572

**Comment by Fledge68** [comment]
sorry not interested.
