### ISSUE TITLE
Wiiflow gets stuck on logo when launching.

### ISSUE THREAD

**Issue by TheAsdfghjkl** [Fledge68/WiiFlow_Lite#266]
So I recently started using wiiflow to play games on my wii and it worked fine. Eventually however, the USB I was using to load the wbfs files eventually became corrupted. I plugged it into my PC, formated it, and put all the files back exactly where they were. And now for some reason wiiflow refuses to get past the logo when I launch it. Other programs (Wiimod lite, homebrew browser ect.) can mount and read the files on the USB fine, so I don't think it's the USB. All changes to any files on the SD card were only made after wiiflow stopped working so I'm pretty sure that It's not because I screwed something up on the SD card. I am loading wiiflow through the homebrew launcher directly so no issue with forwaders or whatever. Not sure what tp do anymore. Any help would be appreciated.

**Comment by gingerbeardman** [comment]
Can you please provide more details of your USB. 

Size, format type, app used to format it, which port is it plugged into etc.

Did you use fresh files to populate the drive?

Are you sure your USB is not failing?
