### ISSUE TITLE
System Selection directly on the Main Menu

### ISSUE THREAD

**Issue by tim4848** [Fledge68/WiiFlow_Lite#269]
Cycling through Systems, at present on the main menu, my set up lets me click on icons for Wii, Gamecube, Retro (Retro then goes to the Source Menu where I can pick SNES, NES, GB, GBC, GBA).... Is there a way of being able to cycle on the Main Menu as Wii, Gamecube, SNES, NES, GB, GBC, GBA (etc) thus avoiding the use of the Source Menu? I'm guessing you could use the Source Menu to replicate Wiiflow's Main Menu and add the extra Systems and have my set up to Start Source Menu at Start but that's way beyond me.

**Comment by Fledge68** [comment]
what you say is the main menu is actually the first tier of the source menu. clicking retro takes you to a second tier of the source menu. what you need to do is edit the main tier of the source menu to include the second tier and remove the retro button. but you have to edit source menu tiers manually with a text editor and I don't have time to go into great detail how to do that. sorry. ask tetsuo  shima on gbatemp. if he feels up to it.

**Comment by tim4848** [comment]
Thanks for the prompt response. It sounds like you've confirmed that the MAIN MENU is not able to be configured to add extra systems at that same level but this could be achieved by replicating the MAIN MENU in a USER created SOURCE MENU and then adding the extra systems. As a side note, I'm running everything exclusively on an SD card, so the USB icon representing Wii Games is counter-intuitive but I suppose I could easily overwrite the USB icon with a Wii icon. Great software by the way, have only just started using it properly and can see it has a great deal of potential, thanks for your work

**Comment by Fledge68** [comment]
I just realized what you are saying in the original first question. You are not using the source menu at all. you are using the buttons on Main Menu. you through me off when you said you clicked the Retro button and it takes you to the Source Menu. I'm old school and have always called the Retro button the Plugin Button which takes you to the Plugin Select Menu not the Source Menu.

so to answer your original question - no you can not add snes, nes, etc... to the Main Menu buttons.  That is why most of users use the Source Menu instead.

**Comment by tim4848** [comment]
Thanks again for replying. I'll endeavour to get my head round the Source Menu then. Apologies for misinterpreting the PLUGINS icon. I'm not sure I've used GITHUB in the manner it is intended. If you can, please delete this thread. Keep up the good work
