### ISSUE TITLE
Exception (DSI) Occured

### ISSUE THREAD

**Issue by willem6956** [Fledge68/WiiFlow_Lite#270]
WiiFlow Lite crashes before I can press play when loading Mario Galaxy 1 (both PAL and NTSC version crash) and Mario Galaxy 2 (PAL version works, NTSC version doesn't). I verified the md5 hashes from all four ISO's (games).

Exception (DSI) occurred!
GPR00 807495E8 GPR08 9E80FAB0 GPR16 80B206C4 GPR24 80A597FC
GPR01 80B20338 GPR09 1F5ABEC0 GPR17 80A40000 GPR25 00000000
GPR02 809F539C GPR10 90B84F9C GPR18 80980000 GPR26 00000005
GPR03 80A5D380 GPR11 000000FF GPR19 80B2067C GPR27 00000000
GPR04 00000003 GPR12 24222244 GPR20 80B20664 GPR28 90B84F9C
GPR05 00000000 GPR13 80A4C0A0 GPR21 80A40000 GPR29 80A5D380
GPR06 00000000 GPR14 8097E8D0 GPR22 00000000 GPR30 00000003
GPR07 43300000 GPR15 80B206DC GPR23 80A597FC GPR31 0000039C
LR 807495E8 SRR0 80748cec SRR1 0000b032 MSR 00001000
DAR 1F5ABECC DSISR 04000000

STACK DUMP:
80748cec --> 807495e8 --> 807e6d98 --> 807ad66c -->
807a3f94 --> 8071b1e4 --> 8071a5f4 --> 808a64f8 -->
808a645c

CODE DUMP:
80748cec: 8109000C 2F880000 419E041C 2B860001
80748cfc: 8BC9001F 3B89000C 6BDE0001 419E0438
80748d0c: 2E060000 41920458 2B860002 409E0064

[sysCheck.txt](https://github.com/Fledge68/WiiFlow_Lite/files/6910949/sysCheck.txt)

[IOSsyscheck.log](https://github.com/Fledge68/WiiFlow_Lite/files/6910943/IOSsyscheck.log)

Thanks for you help in advance!

**Comment by gingerbeardman** [comment]
I play Galaxy 1 (PAL) through WFL no problem, so I would confirm your media is good and not dying if your dumps verify correctly. Basically, try another USB/SD.

**Comment by Fledge68** [comment]
very odd. do you see the cover and the banner of the game playing? at what point is wfl crashing? if its just those 2 games i think you have a bad dump of those games. try getting a better or different dump of those games. I'm thinking wiiflow is crashing when loading the banner which might be corrupt.
