### ISSUE TITLE
Black screen with 480p_fix on (emunand)

### ISSUE THREAD

**Issue by TevesLeandro** [Fledge68/WiiFlow_Lite#271]
Games loading normally in 480p fix option off
When turn it on, screen goes black.

Turn off again and everything works.

**Comment by gingerbeardman** [comment]
Please provide sysinfo

**Comment by TevesLeandro** [comment]
[sysCheck.csv.txt](https://github.com/Fledge68/WiiFlow_Lite/files/6950224/sysCheck.csv.txt)

My setup:
Clean nand 4.3u formated and updated on system menu config.
priiloader 0.9.1 installed with autoboot homebrew channel.
wfl 5.4.9 (9350f51c)
nand emulation: full
nand created from dolphin bootmii backup
wads installed with showmiiwads 1.5.2
emunand with all usa-vc and some usa-wiiware/dlc on sdcard sandisk ultra sdhc class 10.
all working with usbloader_gx mod7 with 480p patch fix on.
nand verification pass on dolphin without error.
obs: games wbfs / gc iso on external hdd 1tb hitachi fat32 not affected by this bug.

**Comment by Fledge68** [comment]
from the commit:

- added 480p pixel patch as option for nand wiiware/vc games. seems to only work if apploader is set to ON. loading via main dol is broke for the time being.

**Comment by TevesLeandro** [comment]
Ok, thanks for answer
