### ISSUE TITLE
Deflicker control setting for Wii games like is present in blackb0x's latest USB Loader GX fork "Enhanced Edition"?

### ISSUE THREAD

**Issue by NintendoManiac64** [Fledge68/WiiFlow_Lite#273]
"Added deflicker filter options (the safe option is recommended)":
https://gbatemp.net/threads/usb-loader-gx.149922/page-1316#post-8856063

Information on the difference between "safe" and "extended":
https://gbatemp.net/threads/usb-loader-gx.149922/page-1374#post-9552316

**Comment by Fledge68** [comment]
this is planned in the next coming weeks. blackb0x will be adding it to wiiflow just as soon as he gets his next version of usb loader gx done provided he doesn't have any health issues.
