### ISSUE TITLE
scummvm plugin does not return to wiiflow

### ISSUE THREAD

**Issue by eku** [Fledge68/WiiFlow_Lite#276]
I have installed the hidden channel for wiiflow. All plugins but scummvm return to wiiflow. scummvm returns to system menu, which looks like the stub failed and the Wii does a soft reboot.

Do you need any more information to investigate the issue?

**Comment by Fledge68** [comment]
if you launch that version of scummvm via the HBC does it return to the HBC or system menu. i'm thinking this is an issue of the version of scummvm that you are using.

**Comment by eku** [comment]
Good point! It's indeed because of the version I'm using.

https://buildbot.scummvm.org/snapshots/master/wii-master-latest.tar.xz

Do you think they broke something or does it take a custom version to return to the calling program.

Can you give me some tips on how to formulate an issue againt [ScummVM](https://github.com/scummvm/scummvm) so that my request is understood and the issue can be corrected?

**Comment by eku** [comment]
We will se, how they act on [this](https://bugs.scummvm.org/ticket/12882#ticket).

Just in case they won't revert the commit, do you think WiiFlow Lite could patch this out in memory before launching ScummVM?

**Comment by Fledge68** [comment]
my understanding of patching is to put the dol in memory and then search from beginning to end of that memory for a specific pattern of bytes. if found replace them with new ones. but i have no idea how to know what those bytes are. is scummvm tricky to compile?

**Comment by Fledge68** [comment]
i see you had a conversation with the guy who made the change but it ended like 2 weeks ago. are you still communicating with him?

**Comment by Wiimpathy** [comment]
Here's the toolchain he used to compile : https://github.com/AReim1982/binaries/tree/master/Toolchains

Regarding the black screen when exiting, I suspect the newlib in recent DevkitPPC.
I don't think [scummvm mod18](https://gbatemp.net/threads/wiiflow-lite.422685/page-99#post-8849029) does that even if the code is also a bit altered.

Here, it may have to do with the getcwd condition in [main.cpp](https://github.com/scummvm/scummvm/blob/master/backends/platform/wii/main.cpp#L213) that fails to interpret wiiflow arguments...
Returning to home menu is not a solution.

See Genesis-Plus-GX similar issue and possible fixes: https://github.com/ekeeke/Genesis-Plus-GX/issues/357#issuecomment-809811217

**Comment by Fledge68** [comment]
thanks wiimpathy for the info. I wonder if i should change wiiflow to remove the 1 or 2 before setting the path for arg. kind of silly anyway since everyone uses usb1 any way.
