### ISSUE TITLE
Could not find any guide on how to replace wiiflow with wiiflow lite

### ISSUE THREAD

**Issue by hanct** [Fledge68/WiiFlow_Lite#281]
Hi,
Is it possible to provide a little guide to explain how to update WiiFlow to WiiFlow_Lite? This is for those people who have already installed WiiFlow, and would like to change to WiiFlow Lite.  Is it as simple as replacing the relevant files? or need to go thru any uninstallation first?

**Comment by gingerbeardman** [comment]
Just replace the files.

Feel free to backup your old `/apps/wiiflow` folder first.

Note that things have changed much between versions so your setup might not persist exactly after the change.

WiiFlowLite (WFL) is much improved so it's recommended the you take a look through the new settings and set things up to your liking.

See: https://github.com/Fledge68/WiiFlow_Lite/blob/master/README.md#installing

Also see the new Rhapsodii theme mentioned in the readme.

**Comment by Fledge68** [comment]
yep basically what he said. :)

rename your apps/wiiflow folder and dev:/wiiflow folder to back them up
and then simply extract the download zip to create new apps/wiiflow and dev:/wiiflow folders.

**Comment by hanct** [comment]
Thanks @gingerbeardman  and @Fledge68 !!  
I have extracted to the apps/wiiflow folder (in my SD card), and replace whatever is originally there. Also download Rhaspodii, and extracted its content to the wiiflow folder. 
I assume no need to do any further installation at the wii side.
