### ISSUE TITLE
[Bug] Writing cheat textfiles that are only intended to be read 

### ISSUE THREAD

**Issue by eku** [Fledge68/WiiFlow_Lite#283]
According to the posting in [gbatemp](https://gbatemp.net/threads/wiiflow-lite.422685/post-9617550), WFL marks cheats as set by changing the original cheat file. The input file should never be approved for writing.

I suggest, analogous to [usbloader_gx](https://github.com/wiidev/usbloadergx), to simply [evaluate the GCT](https://github.com/wiidev/usbloadergx/blob/enhanced/source/cheats/gct.cpp#L221) file to get the information.

The two loaders do not differ so much in the gct.cpp that one could not adopt it with little effort. Perhaps @wiidev  would like to support with a PR.

**Comment by Fledge68** [comment]
the gct file is made correctly and txt file is no longer rewritten. but i discovered that cheats seem to be broken. i tried super mario galaxy and cheats didn't work. the same cheats work on usb loader gx. seems something is broken somewhere.

**Comment by eku** [comment]
May I ask if you also tested cheats on Virtual Console Games in NAND and EmuNAND?
