### ISSUE TITLE
Crash when returning from RetroArch with third party controller attached to wiimote

### ISSUE THREAD

**Issue by eku** [Fledge68/WiiFlow_Lite#286]
**Describe the bug**
I'm using a third party classic pro controller attached to the wiimote while playing classic games in RetroArch. When exiting RetroArch and returning to WFL it chrashes.

**To Reproduce**
1. Start games via RetroArch plugin
2. Attach third party classic pro controller to wiimote
3. Optional play the game
4. Exit RetroArch while leaving the controller attached
5. Crash

**Expected behavior**
WFL loads fine

**Screenshots**
No screenshot.

**Additional context**
WFL might suffer from the same problem as USBLGX.  See [this commit](https://github.com/wiidev/usbloadergx/commit/071022d3aaca1c5411c70ce02125cb5f27135992).

**Comment by Fledge68** [comment]
so are you sure its wiiflow crashing on bootup? or is retroarch crashing on exit?

what about just having the controller connected when you bootup wiiflow for the first time?

as for that USBLGX commit - that fix is included in the new libogc that wiiflow uses so there's no need to precompile libogc.

**Comment by eku** [comment]
Well, I can't reproduce. Don't know how I did. Therefor closing.
