### ISSUE TITLE
after market wii classic controller crashes wiiflow

### ISSUE THREAD

**Issue by CeeBee1980** [Fledge68/WiiFlow_Lite#288]
aftermarket classic controller crashes wiiflow lite. Nintendo branded classic controller works fine.

**To Reproduce**
1. Go to channels and scroll using aftermarket classic controller
2. Crash DSI Exception error 

**What version of WiiFlow Lite**
v5.4.9

On Wii

**Comment by eku** [comment]
I guess you should try a newer version of WFL. See action tab for beta builds.

**Comment by gingerbeardman** [comment]
Conversely, try an older build to see if this has always been a problem.

**Comment by Fledge68** [comment]
i was thinking try a new v5.5.0 beta thats compiled with the latest ppc and libogc as i read there was some controller improvements. so maybe using the latest libogc fixed this isssue.

**Comment by Fledge68** [comment]
v5.4.9 uses libogc 1.8.19
in libogc 2.2.0 there's a fix for 3rd party wii classic controllers
https://github.com/devkitPro/libogc/commit/dc2451fd85f2943738bb106b08e648b645542336
this may be your problem
try wfl v5.5.0 beta 10(i think) - https://www.mediafire.com/file/pic0yhzcke8wll5/wiiflow_lite_62126f6.zip/file

**Comment by CeeBee1980** [comment]
Thank you Just saw and installed 5.5.0 issue is solved.
Thank you for your work and quick reply.
