### ISSUE TITLE
[REQ] shutdown/standby option on WFL home menu?

### ISSUE THREAD

**Issue by gingerbeardman** [Fledge68/WiiFlow_Lite#29]
I use this frequently, but have to jump to another app to shutdown

- Homebrew Channel
- WiiXplorer
- USB Loader GX
- etc

**Comment by dekkit** [comment]
Just to add to this, there are a lot of items in the wii flow lite  'home' button that are probably unnecessary when in kiosk / child lock mode.

Suggest to move any advanced items into the configuration menu (ie for when child lock not activated).  

Something simple like
- Shutdown
- Exit

With both customisable in the configuration menu (ie exit to homebrew channel, system menu, etc. shutdown (full system off vs standby)



 (note: wii flow is great, so thanks for continuing development on it!)
