### ISSUE TITLE
Channels from emunand will not work on 5.5.0 (Dec 8th)

### ISSUE THREAD

**Issue by kikendo** [Fledge68/WiiFlow_Lite#290]
Updated WFL to the latest version and my channels launching stopped working. It was working fine with 5.4.0 and reverting to that version resumed normal operation.
Every time I try to launch a channel, I get the screenshot attached below.

- Wiiflow Lite v5.5.0 December 8th, 2021
- Tested on two Wiis

![image](https://user-images.githubusercontent.com/5854524/147249491-f405be14-d831-473c-93cf-5547dc4ebc6f.png)

**Comment by gingerbeardman** [comment]
> Updated WFL to the latest version

Which files did you update?

**Comment by kikendo** [comment]
All the ones that come in the archive.
The second Wii I tried this on was a fresh install and fresh hack.

**Comment by Fledge68** [comment]
is you emu nand on SD or USB?

are you using full nand emulation or partial?

do you have the CUSTOM or BOOT APPLOADER settings ON/YES?

have you tried RELOAD CACHE?

have tried rename wiiflow_lite.ini to back it up and let wiiflow make a new one?

**Comment by kikendo** [comment]
> is you emu nand on SD or USB?
SD
 
> are you using full nand emulation or partial?
Full NAND. Tried partial too.
 
> do you have the CUSTOM or BOOT APPLOADER settings ON/YES?
Nope.
 
> have you tried RELOAD CACHE?
Yeah.
 
> have tried rename wiiflow_lite.ini to back it up and let wiiflow make a new one?
I have not tried this, will do.

**Comment by Fledge68** [comment]
did you try v5.5.1? there was a small issue with video modes for channels fixed in v5.5.1
