### ISSUE TITLE
Wiiflow hangs when starting up a game

### ISSUE THREAD

**Issue by 3DSUser77** [Fledge68/WiiFlow_Lite#292]
Everytime i start up a game in Wiiflow, it hangs on the Wiiflow loading screen, as seen in the example below.

**To Reproduce**
1. Go to any game that is on your USB drive or SD Card
2. Click on the game
3. Click on the Play Button
4. It shows that its loading, but it never finishes.

**What version of WiiFlow Lite**
v5.5.1

**On Wii or Wii U vWii**
Wii

**Additional context**
I only got it to work ONE time, and that was with Wii Sports and after redownloading the cIOSes. But, after restarting the Wii, even after reinstalling the cIOSes over and over again, it still wouldn’t work.

**Comment by gingerbeardman** [comment]
@3DSUser77 solved?
