### ISSUE TITLE
[BUG] Stuck on SD - GameCube Partition

### ISSUE THREAD

**Issue by antoine2tt** [Fledge68/WiiFlow_Lite#294]
Hello,

I'm using WFL 5.5.1, on a Wii. 

I have almost same issue as : https://github.com/Fledge68/WiiFlow_Lite/issues/8 

But for me, it's only with Gamecube partition. 

I've set it to SD, i want to go back to USB1 (As it is for Wii Game, whick works well) but i can't. I'm stuck on SD. 

I've tried to : 

Reload Cache
Unplug/Plug again USB 
Restart WFL
Restart my Wii 

And nothing change :( 

Thank you for your help.

**Comment by Fledge68** [comment]
so is USB1 Fat32 or NTFS? what port is your usb HDD plugged in?

you could also try path manager in main settings to set the path where your gamecube games are.
