### ISSUE TITLE
WiiSXRX is broken

### ISSUE THREAD

**Issue by qamichele594-2** [Fledge68/WiiFlow_Lite#296]
I have only tested all games so far, but ace combat 3 audio lag and stutters while playing, and worms minor slowdown when the application was in a wii family editon, and when tested in a wii u, the games are made up of repeating loops in every psx game, but the cotm audio lag is gone, I just updated to the latest version of wiiflow

**Comment by qamichele594-2** [comment]
Testing in my Wii family edition Collection i found
Resident evil 2-3, Biohazard (JP) only boot into a blue screen
Driver 2 (Beta) is crappy, and when verificated by the ISO using PCSX-Revolution emulator, everything so plays well but is very slow
Tales of destiny 1&2 crashes during introduction screen
Tonyhawks pro skater 2-3 loops with sound issues and crashing
Need for speed (U+E+J) is REALLY crappy, and when verificated by the ISO using PCSX-Revolution emulator, everything so plays well but is very slow
Tony hawks pro skater 4 not working
Megaman legends 2 (US+EU) crashes the system after capcom screen
Megaman x5, megaman x6 crashes after loading stage
Star wars jedi power battles has some sound issues and random crashing
Destruction derby locks up
Doom (US+EU), and Final doom crashes the system after loading screen
Creatures, tony hawks pro skater crash the system
Ace Combat 2 gives code dump
Alien resurrection (US+EU) crashes immediately, and when verificated by the ISO using PCSX-Revolution emulator, everything so plays well but is very slow
Xenogears crashes the system after saving the memcard
Tales of destiny crashes
Driver 2 (US+EU) seem to trigger some kind of infogrames piracy protection lock out, and when verificated by the ISO using PCSX-Revolution emulator, everything so plays well but is very slow

**Comment by qamichele594-2** [comment]
So any fix this? They all work with duckstation on my PC Windows that has no issues at all with this game works perfectly fine.

**Comment by qamichele594-2** [comment]
When getting all work on PCSX Autobleem emulator after trying to buy a playstation classic console from year 2018, there has been crashing and major looping in both WiiSXRX and PCSX-Revolution emulators, but probably the PCSX-ReARMed libretro3ds core emulator has "prefetch abort (kernel panic)" and "prefetch abort (svcBreak)" and "The card was removed." and "data abort" and "undefined instruction" and "An error has occurred: Couldn't find any FIRM file(s). Press any button to shutdown" and "An error has occurred: Unable to mount CTRNAND or load the CTRNAND FIRM. Please use an external one. Press any button to shutdown" and "An error has occurred: Failed to mount CTRNAND. Press any button to shutdown" and "An error has occurred: Failed to apply 1 FIRM patch(es). Press any button to shutdown" and "An error has occurred: Failed to apply 2 FIRM patch(es). Press any button to shutdown" and "An error has occurred: Failed to apply 3 FIRM patch(es). Press any button to shutdown" and "An error has occurred: Failed to apply 5 FIRM patch(es). Press any button to shutdown" and "An error has occurred: Failed to apply 4 FIRM patch(es). Press any button to shutdown" and "An error has occurred: Failed to apply 6 FIRM patch(es). Press any button to shutdown" and "An error has occurred: Failed to get the CTRNAND FIRM. Press any button to shutdown" and "An error has occurred: Failed to find the CTRNAND FIRM. Press any button to shutdown" and "An error has occurred: Failed to decrypt the CTRNAND FIRM. Press any button to shutdown" and "An error has occurred: Failed to encrypt the CTRNAND FIRM. Press any button to shutdown" and "An error has occurred: Failed to reinsert the CTRNAND FIRM. Press any button to shutdown" and "An error has occurred: The CTRNAND FIRM is corrupted. Press any button to shutdown" and "An error has occurred: Unsupported launcher (argc = 0). Press any button to shutdown" errors and the game still NOT working anymore in newest PCSX-ReARMed libretro3DS core emulator version 1.10.0 on your O2DS console, and probably the ePSXe emulator has "ePSXe.exe has stopped working. A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available." and "Error running ePSXe: SPEC Opcode 1e UNK (PC 00000134) (00000134) (264,45)" and "Error running ePSXe: unknown opcode 00103e44 at 08000345" and "Error running ePSXe: ePSXe (error) recompile block too large (28673)(28672)" and "Error running ePSXe: unknown opcode 00a11235 at 00cda4fe" errors and the game still NOT working anymore again in latest ePSXe release 2.0.5 on my PC Computer, just gives an error:
```
 
 An exception occurred
 
 Processor:       ARM9
 Exception type:  prefetch abort (kernel panic)
 
 R0     00000000       R1     0811FFFF
 R2     00000084       R3     00000000
 R4     080FE8D0       R5     00000FEE
 R6     00800DFE       R7     0000030E
 R8     00000000       R9     00000000
 R10    000036C0       R11    0000000B
 R12    00000008       SP     080EEA0A
 LR     08039455       PC     08075522
 CPSR   60000030
 
 You can find a dump in the following file:
 dumps/arm9/crash_dump_00000012.dmp
 
 Press any button to shutdown
```
And
```
 
 An error occurred (ErrDisp)
 
 Error type:       generic
 
 Process ID:       67115840
 
 Address:          0x00000e1e
 Error code:       0x000000e1
 
 
 Press any button to reboot.
```
And
```
 
 An error occurred (ErrDisp)
 
 Error type:       card removed
 
 The card was removed.
 
 
 Press any button to reboot.
```
And
```
 
 An error has occurred:
 
 Failed to encrypt the CTRNAND FIRM.
 
 Press any button to shutdown
```
And
```
 
 An error has occurred:
 
 Failed to mount CTRNAND.
 
 Press any button to shutdown
```
And
```
 
 An error has occurred:
 
 Unsupported launcher (argc = 0).
 
 Press any button to shutdown
```
And
```
 
 An exception occurred
 
 Processor:       ARM11 (core 0)
 Exception type:  prefetch abort (svcBreak)
 Fault status:    Debug event
 Current process: PCSX ReA (000400000BAC1500)
 
 R0     E0E01BF5       R1     00000000
 R2     0FFFFFE3       R3     00000000
 R4     00001000       R5     00100017
 R6     00023445       R7     000E0000
 R8     0000E000       R9     00AA0E00
 R10    0A00E0F0       R11    0000E000
 R12    00000000       SP     0AEEEFDD
 LR     00130122       PC     0015FE00
 CPSR   A0000010       FPEXC  00000000
 
 You can find a dump in the following file:
 dumps/arm11/crash_dump_00000018.dmp
 
 Press any button to shutdown
```
And
```
A problem has been detected and Windows has been shut down to prevent damage
to your computer.

The problem seems to be caused by the following file: ntoskrnl.exe

CRITICAL_PROCESS_DIED

If this is the first time you've seen this stop error screen,
restart your computer. If this screen appears again, follow
these steps:

Check to make sure any new hardware or software is properly installed.
If this is a new installation, ask your hardware or software manufacturer
for any Windows updates you might need.

If problems continue, disable or remove any newly installed hardware
or software. Disable BIOS memory options such as caching or shadowing.
If you need to use safe mode to remove or disable components, restart
your computer, press F8 to select Advanced Startup Options, and then
select Safe Mode.

Technical Information:

*** STOP: 0x000000f0 (0xfffff78000509518, 0x0000000000000000, 0xfffff90002e64beb, 
0x0000000000000003)

*** ntoskrnl.exe - Address 0xfffff80002e8a5e2 base at 0xfffff80002e07000 DateStamp 
0x55afca65
```
And
`ePSXe.exe has stopped working`
And
`Error running ePSXe: SPEC Opcode 1e UNK (PC 00003456) (00003456) (234,236)`
And
`Error running ePSXe: unknown opcode 00103455 at 039945fe`

**Comment by Fledge68** [comment]
this is a wiisx rx issue. not a wiiflow issue.
