### ISSUE TITLE
Titan Two Freezes App

### ISSUE THREAD

**Issue by erfg12** [Fledge68/WiiFlow_Lite#297]
**Describe the bug**
Plugging in a Titan Two device to simulate a PS3 controller, locks up the application. Unplug it and the application unfreezes. Plugging in a legit PS3 controller works fine. 

**To Reproduce**
1. Plug in a Titan Two out USB cable to the console. 

**What version of WiiFlow Lite**
v5.5.1

**On Wii or Wii U vWii**
Wii U vWii

**Comment by gingerbeardman** [comment]
How does your Titan Two device work with other loaders?

**Comment by Fledge68** [comment]
wiiflow uses libsicksaxis. maybe Titan Two is not compatible with it. maybe you should ask on the libsicksaxis gbatemp thread. maybe xerpi's will reply. otherwise this is not an issue with wiiflow lite.
