### ISSUE TITLE
Issues to boot out of region vc games

### ISSUE THREAD

**Issue by brandbox23** [Fledge68/WiiFlow_Lite#298]
Hi, I am having some issues to boot ntsc vc games on a pal console wii, I tried changing some settings but it just shows a black screen, I have enabled region everything (games, channels) on priiloader, if I launch them from the wii menu they suffer of slowdown due to the default settings of pal consoles, as I've mentioned, I tried launching them from wiiflow, it worked at the beginning and it fixed the slowdown, etc. I just wanted to change some settings and now it doesn't work again, also is it normal that some times when I want to exit to the wii menu or hb channel gets stucked on a black screen??

**Comment by gingerbeardman** [comment]
Which games?

**Comment by brandbox23** [comment]
@gingerbeardman I've used just this one, anyway I was trying to play some n64 vc games but I'm still getting a black screen, I'll try with the loader you've mentioned, I can't find it to download though

**Comment by gingerbeardman** [comment]
Here it is http://www.mediafire.com/file/dv9n94d9wyc5hj6/mighty_channels_v11_1_by_marc.zip/file

**Comment by gingerbeardman** [comment]
This is good news!

If you could let us know what VC game we can look into why this might be.

**Comment by brandbox23** [comment]
The games I tried was mario tennis 64, smash 64, and SM64, all of them are ntsc ver. I do hope there's a correct setting to that, also, I have everything updated about the app, but sometimes I can't exit to the wii menu or hb channel, it gets stucked on a black screen and I have to force the shutdown, idk why this happens

**Comment by Fledge68** [comment]
any new news on this?

**Comment by gingerbeardman** [comment]
Assuming the VC games are USA I can try one of the above tonight.

**Comment by Fledge68** [comment]
if you have a pal console then yes please do.

**Comment by gingerbeardman** [comment]
Yes I do, and I will do so tonight

**Comment by Fledge68** [comment]
any luck?

**Comment by brandbox23** [comment]
@Fledge68 sorry that I didn't responded anymore, I will try as well again to see if I have any luck

**Comment by gingerbeardman** [comment]
Ran out of time last night, but have everything ready to go tonight.

**Comment by gingerbeardman** [comment]
OK so I have a PAL Wii and just installed Mario Tennis N64 (NTSC) into real nand. 

It worked just fine from WFL and also from Wii menu. I also have Priiloader region free everything/games/channels enabled. 

I run 480p and there didn't seem to be any slowdown? (I've never played this game before though so take that with a pinch of salt.)

Not sure what to suggest. Happy to confirm any of my WFL settings if needed.

**Comment by brandbox23** [comment]
@gingerbeardman mario tennis runs at 30fps, generally pal consoles doesn't have problems with that framerate, for example smash bros does suffer from that, anyway, good to know that wfl works, I'll try with those settings

**Comment by brandbox23** [comment]
@gingerbeardman where did you set thatore specifically?? There just general settings

**Comment by brandbox23** [comment]
@gingerbeardman can you send me a photo if possible please??

**Comment by gingerbeardman** [comment]
What I mean is I didn't charge any wiiflow settings on the particular game. Press it once then choose the cog.

**Comment by gingerbeardman** [comment]
Here's a screen recording of my setup https://youtu.be/WoQm2CeWSFk

**Comment by Fledge68** [comment]
> @gingerbeardman @Fledge68 my issue tho, is that for some reason after I exit settings, it just gives me a black screen, the same thing when I try to exit to the wii menu or hb channel...

when exiting settings or exiting wiiflow back to wii menu or hbc - wiiflow is saving the config files. in your case for some reason that fails. is wiiflow on SD - if so is your sd card write blocked? or your gameconfig2.ini is corrupted - you need to rename and have wiiflow create a new one.

**Comment by brandbox23** [comment]
@gingerbeardman I'll compare tomorrow those settings 👍🏻
Also, I have both channel and app from hb channel of wiiflow, I'll try deleting the gameconfig, but before installing the channel I had already these issues

**Comment by brandbox23** [comment]
@Fledge68 So, I've changed the settings according to the video you @gingerbeardman sent me, it worked, I deleted the config file, but even so I'm still having this black screen issues casually, idk why is this happening on my console, at this point I think I will continue with mighty channels, as that boots normally without problems...
If this is useful, this is my syscheck results
[sysCheck.csv](https://github.com/Fledge68/WiiFlow_Lite/files/8189032/sysCheck.csv)
[IOSsyscheck.log](https://github.com/Fledge68/WiiFlow_Lite/files/8189033/IOSsyscheck.log)
