### ISSUE TITLE
downloading cheats is broken on some games

### ISSUE THREAD

**Issue by CJthisis** [Fledge68/WiiFlow_Lite#299]
When I try to download cheats on Need For Speed Undercover (PAL), it is stuck on "Initializing network..."
But it works on Mario Kart Wii (also PAL)
I tried some googling and figured you are taking the codes from wiigeckocodes.github.io (Please dont go to this website if you have a fear of spiders or bugs)
That website is broken, only a few letters of the lists are working, but idk if this is a permanent thing.
If this turns out to be a permanent error, would it be possible to switch to gamehacking.org as a source of cheats?

**Comment by CJthisis** [comment]
Sorry, I am new to github and accidentally posted the question without the explaination

**Comment by gingerbeardman** [comment]
No worries. Thanks for clarifying!

Cheats are downloaded from this following site, by game ID.

Could you please confirm the Game ID of the version you're using.

https://www.gametdb.com/Wii/RX9P69 (EN, NL)
https://www.gametdb.com/Wii/RX9Y69 (ES, IT)

As you can see there are multiple PAL versions of that game, one has cheats:

https://codes.rc24.xyz/txt.php?txt=RX9P69

The other does not:

https://codes.rc24.xyz/txt.php?txt=RX9Y69

Maybe WFL is getting stuck when there are no cheats?

**Comment by CJthisis** [comment]
After doing some digging, I found out that my version of the game has the Game ID RX9_X_69 (without the underscored obviously), which is not listed on https://www.codes.rc24.xyz
But I found that cheats for this version do exist, on https://www.gamehacking.org
They got detected fine in wiiflow, but they did not manage to work :(
Still, I think it is an issue that wiiflow reports that it is trying to connect to the internet, when in fact cheats for the game do not exist. The solution could be maybe a text box that pops up after a number of failed attempts to load the website.

**Comment by gingerbeardman** [comment]
Agreed, WFL is not dealing with "no cheats" correctly.

Any thoughts @Fledge68 ?

**Comment by Fledge68** [comment]
I know it used to work fine. I'll look into this free time permitting.

**Comment by Fledge68** [comment]
so when it gets stuck on "Initializing network..." does it ever say anything else on screen? can you press 'home' or 'b' button to exit?

**Comment by Fledge68** [comment]
so I tried a game that doesn't have a cheat file and wfl doesn't get stuck on "Initializing network..." 
it finished quickly with the message "Download failed!" which isn't quite correct. 
it should say "No cheat file available to download."
I think the "Download failed!" because technically the url just takes you to a blank webpage rather than returning a error such as 404.

As for  "Initializing network..." that makes me think there's something wrong with your home wifi maybe? are you on a wii u maybe? are you using a proxy?

@wiidev any thoughts on this guys problem. that is if you have the time.

**Comment by Fledge68** [comment]
any response? or can i close this? @gingerbeardman have you tried it? does it freeze on Initializing network?

**Comment by gingerbeardman** [comment]
I will have time to try tomorrow 👍

**Comment by Fledge68** [comment]
just a reminder. :)

**Comment by gingerbeardman** [comment]
Just put the kids to bed and am ready to rock

**Comment by gingerbeardman** [comment]
OK my test results

5.4.9 9350f51c
- game with no cheats
- "download failed!" 100%

5.5.2 (downloaded just now)
- game with no cheats
- "download failed!" 100%

There's no Back button on the failure screen but you can press the B trigger button to go back.

**Comment by Fledge68** [comment]
thank you.  so it works as it should but I should maybe make a few minor adjustments. thank you again.
