### ISSUE TITLE
multiple sources at once?

### ISSUE THREAD

**Issue by octoshrimpy** [Fledge68/WiiFlow_Lite#3]
One thing that bothered me about the original WiiFlow was that I could not see USB sources next to SD sources. If it was possible, the setting was hidden very well. It shouldn't be too hard to iterate through each source on boot, and create a cached list of the available games for a "all games available" view (that includes the disc, too!), since it's already caching the list and we need to refresh cache when files change anyways.

**Comment by Fledge68** [comment]
ok lets see. first off this is possible with wiiflow and wiiflow lite. 
wiiflow uses partitions that can be SD, USB1, USB2, etc...
with wiiflow lite you goto main settings and select partition settings. here you can set the partition for wii games, gc games, and plugins default partition. 
each plugin can have its own partition but you have to edit the plugins ini file and add the line partition=x with x being 0, 1, 2 for the choices above. if that line is not added then the plugin will use the default partition i just mentioned.

once you have your partitions set. now here's how to combine sources.
1. plugin select menu. goto Home Menu then choose select plugins. put a checkmark in all you want to combine together. you can get the extra plugins download from the releases tab of this project. in it is plugins for wii, gc, and nand games so you can combine those with the plugins.
2. source menu - goto source menu and press the home button on your wiimote and a config menu will show. turn on multisource or multiselect. with that on when you go to the source menu now you will click on all the sources you want to use (your choices will have yellow border around them) and click done. all your sources will be combined and shown.
3. source menu multi magic numbers - each source menu button defined in source_menu.ini can have multiple magic numbers separated by a comma, example - magic=DEFD1001, FFFFCA10, BA981200 .
so you can make a source menu button that combines 2 or more plugins.

**Comment by danylopez123** [comment]
I know this was from an older version and it was from years ago but, is this method still the same for v5.5.2 or it is different?
