### ISSUE TITLE
Enable multiple sources for newer WiiFlow Lite versions?

### ISSUE THREAD

**Issue by danylopez123** [Fledge68/WiiFlow_Lite#300]
Related to https://github.com/Fledge68/WiiFlow_Lite/issues/3 however, it was from years ago and im guessing WiiFlow Lite had many changes and it might not be the same as the related question.

All of my games are from my microSD.

I've finished building my collection of Wii, GameCube and Wiiware games, i wouldn't mind if i had to switch sources to pick what i want, however, it would have been nice if there was a way to enable what sources you want to display without having to switch them.

Is there a way to do this for the new versions of WiiFlow Lite? Or there isn't a way for that yet?

**Comment by Fledge68** [comment]
are you talking about being able to select wii and gamecube together for example? or gamecube and snes?

**Comment by danylopez123** [comment]
> are you talking about being able to select wii and gamecube together for example? or gamecube and snes?

Being able to select Wii, GameCube and Wiiware Together.
For Retro consoles i can just use RetroArch from the Wii U itself.

**Comment by eku** [comment]
> Being able to select Wii, GameCube and Wiiware Together.

Well, well. It is strange that exactly the function that other USB loaders offer is missing. WFL does not show all sources at the same time, ULGX can, but one wishes for the tab view.

We should merge WFL and ULGX :grin:

**Comment by gingerbeardman** [comment]
@eku let's not try degenerate this into "USB loader wars" and spread misinformation.

viewing multiple sources at once is possible, a 10 second google for "wiiflow multiple sources" led me to: https://gbatemp.net/threads/wiiflow-multiple-sources-at-once.362512/

**Comment by danylopez123** [comment]
> @eku let's not try degenerate this into "USB loader wars" and start spreading misinformation. no answer does not mean it's not possible.
> 
> on the contrary, viewing multiple sources at once in WFL is possible, a 10 second google for "wiiflow multiple sources" led me to: https://gbatemp.net/threads/wiiflow-multiple-sources-at-once.362512/
> 
> Even though that information is from 2014 it is still valid and the solution to this issue.

When i saw the "Plugins" part, the recent release of Wiiflow Lite doesn't come with Plugins, even if i press Select Plugins doesn't do anything.
When i saw the "go into the global settings, page 2 startup settings and enable multisource" the Startup Settings doesn't have a second page.

**Comment by Fledge68** [comment]
fyi - sorry i haven't answered. i will try to get to you soon. maybe even later today.

**Comment by Fledge68** [comment]
nevermind. i'll answer now.

download the wf internal plugins pack here - https://github.com/Fledge68/WiiFlow_Lite/releases/download/v5.4.7/wf_internal_plugins.zip

extract to your dev:/wiiflow/plugins folder.

now start wiiflow lite. on the main cover screen press 'HOME' on wiimote to open the HOME MENU. now click on 'SELECT PLUGINS'. in the window that appears you should see five choices. put a checkmark in the ones you want and go back to see your covers.

by the way -  "go into the global settings, page 2 startup settings and enable multisource" is old and wrong. instead of startup settings he meant source menu settings. but that option is no longer there.

**Comment by gingerbeardman** [comment]
@eku I'm sorry. Apologies for my misinformation! I should have checked the info was up to date. 

It's been too long since I activated my plugins and multi source.

**Comment by danylopez123** [comment]
Huh.. i was kind-of unsure if those plugins wasn't supported for the newer versions.
Still, once again, thank you soo much @Fledge68 ! Downloading the plugins pack and enabling the ones i want now they all appear like how i wanted them.

My question it's now solved, closing.
