### ISSUE TITLE
[REQ] Add functionality to select hermes cios base 38 for larger games like Just Dance UP

### ISSUE THREAD

**Issue by TimG119** [Fledge68/WiiFlow_Lite#301]
**Request**
Unable to specifically assign the Hermes cios base 38 for larger games like Just Dance UP.  CFG USB Loader allows selecting 222 -mload and 222 -yal in order for that game to play.

Issue was discussed here on GBATemp.
https://gbatemp.net/threads/wiiflow-lite.422685/page-194#post-9745681

Thank you!

**Comment by Fledge68** [comment]
wfl does use hermes -mload but something must be broke or missing. I will be looking into this free time permitting.

**Comment by TimG119** [comment]
Thank you so much!  Truly appreciated!

**Comment by Fledge68** [comment]
if you have wfl v5.5.2 backup your boot.dol and ext_booter.bin (in the bins folder)  and then replace them with these - https://www.mediafire.com/file/qnfv081crx2d0r0/wfl_hermes_test1.zip/file

try your game with hermes cios. make sure you have selected ios 222 for the game. let me know if it works.

**Comment by TimG119** [comment]
Thank you.  Will try and let you know.

**Comment by TimG119** [comment]
I had a chance to try it out quickly last night.  I mistakenly thought I had v5.5.2 but it was v5.5.1...which I didn't realize until after I swapped the files.  It still worked, though not when I selected iOS 222 but rather when I had 'auto' selected, like I have selected with all the other games.

I'll give it a try with v5.5.2 later tonight when I get a chance.

**Comment by TimG119** [comment]
Quick update:  

I had some time to update to 5.5.2 over lunch, one of the benefits of working from home.  Wiiflow is now functioning as intended.  The game loads if I set it to iOS 222 and also if I use the 'AUTO' setting.

Thank you so much for the quick turn around.  It has simplified things greatly.  I told my kids you had fixed it and they also extend their thanks.

**Comment by Fledge68** [comment]
ok good. really strange that it works with AUTO since that should be a d2x cios. but enjoy!
