### ISSUE TITLE
Latest version of WiiFlow and issues

### ISSUE THREAD

**Issue by 0rionas** [Fledge68/WiiFlow_Lite#302]
First of all, let me congratulate everyone involved on an excellent piece of work. I have been into emulation and old consoles for well over 20 years, and WiiFlow is probably the best frontend I have ever had, both in aesthetics and functionality. I have been following the development since its early days, and whenever the question of which loader to choose popped up, my answer has always been straightforward. So, many many thanks for all those years and experiences.

Now, unfortunately the last versions of WiiFlow seem to be failing to follow the trend of fidelity and trustworthiness. I always keep a spare copy of USB Loader GX just to compare notes between the two, and it seems that year 2022 was not that good for Wiiflow.

Wiiflow 5.5.1 had major issues with keeping the correct times and dates on save games and game operations in general. I dunno what the problem was, but by testing both Wii Fit and Wii Fit Plus, plus a few runs on Wii Sports Resort showed that date and time were off. And not only that, but also the classic prompt to SYNC with the Balance Board had gone missing.

WiiFlow 5.5.2 fixed this. Now the date and time are correct. But now there are problems with the extra controllers. When Ultimate Band comes up, second and third controllers do not work. And not only that, but they lose their sync altogether. I have to exit the game and repeat the whole sync process again just to have them working from the start. The same thing happens with Wii Sports Resort.

I have never had similar problems in the past, everything and I mean everything worked without any glitches. Now I am tinkering with forcing cIOS 249 and playing around with various settings and remotes, always scratching my head as to what can be going wrong.

I will probably start using an older version of WiiFlow, hoping that this will get better during the next months. Please do not take all the above as a complaint or rant, all I am trying to do is aid with troubleshooting and getting WiiFlow better than it already is.

**Comment by gingerbeardman** [comment]
Could you let us know the most recent old version that is free of the problems you describe.

**Comment by Fledge68** [comment]
so i guess this is fixed?
