### ISSUE TITLE
Screen offset changes without pressing A button

### ISSUE THREAD

**Issue by Devnol** [Fledge68/WiiFlow_Lite#303]
**Describe the bug**
Changing the vertical and horizontal offset settings is possible without pressing the A button, making it hard to adjust granularly

**To Reproduce**
1. Go to Settings page 6
2. Hover over the arrow buttons of Horizontal or Vertical offset
3. The offset changes without pressing A multiple times a second, making it difficult to adjust

**What version of WiiFlow Lite**
v5.5.2

**On Wii or Wii U vWii**
Wii (mini)

**Additional Information**
Nunchuck is connected to wiimote but nothing is pressed and the stick is centered correctly.

**Comment by Devnol** [comment]
Weird. Now it stopped doing that and works fine for some reason. I don't even know how that would programmatically occur or why but well I'll leave it here and you can decide whether to close it or investigate further

**Comment by Fledge68** [comment]
sticky button maybe? i don't know. will close for now.
