### ISSUE TITLE
Some text in the menus are not showing

### ISSUE THREAD

**Issue by AmaiKinono** [Fledge68/WiiFlow_Lite#304]
**Describe the bug**
I am using the latest release (5.5.2) on Wii U. HBC is installed using Compat installer. When I click the home or gear icon, some text in the menus are not showing:

![PXL_20220301_233530027](https://user-images.githubusercontent.com/28714352/156199794-ccd60eb4-f3e8-4a71-bb26-6cdd6fb025ba.jpg)

![PXL_20220301_233625059](https://user-images.githubusercontent.com/28714352/156199800-df650f23-8f3e-4218-8b76-fe91e840f75f.jpg)

**To Reproduce**
1. Open Wiiflow through vWii -> Homebrew Channel
2. Click the home or gear icon

**What version of WiiFlow Lite**
v5.5.2

**On Wii or Wii U vWii**
Wii U vWii

**Screenshots**
See above.

**Additional context**
Please let me know if more information is needed.

**Comment by Fledge68** [comment]
don't forget the language files in wiiflow/languages folder. without those everything will default to English except japanese i guess.
