### ISSUE TITLE
Wiiflow gets stuck on logo then kicks back to loader

### ISSUE THREAD

**Issue by AlphaDragon601** [Fledge68/WiiFlow_Lite#306]
I recently homebrewed my wii and went to install wiiflow. I installed cIOS as according to the wii.guide on the subject then installed wiiflow. When I launch the app from the homebrew launcher I see the static image of the logo for a few seconds then get sent back to the launcher. Following the Known Issues page I installed the startup configurator which crashed to a DSI error.
So far I've tried:
- uninstalling and reinstalling wiiflow (both from a downloaded copy and homebrew browser)
- double checked cIOS (installed at IOS249 and IOS251)
here is my syscheck file:
[sysCheck.txt](https://github.com/Fledge68/WiiFlow_Lite/files/8312275/sysCheck.txt)

any thoughts on what the issue could be and how to fix it? I'm fairly new at this.

**Comment by Fledge68** [comment]
why are you using beta53 alt? and why did you skip slot 250? i think you need to go back and read wii.guide better, especially for cios. do not use beta53 alt.

**Comment by AlphaDragon601** [comment]
> why are you using beta53 alt? and why did you skip slot 250? i think you need to go back and read wii.guide better, especially for cios. do not use beta53 alt.

I initially installed cIOS incorrectly, is there a way to remove that install?

**Comment by Fledge68** [comment]
just install the correct ones. they will overwrite your current ones.

you might have to go to your wii's data management to delete the wiiflow save file.

**Comment by AlphaDragon601** [comment]
I had in fact screwed up the install which has been fixed. Wii flow does run now! However specifically the game Kirby Return to Dreamland cuts to black and freezes when I try and press the "main game" button in the menu (it loads through the opening just fine). I deleted my Wii flow and Kirby save data to no avail. More importantly the startup configurer is still crashing with a DSI error.

**Comment by Fledge68** [comment]
1. your syscheck looks good
2. if wiiflow is booting fine then you don't need start configurator. but please tell me how you installed it and how you run it because you should not be getting a DSI error. unless your download is corrupt which then you should re download it.
3. kirby return to dreamland has metafortress anti piracy. it will only run without any patches applied or if you use a gameconfig file for it. more info here - https://gbatemp.net/threads/kirby-return-to-dreamland-metafortress-anti-piracy.601368/

**Comment by mardy** [comment]
I'm having the same issue. I followed the wii.guide to install the cIOS, but I could not install the d2x v10; the newest one was v6 (and I installed that one). Could that be the cause of the problem?

**Comment by yllekz** [comment]
Same issue. Crashes to homebrew launcher. WiiFlow Start Configurator also crashes. How do I clear out all the config files and start anew?

**Comment by mardy** [comment]
> Same issue. Crashes to homebrew launcher. WiiFlow Start Configurator also crashes. How do I clear out all the config files and start anew?

I did fix my issue, but I wish I remember what my problem was... I just remember that it was a silly one, maybe that the SD card was locked to read-only.

**Comment by gingerbeardman** [comment]
Best place for user support is https://gbatemp.net/threads/wiiflow-lite.422685/

**Comment by custrtrs** [comment]
> See: [#330 (comment)](https://github.com/Fledge68/WiiFlow_Lite/issues/330#issuecomment-1356858393)
> 
> But the best place for user support is https://gbatemp.net/threads/wiiflow-lite.422685/

That was for vWii, but I think it works for Normal Wiis too.
