### ISSUE TITLE
GAMECUBE COVERS DO NOT LOAD

### ISSUE THREAD

**Issue by AnettoMan** [Fledge68/WiiFlow_Lite#309]
Games like ultimate spiderman, the legend of zelda the wind waker do not load the covers.
I understand that I could be leaving something aside and if there is a way to force the placement of a gamecube cover, I would appreciate if you could inform me. I have been researching for 3 days.

I already deleted and reloaded the cache and I also did it manually with a script on pc

I put them in: sd: wiiflow/boxcovers

**On Wii or Wii U vWii**
Wii

**Comment by eku** [comment]
This is not a support forum. If you think you found a bug use the bug template.

**Comment by gingerbeardman** [comment]
Also see https://github.com/Fledge68/WiiFlow_Lite/issues/229

TL;DR: download the covers through WFL.

Also, if your game is a bad rip, or patched, covers may not be found.

**Comment by Fledge68** [comment]
haven't heard any more on this so m closing it.
