### ISSUE TITLE
[REQ] better handling of download timeout/retry for cover images that do not exist

### ISSUE THREAD

**Issue by gingerbeardman** [Fledge68/WiiFlow_Lite#31]
Downloading covers

For covers that do not exist WFL spends some time waiting. Is it a timeout? Retries? 

A scan of channels or odd games can take a very long time. 

It would be good if this scenario was handled better?

**Comment by Fledge68** [comment]
when?
downloading?

**Comment by gingerbeardman** [comment]
Oh yes, sorry, when downloading

**Comment by Fledge68** [comment]
i noticed when downloading covers with the commit i just posted. that most times it takes 4 - 10 seconds to download the cover but occaisionally it would seem to pause. i counted 40 to 45 seconds for one download.
i can only assume that it lost connection and had to reconnect or it had to retry the download multiple times for some reason. 
as for covers that don't exist on gametdb.com i'm not sure how to stop it and move on to the next. i'll keep checking the code maybe i'll find something.

**Comment by gingerbeardman** [comment]
I can code so if you want help in certain areas, let me know. I'll get the devkit installed

**Comment by Fledge68** [comment]
by all means, if you know how to code then fork wiiflow lite, fix it, and send a pull request.

and fix/update libpng and pngu. i tried but got several errors. seems that fix94 took libpng and pngu and heavily modified them.
