### ISSUE TITLE
WiiFLow Lite refuses to start up when I change the file path for homebrew apps from SD to USB1.

### ISSUE THREAD

**Issue by codeNameArkangle** [Fledge68/WiiFlow_Lite#313]
**Describe the bug**

**To Reproduce**

1. I start by turning on my Wii which uses PriiLoader to boot into WiiFlow Lite from my SSD which is in FAT32.
2. WiiFlow Starts up.
3. I click on the gear icon then go to page 12 in settings and click on Homebrew settings.
4. I noticed that Homebrew Partition was set to SD, which is weird because all of the other settings are automatically set for USB1 and refuse to let me change them to SD, I don't have an SD card. 
5. I change Homebrew Partition to USB1, the only option it will let me select and won't let me change it back to SD.
6. I clicked B twice to exit settings.
7. WiiFlow automatically takes me to homebrew apps category.
8. I can now run my Homebrew apps from WiiFlow.
9. I run a hombrew app from WiiFlow, in this case DOSBox.
10. I get an DSI error message, which looks like a DOSBox issue.
11. It reloads the screen goes black for about 10 seconds, then I get taken to the hombrew channel, not sure why it didn't load up WiiFlow. 
12. In the hombrew channel I click WiiFLow then load.
13. I see the WiiFlow logo, I wait about 16 seconds before the screen goes black, then I'm immediately taken back to the homebrew channel.

NOTE: This does not happen on other settings.
NOTE2: I notice when I delete the file /apps/wiiflow/wiiflow_lite.ini then plug my SSD back in to my Wii, it works again as usual, except my homebrew apps don't show up from my SSD.

**What version of WiiFlow Lite**
v5.5.3

**On Wii or Wii U vWii**
Wii

**Hardware**
I have a SSD plugged into my Wii that has hombrew apps on it and gamecube games.
I don't have an SD card plugged into it.

Thanks to those who read through this, I hope I provided enough info, and its not something I'm doing wrong which I don't think so. Thanks again.

**Comment by Fledge68** [comment]
what about other apps? do other apps crash or work?

**Comment by Fledge68** [comment]
thanks for pointing out homebrew partition should not default to SD if there is no SD.
