### ISSUE TITLE
4:3 only games always stretched on Wii U

### ISSUE THREAD

**Issue by Bubblegum3390** [Fledge68/WiiFlow_Lite#314]
When playing on a Wii U set to widescreen, 4:3 only games are always stretched. Going to the per game settings and setting "force 4:3" or "force 16:9" does nothing but change which mode is sent to the game to display as. On USB Loader GX, I can set 4:3 only games to force 4:3 and it will disable the "Wii U Widescreen" setting and display the game in 4:3 unstretched. I would like this behavior replicated in Wiiflow Lite so I don't have to change my tv setting to play 4:3 games

**Comment by Fledge68** [comment]
isn't there a wii u widescreen setting on page 6?

**Comment by Bubblegum3390** [comment]
I'm away from my system for several more days, but I believe you're right. However I'm pretty sure that it's not in the per game options. I think it would be beneficial if the force 4:3 per game setting automatically disabled Wii U widescreen. Either that or add Wii U Widescreen as it's own per game setting. Forgive me if I've gotten anything wrong, I wish I could check myself hah.

**Comment by Bubblegum3390** [comment]
I figured it out, you were right about it already being a per game setting. Sorry, should have waited until I could check again myself before opening this.
