### ISSUE TITLE
Error with a game.

### ISSUE THREAD

**Issue by GabriMode** [Fledge68/WiiFlow_Lite#315]
**Describe the bug**
When I want to start Just Dance 2014, the screen stays black. 

**To Reproduce**
1. Start the game "Just Dance 2014"
2. See error

**What version of WiiFlow Lite**
v5.5.3

**On Wii or Wii U vWii**
Wii

**Additional context**
I hope you can fix this bug as soon as possible please.

**Comment by eku** [comment]
I can say for sure that it works.

Please post your syscheck.csv and tell us, which cIOS you use to start this game.

**Comment by gingerbeardman** [comment]
Also worth verifying the checksum/hash of your game to make sure it is a good dump. 

May be easier to redump the game or use a verified good dump.

**Comment by eku** [comment]
@GabriMode any feedback from you would be nice? May we close the issue?
