### ISSUE TITLE
Wiiflow doesnt boot

### ISSUE THREAD

**Issue by sbot50** [Fledge68/WiiFlow_Lite#317]
I installed wiiflow to mh sd card, all my games are on my usb.
I know that the usb isnt the problem since im (trying to) switch from cfg usb loader to wiiflow.
When wiiflow starts it just goes to a black screen and then fades back to the homebrew channel (all homebrew apps are on the sd card)
If you need any more information im happy to provide it :)

**Comment by eku** [comment]
Turn on logging to SD by editing `apps/wiiflow/wiiflow_lite.ini` and setting `sd_write_log=yes`. Start WFL as you described. Turn of your WII and copy the file wiiflow.log from the SD to your PC. Upload the file to this issue.

**Comment by sbot50** [comment]
> Turn on logging to SD by editing `apps/wiiflow/wiiflow_lite.ini` and setting `sd_write_log=yes`. Start WFL as you described. Turn of your WII and copy the file wiiflow.log from the SD to your PC. Attach the file to this issue.

IG theres already a problem, i downloaded the latest release from this github and theres no wiiflow_lite.ini file in the apps/wiiflow folder, neither is it in the root wiiflow folder (i just downloaded it again, and it still doesnt exist...) Am I supposed to get some other files elsewhere?

**Comment by eku** [comment]
This file is created on first run of WFL.

**Comment by sbot50** [comment]
> This file is created on first run of WFL.

It wasnt, i ran the new install just now and checked with wiixplorer, no file is created. Anyways imma just use usb loader gx instead, the only reason i wanted wiiflow is because it looks REALLY good, but i can just install a theme.

**Comment by Fledge68** [comment]
he never got anywhere on boot. no logo and no animated logo. just a black screen and return to HBC.  did you launch it via HBC or a forwarder channel?

**Comment by sbot50** [comment]
> he never got anywhere on boot. no logo and no animated logo. just a black screen and return to HBC. did you launch it via HBC or a forwarder channel?

I did actually, the logo popped up and the what is animated on turorials online logo popped up but not animated. If you want I can send you a video (just not rn it's 00:35)

**Comment by sbot50** [comment]
Got it working by installing it from someone's masterpiece pack. The problem now is that I can't go to wiiflow, not because it doesn't work. It works perfectly fine, it's just that it lacks the option to have every game in 1 menu instead of switching between consoles.

**Comment by Fledge68** [comment]
actually you can have every game in 1 menu.  The easiest way to go to the Home Menu (presss Home on wiimote) and choose the Select Plugins option. there you can check them all or just the ones you want.

Or you can edit the source menu.ini to add a button with the magic= set to all the plugin magic's separated by commas.

**Comment by sbot50** [comment]
> actually you can have every game in 1 menu. The easiest way to go to the Home Menu (presss Home on wiimote) and choose the Select Plugins option. there you can check them all or just the ones you want.
> 
> Or you can edit the source menu.ini to add a button with the magic= set to all the plugin magic's separated by commas.

Omg thank you, this is great.
