### ISSUE TITLE
RiiTag not updating

### ISSUE THREAD

**Issue by MrOrange9-JCT** [Fledge68/WiiFlow_Lite#319]
**Describe the bug**
When I load a game, it doesn't appear on my RiiTag nor does the plays counter update. The .ini file is like the official RiiTag guide says. 

**To Reproduce**
1. Edit the .ini file to RiiTag link and your key
2. Load a game
3. See it doesn't appear on your RiiTag

**What version of WiiFlow Lite**
v5.5.3

**On Wii or Wii U vWii**
Wii

**Additional context**
I've researched the problem and it seems it is aproblem of WiiFlow Lite not auto initializing the network, but I am not sure if this is true.

**Comment by Fledge68** [comment]
i checked with larsenv, he said it should be working fine.
