### ISSUE TITLE
Wii Flow freezes When using file explorer on VWII

### ISSUE THREAD

**Issue by Gigashocks2015** [Fledge68/WiiFlow_Lite#320]
**Bug description**

Whenever I try to load games, switch to gamecube games, or go to file explorer to switch to my usb wii flow freezes. 

**to reproduce**
Open wii flow and try and open a game, switch to gamecube games, or try to change file path.

**Version of Wiiflow Lite**
5.5.3 Latest release

**On Wii or VWII**
VWii

**Additional Info**
Also it will not give a wiiflow_lite.ini file

**Edit**
It seems to work when I do not have the usb plugged in. But games do not load even when the games are on the SD card if the usb is plugged in.

**Comment by eku** [comment]
Please use the bug template.
