### ISSUE TITLE
Refreshing box cover does not respect the file time

### ISSUE THREAD

**Issue by eku** [Fledge68/WiiFlow_Lite#322]
**Describe the bug**
I overwrite a box cover on the SD card with a new version. Then I update the cache of the plug-in. Since a cached cover (WFC) already exists, no new one is generated.

**What version of WiiFlow Lite**
v5.5.3

**On Wii or Wii U vWii**
Wii

**Screenshots**
N/A

**Additional context**
WFL should decide on the basis of the file times whether the cover is newer than the WFC file and, if necessary, create the WFC file again.

Currently, you have to use WiiXplorer to delete the WFC file. Its existence should not be assumed.

**Comment by Fledge68** [comment]
added game setting to refresh/reload the cached cover. commit https://github.com/Fledge68/WiiFlow_Lite/commit/cc9aa985edaa9ad7cf2f25e18dca92b19fc289b3
