### ISSUE TITLE
Wiiflow stuck on loading save data screens 

### ISSUE THREAD

**Issue by Mariopartyplayer7** [Fledge68/WiiFlow_Lite#323]
https://user-images.githubusercontent.com/93081743/194175436-5a18faf7-4455-49cb-aa5c-661364dfcec7.MOV

ive tried loading mario party 9 and its stuck on this load screen and ive also tried redownloading wiiflow lite, d2x cios installer and even switching from 32gb flash drive to 32gb sd both formatted to FAT32 and nothing worked

**Comment by eku** [comment]
Please use the bug report form and supply IOS information.

**Comment by Mariopartyplayer7** [comment]
> Please use the bug report form and supply IOS information.

whats that supposed to mean

**Comment by Mariopartyplayer7** [comment]
![9FE34091-3596-435E-B22C-381A38067312](https://user-images.githubusercontent.com/93081743/194291858-9de7b6bd-5494-4fd4-9836-2ed7db6e2d54.jpeg)
![C0B4A200-985F-4491-912C-A5B9308E681E](https://user-images.githubusercontent.com/93081743/194291865-de953f38-b559-4a30-bf81-f5ef12ea5a5e.jpeg)
![014C2AFD-FAEF-4B26-8456-DE94356AE603](https://user-images.githubusercontent.com/93081743/194291868-4a77ca54-d0df-4d26-be43-7417b9995d59.jpeg)
![49404C49-EB49-4C04-A279-1614D6B4E0AF](https://user-images.githubusercontent.com/93081743/194291869-f921a6ee-9682-47c9-b183-ab7a021d5e71.jpeg)
![1FCC70D1-31E2-461F-B4DE-5170EB4B5CD8](https://user-images.githubusercontent.com/93081743/194291872-1cc4aca6-0238-41ad-9a8b-3faae34d4f24.jpeg)

**Comment by Fledge68** [comment]
issue is not with wiiflow. possible cause cios used, emunand bad, save corrupted, etc..
