### ISSUE TITLE
Super Mario Galaxy 2 not working on wiiflow

### ISSUE THREAD

**Issue by chaogamer** [Fledge68/WiiFlow_Lite#324]
**Describe the bug**
what happens is after it loads the iso for super mario galaxy 2, my wii remote disables, it goes through the safety instructions as normal. after that it get's stuck on a black screen and softlocks.
i tried redumping
i tried changing settings
using different loaders is not an option for me since i don't have a usb and gecko and neogamma disables wii remote for some reason after launch
tried changing iso's
nothing worked
enabling debugger and full emu nand makes the problem worse by giving just a black screen and softlock and nothing else

**To Reproduce**
1.launch super mario galaxy 2 with default settings
2. the bug just happens

**What version of WiiFlow Lite**
V 5.5.2 latest

**On Wii or Wii U vWii**
Vwii

**Additional context**
it is a dump from the eshop version and the iso works fine in dolphin

**Comment by eku** [comment]
I don't remember SMG2 for Wii being sold in the e-shop.

I have a CD of SMG2 and its dump in WBFS format runs flawlessly in WFL. So the error is probably a faulty dump or a wrong cIOS.

**Comment by gingerbeardman** [comment]
Your SysCheck info would be very helpful. https://wiibrew.org/wiki/SysCheck_HacksDen_Edition
This will let us see if you need to install a different cIOS or add some patches to the Wii.

Wondering if the game dump you got (from inside the Switch eShop version?) has been modified in some way? I recommend getting a new dump, r-roms. Feel free to share or confirm the has of your game image to make sure it is a good one. https://www.gametdb.com/Wii/SB4P01

Regarding the remote going dead this happens sometimes for me, with the later types of Wii remotes that have Wii Motion Plus built-in. So, I always use a Wii remote without Wii Motion Plus built in and it never disables.

By the way: WFL and USB Loader GX can both work with only SD card, no need for anything to be connected over USB.

**Comment by eku** [comment]
@chaogamer any feedback? Please close this issue if you solved your problem.

**Comment by chaogamer** [comment]
Problem not solved but yeah figured out it was just a bad dump. I just need to see if there is another way to dump wii titles from the eshop version without nfs2iso2nfs

**Comment by chaogamer** [comment]
> I don't remember SMG2 for Wii being sold in the e-shop.
> 
> I have a CD of SMG2 and its dump in WBFS format runs flawlessly in WFL. So the error is probably a faulty dump or a wrong cIOS.

The eshop sells digital versions of wii games which sees it as virtual console
