### ISSUE TITLE
wiiflow loads on 2gb sd card, not on 128gb cards

### ISSUE THREAD

**Issue by XxTriviumxX** [Fledge68/WiiFlow_Lite#326]
When i use a 2gb sd card, i can load wiiflow and play wii games... When i use a 128gb sd card (both my sandisk and my patriot), i can see the first logo, but not the logo that moves, and then it brings me back to the homebrew channel. another weird thing here is the sd cards work when used with a usb sd card adapter while using the 2gb sd card for wiiflow and homebrew channel. I bought the sandisk just check if the patriot sd card was the problem and seems like it was not a broken sd card case.. Let me know if you need any info/log files. I will gladly share them.

**Comment by eku** [comment]
Would please use the support forum at https://gbatemp.net/threads/wiiflow-lite.422685/ for your issue.

Thanks.

**Comment by Fledge68** [comment]
guess they don't have an issue anymore

**Comment by XxTriviumxX** [comment]
im using a hard drive now, sorry.
