### ISSUE TITLE
Make path to wiitdb.xml configurable

### ISSUE THREAD

**Issue by eku** [Fledge68/WiiFlow_Lite#327]
Various homebrews use the GamesTDB's wiitdb.xml, each a copy.  

```
apps/SaveGame_Manager_GX/wiitdb.xml
apps/usbloader_gx/wiitdb.xml
wiiflow/settings/wiitdb.xml
```

Therefore, it would be nice if each homebrew could make the path to the file configurable so that only one file exists. WFL could make a start. It is sufficient to read the path from apps/wiiflow/wiiflow_lite.ini. You would have to edit the file for lack of GUI support, but that would be fine.

**Comment by Fledge68** [comment]
nice suggestion. shouldn't be hard to add. and i will. but honestly it isn't a very big file and with today's large hard drives and sd cards you really shouldn't have to worry about the free space. 29.6mb x 3 = 90mb (roughly) of a 4gb+ SD card. but it does keep you from having to update/download it for every app. but ill add it to the paths config menu.

**Comment by eku** [comment]
> but ill add it to the paths config menu.

Does it mean that themes have to be adapted? Who's gonna to make this?

**Comment by Fledge68** [comment]
I'll do it.  with my recent theme changing commits it makes it easy to add new options to wiiflow without themes having to be modified,

**Comment by Fledge68** [comment]
done.
