### ISSUE TITLE
Sam And Max Season 1 crashes on black screen when choosing an episode

### ISSUE THREAD

**Issue by homestar92** [Fledge68/WiiFlow_Lite#329]
When choosing an episode in Sam and Max Season 1, the screen goes to black, the Wiimote desyncs, and the system just hangs.

The only other multi-load game I've tried is Metroid Prime Trilogy and that one works. Also, Sam and Max Season 1 works properly in other loaders on the same system, such as CFG USB Loader

**Comment by CJthisis** [comment]
Have you tried re-ripping the game and maybe checked the hash of the game? (You can do that with the Wii Backup Manager on Windows)

**Comment by Fledge68** [comment]
i've never played that game. haven't heard anything about this lately so im closing it.
