### ISSUE TITLE
Bug or feature of coverflow? 

### ISSUE THREAD

**Issue by CJthisis** [Fledge68/WiiFlow_Lite#332]
**Describe the bug**
When clicking on covers in coverflow, the title is instantly displayed as if you would click on the regular disc channel with the disc inserted. This is a problem becaue i cant access cheats or add the game to my favourites and such.

**To Reproduce**
I dont know, I already tried to change a whole bunch of setting and it still did not change.

**What version of WiiFlow Lite**
v5.5.3

**On Wii or Wii U vWii**
Wii

**Screenshots**

**Additional context**

**Comment by gingerbeardman** [comment]
I'm not sure what you mean, it takes two clicks to start a game. After the first click I can point at the game cover to show the options.

Can you give a step-by-step of what you're seeing?

**Comment by CJthisis** [comment]
> I'm not sure what you mean, it takes two clicks to start a game. After the first click I can point at the game cover to show the options.
> 
> 
> 
> Can you give a step-by-step of what you're seeing?

It looks like this:
https://user-images.githubusercontent.com/99442347/210102646-3dd4310f-f556-45e9-b5b3-1cee13f5975c.MOV

**Comment by Fledge68** [comment]
> **Describe the bug**
> When clicking on covers in coverflow, the title is instantly displayed as if you would click on the regular disc channel with the disc inserted. This is a problem becaue i cant access cheats or add the game to my favourites and such.

that is how wiiflow works when using full screen banners. you click on the banner to shrink it so you can access the settings menu. when done you can click on the small banner to go back to full screen banners. 

in other words, settings can only  be accessed when the banner is small in upper right corner. a little inconvenient but you get used to it cause after all most people don't need to constantly keep making changes to the settings.

**Comment by CJthisis** [comment]
> I'm not sure what you mean, it takes two clicks to start a game. After the first click I can point at the game cover to show the options.
> 
> 
> 
> Can you give a step-by-step of what you're seeing?

Welp, it turns out I'm just dumb. I clicked on the full screen banner by accident when trying to start a game and then I could access the settings and such. This issue is now solved, but this should be somewhere in the Readme or something.
