### ISSUE TITLE
WFL 5.5.3 Geko Codes not recognised 

### ISSUE THREAD

**Issue by 900Ninety** [Fledge68/WiiFlow_Lite#333]
I manually put geko files onto the E:\wiiflow\codes\gct file , making sure the gct file is named using the serial  ( for example 'SDVP41.gct')  however after enabling 'Ocorina' then pressing 'Select' on cheat codes ; I get a ' Cheat file for game not found' . This seems to be a reoccurring bug with Wiiflow , is it not?

**Comment by Fledge68** [comment]
after pressing 'SELECT' your are taken to the Cheats Select Menu which looks for a  cheat txt file in wiiflow\codes. when you select cheats the chosen cheats are made into the gct file to be used by the booter.

**Comment by 900Ninety** [comment]
> after pressing 'SELECT' your are taken to the Cheats Select Menu which looks for a cheat txt file in wiiflow\codes. when you select cheats the chosen cheats are made into the gct file to be used by the booter.

When pressing 'select' I simply get a 'Cheat file for game not found' , then an option to download thats it . I suppose there is supposed to be a menu  . This is the case with USB loader but for wiiflow this menu does not show

**Comment by Fledge68** [comment]
you don\t have a txt file so you get the message 'Cheat file for game not found'

**Comment by gingerbeardman** [comment]
The easiest way to get cheats is to download them through WFL.

If you are adding your own cheats they need to be in TXT format at `wiiflow\codes`

**Comment by Fledge68** [comment]
guess he solved it or gave up.
