### ISSUE TITLE
[BUG] Cannot select USB as game partition device

### ISSUE THREAD

**Issue by krisutofu** [Fledge68/WiiFlow_Lite#334]
Concerns the latest version of Wii flow (that was available on Jan 5 in 2023). I have been quite happy with Wii Flow. So two days ago I thought, I'd update my old version with the newest one.

Unfortunately, it would not find the USB device anymore.

I am using PAL Wii 4.3E version. Standard d2x cIOSes for 249 and 250 and all Wad Mod Pack wads installed. I was able to load and play games from the same device previously.

By deleting the entire apps/wiiflow folder and using the apps/wiiflow folder from a fresh download of an older version, the latest of 2020 (basically randomly picked because I remembered it worked back then), it did work again.

This could be a regional problem or maybe a configuration problem. The last time, I had two .ini files (wiiflow.ini and wiiflow_light.ini). At least I think, it didn't make problems earlier.

**Comment by Fledge68** [comment]
did you try going to main settings>startup settings and try changing a few things.
 
1. make sure sd only is off
2. try force cios off
3. try force cios  on and select a cios
4. maybe you need to change the port setting but i doubt it.
