### ISSUE TITLE
Plugin-Buttons: Hide not work anymore

### ISSUE THREAD

**Issue by eku** [Fledge68/WiiFlow_Lite#337]
**Describe the bug**
I recently updated from 5.5.3 to the latest build. I'm using Rapsody Shima theme and had serveral emulator buttons hidden. With the latest build, and probably others as well, hiding of buttons does not work anymore.

**What version of WiiFlow Lite**
2fd07be7a8538679e24f4ed1fc7f35960bf639ad

**On Wii or Wii U vWii**
Wii

**Screenshots**
n/a

**Additional context**
n/a

**Comment by Fledge68** [comment]
ok i see the problem. 

`for(vector<dir_discHdr>::iterator hdr = m_gameList.begin(); hdr != m_gameList.end(); ++hdr)
	{
		if(m_sourceflow && !m_source.getBool(sfmt("button_%i", hdr->settings[0]), "hidden", false))
		{
			CoverFlow.addItem(&(*hdr), 0, 0);// no filtering for sourceflow
			continue;
		}`
if the button IS hidden it will fall thru this if and try to filter as if it were a wii game and eventually just adds it anyway.

quick fix is to add afer this if:
if(msoureflow) continue;

or redo the if into 2 if's. anyway, glad you caught this.

**Comment by Fledge68** [comment]
should be fixed since commit - 2e3a862
