### ISSUE TITLE
commit 2e3a862 - strange behavior of the display value 'Auto'/'AUTO' in the translations

### ISSUE THREAD

**Issue by MayanKoyote** [Fledge68/WiiFlow_Lite#340]
**Describe the bug**
I noticed that commit 2e3a862 added the ability to translate 'Auto' text to other languages (in some places). But something went wrong with that.

**To Reproduce**
1. Go to 'Settings 2/14'
2. Set 'WiiFlow Language' to 'Default'
3. At same page go to 'Startup Settings' and 'Go' it.  
4. At 'Startup Settings' go to 'Force cIOS Revision' and start to cycle through the value options.
5. It will be: AUTO -> 222 -...- 251 -> AUTO -> (and so on), all the same.
6. Return to 'Settings 2/14', Set 'WiiFlow Language' to 'English', return to 'Force cIOS Revision' and start to cycle through the value options.
7. It will be: Auto -> 222 -...- 251 -> AUTO -> 222 -...- 251 -> AUTO -> (and so on). Notice that 'Auto' (as 'GC_Auto=Auto' in english.ini) has come to be written in capital letters - AUTO (as '_t("GC_Auto", L"AUTO")' in source/menu/menu_config_boot.cpp). If you leave it set to 'AUTO', exit the setting and reenter it again, it will change back to 'Auto'. But when scrolling, it will revert to 'AUTO' again.
8. The situation with the Russian language is similar: АВТО -> 222 -...- 251 -> AUTO -> 222 -...- 251 -> AUTO.

**What version of WiiFlow Lite**
commit 2e3a862

**On Wii or Wii U vWii**
Wii

**Comment by Fledge68** [comment]
because i missed changing line #114. thanks for letting me know. i dont get to test these commits very often lately. my son is usually on the switch or his PS5.
