### ISSUE TITLE
commit 2e3a862 - the result of 'Game Save Extractor' remains as a ghost text

### ISSUE THREAD

**Issue by MayanKoyote** [Fledge68/WiiFlow_Lite#341]
**Describe the bug**
The result of 'Game Save Extractor' remains as a ghost text on all the following screens. It certainly wasn't like this before (in the v5.5.3).

**To Reproduce**
1. Go to 'Settings 1/14' -> 'NAND Emulation Settings 2/3' -> 'Extract Game Saves' -> All (or Missing, whatever).
2. Wait for the process to run and for the result to appear, click on 'Back'.
3. See ghost text.

**What version of WiiFlow Lite**
commit 2e3a862

**On Wii or Wii U vWii**
Wii

**Screenshots**
![Mar-09-2023-00h58m54s](https://user-images.githubusercontent.com/43220515/223828184-99626769-e270-4d26-9656-d14a45ac7388.png)
![Mar-09-2023-01h31m24s](https://user-images.githubusercontent.com/43220515/223837117-33098454-c279-4b8e-8ad5-416091ca815e.png)

**Comment by Fledge68** [comment]
obviously needs to be hidden. time for bed now. will have to look into this one later.
