### ISSUE TITLE
List of non-translatable words/strings in the current version.

### ISSUE THREAD

**Issue by MayanKoyote** [Fledge68/WiiFlow_Lite#342]
**Describe the bug**
Thanks for commits 2e3a862 and aceb49c, which added the ability to translate the 'AUTO' value in one of the places where it was not possible before.
But there are still a few places where such non-translatable cases occur.
This is a list (what I've been able to notice) of those words/strings that cannot be translated (there is no possibility):

Value 'AUTO':
1. (Individual Game) Settings, page 1/6 -> IOS
2. (Individual Game) Settings, page 2/6 -> Hook Type

Value 'default' (or 'Default' sometimes):
1. (Global) Settings, page 1/14 -> NAND Emulation Settings, page 1/3 -> Select NAND
2. (Global) Settings, page 1/14 -> NAND Emulation Settings, page 1/3 -> Select Saves NAND
3. (Global) Settings, page 2/14 -> Theme

Also, the translation of the words "Total size: KB (blocks)" is not displayed, it's always in English. Although the translation is present in the translation file.
This is observed for:
1. (Global) Settings, page 1/14 -> NAND Emulation Settings, page 2/3 -> Extract Game Saves -> both 'All' and 'Missing'
2. (Global) Settings, page 1/14 -> NAND Emulation Settings, page 2/3 -> Extract NAND

**What version of WiiFlow Lite**
aceb49c

**On Wii or Wii U vWii**
Wii

**Screenshots**
![image-A1](https://user-images.githubusercontent.com/43220515/225327971-923d9541-b3d2-47c7-9b1b-188b0e97c0fc.png)
![image-A2](https://user-images.githubusercontent.com/43220515/225328035-91b3e97a-bc53-47c6-9506-d1e5f02ee6ce.png)

![image-D1](https://user-images.githubusercontent.com/43220515/225328060-d4af4506-5627-459b-baa7-44d73336a230.png)
![image-D2](https://user-images.githubusercontent.com/43220515/225328077-b185992c-aaf5-4824-a21f-1e7ab324d1a4.png)
![image-D3](https://user-images.githubusercontent.com/43220515/225328093-8bb183c3-29b6-40b1-9c08-3a88ac063cdb.png)

![image-T1](https://user-images.githubusercontent.com/43220515/225339807-d9dfcce4-51ef-4261-b4a4-8da3579cfff4.png)
![image-T2](https://user-images.githubusercontent.com/43220515/225341534-708cb826-5ceb-4dbf-ae51-07d9e180db75.png)

**Comment by Fledge68** [comment]
this is all very strange because the translation code is there the same as it is for all text. i wonder if your russian.ini is corrupted. otherwise i have no idea. maybe certain characters in your language are causing the issue.

**Comment by MayanKoyote** [comment]
> this is all very strange because the translation code is there the same as it is for all text. i wonder if your russian.ini is corrupted. otherwise i have no idea. maybe certain characters in your language are causing the issue.

Does this refer to "Total size: KB (blocks)"? If yes, there is a screenshot of the same thing happening with the Spanish translation.
And I'm pretty sure that the Spanish doesn't use any Cyrillic characters.

**Comment by Fledge68** [comment]
so today i open english.ini and replaced hook type and IOS with some different text and set wiiflow to english text and both of them showed up with the new text. so then i replaced them with your russian text and it showed as well. here are the screenshots.

![Mar-16-2023-10h50m19s](https://user-images.githubusercontent.com/17163249/225673019-be4c0182-d7d1-423f-a62c-43b161d26674.png)
![Mar-16-2023-10h50m15s](https://user-images.githubusercontent.com/17163249/225673047-9dbfbc0e-8105-4afe-a5d5-1a579369897f.png)

**Comment by MayanKoyote** [comment]
Oh, then there was some misunderstanding.
I'm not talking about the name of the setting.
I'm talking about the setting value. That is, I'm talking about the words "AUTO", "default", "Default".
That is, about what the cursor is next to.
The screenshots use the English interface in order to make it clear exactly where it is located.

**Comment by Fledge68** [comment]
the nand defaults are filenames for the folder. i may change them to wf_nand.

let me know if the total size text changed?

**Comment by MayanKoyote** [comment]
Checked d5f0ca6:
- Value 'AUTO' - translation appeared in both cases. Everything looks fine.

- Value 'default' (in NAND section), both - Oh, now I realized that these are the real names of the NAND folders there. I don't know what would be better yet. Perhaps I will add a mention that these are the names of folders in the name of the setting. Although wf_nand probably wouldn't hurt either.

- Value 'default/Default' for Theme - The translation does not appear immediately. When you switch languages, the translation of the word from the previous language is retained. To get the translation in the current language, you need to tap the side arrow. In the case of the Russian language there is also an encoding failure.
The screenshots show the transition from English to Russian and then to Dutch (default -> Default -> По умолчанию -> Standaard):

![TH001](https://user-images.githubusercontent.com/43220515/225929254-25b4a79c-2da1-40fd-a418-eb9db0266fb0.png)
![TH002](https://user-images.githubusercontent.com/43220515/225929274-565de0fd-ea57-4270-800f-57253a757979.png)
![TH003](https://user-images.githubusercontent.com/43220515/225929292-e793426b-dfb2-414b-90b3-0cdaf7162964.png)
![TH004](https://user-images.githubusercontent.com/43220515/225929312-8211597a-0646-412d-aa9e-2ff0585635ca.png)
![TH005](https://user-images.githubusercontent.com/43220515/225929329-38ae3f1c-aa4c-48a1-89ac-6f3c7336f66f.png)
![TH006](https://user-images.githubusercontent.com/43220515/225929346-b6946637-15aa-4a65-bb29-0cdde6628d96.png)

- Total size - same as before, English text:

![TS001](https://user-images.githubusercontent.com/43220515/225927767-405b3267-1242-4658-8c82-0fadaf4fbc65.png)
![TS002](https://user-images.githubusercontent.com/43220515/225927812-1a6fdfb0-73ff-49cb-9486-2b5bcca5837e.png)

**Comment by Fledge68** [comment]
could you check the latest commit? it should fix the "total size text' issue.

**Comment by MayanKoyote** [comment]
Sorry for the delay, been busy migrating system to new drives.

Checked Artifact bd6c188 (with updated translation files).
- Extract Game Saves - both 'All' and 'Missing' are OK.
- Extract NAND - OK.

![Mar-22-2023-23h40m53s](https://user-images.githubusercontent.com/43220515/227006617-2fb8663b-bc61-4e72-b700-88d94ca1cd2a.png)
![Mar-22-2023-23h47m52s](https://user-images.githubusercontent.com/43220515/227006672-949f55d4-2801-4c05-be82-98e0b6b68dc6.png)

Also checked Artifact bd6c188 with 'old' translation files - everything is OK too.

Thank you very much.
