### ISSUE TITLE
WiiFlow doesn't detect external SSD if plugged in at launch

### ISSUE THREAD

**Issue by joseph-marques** [Fledge68/WiiFlow_Lite#346]
**Describe the bug**
When using a Samsung T7 SSD with my Wii, WiiFlow won't recognize the disk as plugged in. However, it works if I instead wait for the WiiFlow logo to appear and then quickly plug in the USB cable. WiiXplorer has no trouble recognizing the disk.

**To Reproduce**
1. Load up a 1tb Samsung T7 SSD with some games.
2. Connect the USB cable to the Wii.
3. Launch WiiFlow through either the homebrew launcher or the channel.
4. No USB drive detected.

Steps to reproduce the workaround:
1. Load up a 1tb Samsung T7 SSD with some games.
2. Launch WiiFlow
3. As soon as the WiiFlow logo appears, connect the USB cable to the Wii
4. USB drive is detected without issue

**What version of WiiFlow Lite**
5.5.3

**On Wii or Wii U vWii**
Wii

**Screenshots**
N/A

**Additional context**
It appears to make no difference whether the drive is formatted with FAT32 or NTFS. No difference based on which USB port is used. USB Loader GX demonstrates the same issue (though it has a countdown showing the drive as not detected).

If the drive is plugged in from the start, the activity light blinks red briefly, which would seem to indicate some sort of USB error. My best guess is that some sort of hard reset of the USB port is needed?

**Comment by joseph-marques** [comment]
Turns out the issue was that the auto-chosen iOS wasn't working, forcing it to a slot with ciOS 58 fixed it.

**Comment by pancakers2001** [comment]
I'm having the same issue with my SSD, same brand as described here, however forcing the iOS does not work for me, but then for some reason when I switch it back to auto iOS it starts working yet none of my games will play. Doing a clean install of wiiflow will fix the games however I still have the same issue with the SSD afterwards.
