### ISSUE TITLE
Wiiflow doesn't recognize sd card to usb adapters

### ISSUE THREAD

**Issue by EpicDoodleboy2** [Fledge68/WiiFlow_Lite#348]
**Describe the bug**
When I use WFL and I put in my sd card to usb adapter in both usb areas it does't regognize it and yes it works it shows the apps on the HB channel.

**To Reproduce**
1. Have a Micro Sd card to usb adapter (IDK about regular sd cards)
2. Plug it in usb port 1 or 0
3. Launch WFL 
4. Doesn't show up with a reload cache

**What version of WiiFlow Lite**
v5.5.3

**On Wii or Wii U vWii**
regular over June 2007 European Wii with bootmii ios

**Screenshots**
![20230415_155713](https://user-images.githubusercontent.com/111697934/232232627-a9ebb251-21a5-43c8-bea3-186765a5f09a.jpg)
![20230415_155737](https://user-images.githubusercontent.com/111697934/232232648-0f159e9d-bace-446e-a6af-70ad434db2d5.jpg)

**Additional context**
It looks it has games but nope thats running from the front SD not the back and I know due to me putting Super Paper Mario on the Back SD.

**Comment by Fledge68** [comment]
a few things to check.

1. have you went into main settings>partition settings and changed the partition to USB1? will it let you?
2. if it doesn't let you then go to main settings>startup settings and make sure sd only is set to off or no. then change wii game partition to USB1
3. while in startup settings you might want to set force ios to yes or on. wiiiflow will reboot of course.

**Comment by EpicDoodleboy2** [comment]
> a few things to check.
> 
> 1. have you went into main settings>partition settings and changed the partition to USB1? will it let you?
> 2. if it doesn't let you then go to main settings>startup settings and make sure sd only is set to off or no. then change wii game partition to USB1
> 3. while in startup settings you might want to set force ios to yes or on. wiiiflow will reboot of course.

1. It would not let me change it 
2 + 3. Tried it on usb 1 and 0 And it still wouldn't let me change the wii game partition to usb.

**Comment by EpicDoodleboy2** [comment]
Ok now when I launch the game it boots me out to the wii menu.

**Comment by EpicDoodleboy2** [comment]
Nvm switched it it workes now
