### ISSUE TITLE
can't install games

### ISSUE THREAD

**Issue by game174master** [Fledge68/WiiFlow_Lite#351]
back then I used to copy Wii discs to my SD card using Wiiflow. now I can't do that. why? and which USB port do I use on a Wii U for USB 0 or 1?

**Comment by MayanKoyote** [comment]
A more appropriate place for such kind of questions would be https://gbatemp.net/threads/wiiflow-lite.422685/

**Comment by game174master** [comment]
okay then,but can you please still answer my question on why the ability to install games from a physical disc was removed?
