### ISSUE TITLE
Super Paper Mario PAL Crashes at the beggining

### ISSUE THREAD

**Issue by EpicDoodleboy2** [Fledge68/WiiFlow_Lite#353]
**Describe the bug**
The Wii crashes when it eeaches Bowsers castle at the beggining of the game.

**To Reproduce**
1. Get your save ready
2. Launch it
3. Wait till it turns black to bowsers castle
4. Music stops and The wii has crashed

**What version of WiiFlow Lite**
v5.4.9

**On Wii or Wii U vWii**
Wii

**Additional context**
It used to work but it doesn't anymore.

**Comment by EpicDoodleboy2** [comment]
> Did this start happening after a WFL update? If so, does it still work with the older version?
> 
> One thing to confirm is that your dump is still good. If you storage media has started to fail that might have corrupted your game file. You can check the hash, or maybe easier just copy on a known good version.

So I didn't know that there was a Wiiflow update so I updated it today once after I saw your comment and That didn't fix it.

My storage Media hasn't been failing on me.

And Idk how to check if my dump is good or bad bu I haven't checked If my Wii save is corrupted or not so Im going to try that and replay back if that did the trick.

**Comment by EpicDoodleboy2** [comment]
> Did this start happening after a WFL update? If so, does it still work with the older version?
> 
> One thing to confirm is that your dump is still good. If you storage media has started to fail that might have corrupted your game file. You can check the hash, or maybe easier just copy on a known good version.

So I redumped my rom and it works! Thx
But the OG Rom worked on dolphin so idk whats going on with that...

**Comment by gingerbeardman** [comment]
Great! Have fun
