### ISSUE TITLE
Game won't load with Ocarina codes enabled without cache reload first

### ISSUE THREAD

**Issue by Kirbeast** [Fledge68/WiiFlow_Lite#354]
**Describe the bug**
I can't get a mod like Project M to load. It just gets stuck on a black screen before the loading bar appears.
The game will load if I reload the cache first. Though I can't just reload it once I have to reload it **_every single time_** in order for the game to load.

- Reload cache button works
- First wiiflow startup reload cache works

**To Reproduce**
1. Have Super Smash Bros. Brawl[RSBE01] on a usb
2. Go to https://projectplusgame.com/download
3. Click on 'Offline / Wii'
4. Extract contents to root of the SD card
5. Set paths in app/wiiflow/wiiflow.ini
```
[GENERAL]
dir_cheat=sd:/Project+
dir_txtcheat=sd:/Project+
```
6. Enable Ocarina cheats
7. Load the game for a second time without reloading the cache

**What version of WiiFlow Lite**
v5.5.3 March 23rd, 2022

**On Wii or Wii U vWii**
Wii

**Comment by Kirbeast** [comment]
Does the issue being closed means it got fixed?

**Comment by peterwoodworth** [comment]
@Fledge68 ^ A response would be much appreciated 🙂

**Comment by Kirbeast** [comment]
This bug was fixed with commit a1f72297e3c8914050e944378bff388b2d759929 
Seems it was fixed with menu_game_boot.cpp removing calls to cache dir.
Thank you! 🤩

**Comment by Kirbeast** [comment]
More information from tests. This bug now only happens from within wiiflow lite if Ocarina and Video patch are enabled together. However with more tests it seems the bug was indeed fixed for auto booting.
