### ISSUE TITLE
Ocarina .gct codes don't work

### ISSUE THREAD

**Issue by game174master** [Fledge68/WiiFlow_Lite#355]
Whenever I try to manually add cheat codes, it says no cheat codes are found.

v5.5.3

Wii U vWii

[https://drive.google.com/file/d/1v2VxP5TDnxjQGaFvUvqSi3Ay824wVRNj/view?usp=drive_link](url)
[https://drive.google.com/file/d/1-SwWTeC0XXMqvKUpym8YkZAHb4nAAqFO/view?usp=drive_link](url)

**Comment by gingerbeardman** [comment]
Does it work when you download the cheat code on the game settings?

Where are you putting the .gct file? \wiiflow\codes\gct ?

**Comment by game174master** [comment]
the gecko codes website was shut down. so that means you can no longer download codes straight to wiiflow or even USB loader GX. and yes I do have the .gct files in \wiiflow\codes\gct

**Comment by gingerbeardman** [comment]
WFL uses https://codes.rc24.xyz (GameHacking.org Codes Mirror) for code downloads, not geek codes.

**Comment by game174master** [comment]
it turns out that you do not need .gct files, you need .txt . then you put .txt in wiiflow\codes
and for some reason Mario Galaxy codes have to be put manually. I am the definition of caveman brain.

**Comment by gingerbeardman** [comment]
Hahaha! No worries, glad you got it sorted. Have fun
