### ISSUE TITLE
Crashes on Loading

### ISSUE THREAD

**Issue by Wire-Firey** [Fledge68/WiiFlow_Lite#359]
**Describe the bug**
Crashs on Loading

**To Reproduce**
1. Go to 'Homebrew Channel'
2. Access to Wii Flow
3. Wait 20 Seconds

**What version of WiiFlow Lite**
Latest

**On Wii or Wii U vWii**
Wii

**Comment by gingerbeardman** [comment]
The app is used by many people daily with no such crash, so it would seem this is a setup problem.

Please describe your setup and how you installed WFL. You can use [SysCheck](https://wii.guide/syscheck.html) or similar.

Structure and layout of the WFL files on your SD card would also be helpful.
