### ISSUE TITLE
[BUG] "Show banner in game settings" option is ignored

### ISSUE THREAD

**Issue by gingerbeardman** [Fledge68/WiiFlow_Lite#36]
banner appears in game settings regardless of the setting for "Show banner in game settings"

5.0.1

I raised this in #13 after it was closed but it seems to have slipped through the net

**Comment by Fledge68** [comment]
ok matt. it will probably work if you exit wiiflow and restart. i missed your reply - i'm sure wiiflow sets a variable to it at launch but chnaging it doesn't change that variable.

**Comment by Fledge68** [comment]
ok just checked - this works perfect for me.

**Comment by gingerbeardman** [comment]
This one still happens in default theme.

I hope there isn't a misunderstanding between us about what this option does? I am assuming it stops the animated banner from appearing in the top right of the game settings screen?

**Comment by Fledge68** [comment]
just to clarify. this is not the mini banner in the upper right corner when you are on the game selected view.
this is when you go to a games' setting menu  and the banner is displayed full screen darkened behind the settings options like game cios, video mode, cheats, etc...

**Comment by gingerbeardman** [comment]
Oh! Then please accept my apologies. Sorry for the confusion. 

I would like to be able to catch off the mini banner in the corner.

**Comment by Fledge68** [comment]
hmmmm . . . maybe a future option.  one problem - no way to switch to full banner if we do. unless we add 'show banner' button.
