### ISSUE TITLE
Game freezes randomly 

### ISSUE THREAD

**Issue by swaggio7** [Fledge68/WiiFlow_Lite#363]
**Describe the bug**
I was just playing Wii Sports + Wii Sports Resort, and just as I was about to load a swordplay match, my game froze. So I tried again, and it worked... for 5 minutes, at least. It froze again in the middle of the match. Not only that, but my Wiimote (Plus) immediately disconnected and did not reconnect to my Wii U. There is no consistency to this, it's all random! I will reply if more of these happen.

**What version of WiiFlow Lite**
5.5.3 Release

**On Wii or Wii U vWii**
vWii with Priiloader installed

**Additional context**
I am using WiiFlow since USBLoaderGX is pretty buggy when Priiloader is installed on a vWii.

**Comment by gingerbeardman** [comment]
Are you playing from SD card or USB HDD?

Please verify that your storage is not failing. Easiest way might be trying some different storage.

**Comment by swaggio7** [comment]
> Are you playing from SD card or USB HDD?

I use my SD Card since it's 128 gigs and can easily store plenty of games. 

> Please verify that your storage is not failing. Easiest way might be trying some different storage.

There is NO way my SD Card is failing. I got it a month ago!

**Comment by swaggio7** [comment]
If I was using my old 64 gig SD Card I got years ago, this would be more plausible.
Now, the SD card I'm using is a 128GB microSDXC SanDisk Ultra Extreme. The old one is the same thing, just it's 64GB in a standard SD form.

**Comment by MayanKoyote** [comment]
> There is NO way my SD Card is failing. I got it a month ago!
For example, a car dash cam (video registrator) can kill an SD card (crappy one, but anyway) in less than 24 hours.
> SanDisk Ultra Extreme
It's both "Ultra" and "Extreme" at same time? Your sure? If yes, then I have bad news for you.

**Comment by swaggio7** [comment]
Ah. Correction: it's Extreme Pro. Got my names wrong

**Comment by swaggio7** [comment]
> > There is NO way my SD Card is failing. I got it a month ago!
> 
> 
> 
> For example, a car dash cam (video registrator) can kill an SD card (crappy one, but anyway) in less than 24 hours.

... I literally don't use the SD card for anything else BUT my Wii U

**Comment by eku** [comment]
Maybe a SysCheck will shed some light? Feel free to paste in here.

https://wii.guide/syscheck.html

Do you have enabled any hacks in PriiLoader?

**Comment by swaggio7** [comment]
[SysCheck.csv](https://github.com/Fledge68/WiiFlow_Lite/files/12600123/SysCheck.csv)

Enabled Hacks:

Block Online Updates
Move Disc Channel
Region Free Everything
Remove Deflicker
System Settings via Options Button
Create message via Calendar Button
Always Enable WC24 for vWii

**Comment by gingerbeardman** [comment]
Please also do a hash check of your game file, to check it is not corrupted (can happen during copy to SD card).

**Comment by swaggio7** [comment]
> Please also do a hash check of your game file, to check it is not corrupted (can happen during copy to SD card).

Ah. I downloaded the WBFS from Vimm (NTSC-U, I think?) and the MD5 does not match... 🫠
