### ISSUE TITLE
wiiflow overwrote contents of source_menu.ini with inputs file?

### ISSUE THREAD

**Issue by kcpants** [Fledge68/WiiFlow_Lite#364]
**Describe the bug**
After launching and closing a gba game the wiiflow source menu vanished. I plugged my sd card into my pc and opened up the `source_menu.ini` file and found that its contents had been overwritten with what appears to be text from an input file. I've included the new contents of the file below for reference:
```
[BUTTON_0]
hidden=no
source=
title=button_0

[GBA.INPUT.DRCU]
axisdownvalue=-48
axisleftaxis=-0
axisleftvalue=-48
axisrightaxis=+0
axisrightvalue=48
axisupvalue=48
keya=15
keyb=14
keydown=8
keyl=5
keyleft=11
keyr=4
keyright=10
keyselect=2
keyup=9

[GBA.INPUT.GCN1]
axisdownaxis=-1
axisdownvalue=-48
axisleftaxis=-0
axisleftvalue=-48
axisrightaxis=+0
axisrightvalue=48
axisupaxis=+1
axisupvalue=48
keya=8
keyb=9
keydown=2
keyl=6
keyleft=0
keyr=5
keyright=1
keyselect=10
keystart=12
keyup=3

[GBA.INPUT.GCN2]
keya=-1
keyb=-1
keydown=-1
keyl=-1
keyleft=-1
keyr=-1
keyright=-1
keyselect=11
keystart=-1
keyup=-1

[GBA.INPUT.WIIC]
axisdownaxis=-1
axisdownvalue=-48
axisleftaxis=-0
axisleftvalue=-48
axisrightaxis=+0
axisrightvalue=48
axisupaxis=+1
axisupvalue=48
keya=20
keyb=22
keydown=30
keyl=29
keyleft=17
keyr=25
keyright=31
keyselect=28
keystart=26
keyup=16

[GBA.INPUT.WIIM]
keya=0
keyb=1
keydown=8
keyl=2
keyleft=11
keyr=3
keyright=10
keyselect=4
keystart=12
keyup=9

[GUI.INPUT.GCN1]
keyback=9
keycancel=4
keydecrease solar brightness=-1
keydown=2
keyfast forward (held)=-1
keyfast forward (toggle)=-1
keyincrease solar brightness=-1
keyleft=0
keymute (toggle)=-1
keyright=1
keyscreen mode=-1
keyselect=8
keytake screenshot=-1
keyup=3

[GUI.INPUT.WIIM]
keyback=1
keycancel=7
keydecrease solar brightness=-1
keydown=8
keyfast forward (held)=-1
keyfast forward (toggle)=-1
keyincrease solar brightness=-1
keyleft=11
keymute (toggle)=-1
keyright=10
keyscreen mode=-1
keyselect=0
keytake screenshot=-1
keyup=9

[PORTS.WII]
autoload=1
autosave=0
filter=0
fpscounter=0
frameskip=0
gba.forcegbp=0
gyrosensitivity=1
interframeblending=0
mute=0
screenmode=1
sgb.bordercrop=0
sgb.borders=1
sgb.model=SGB
showosd=1
stretchheight=0.9
stretchwidth=0.9
usebios=1
videomode=0
```

**To Reproduce**
I triggered this bug by launching a gba game using mgba and then exiting. I'm not sure if it is reproducible.

**What version of WiiFlow Lite**
v5.5.3

**On Wii or Wii U vWii**
This occurred on my Wii (not on Wii U)

I have a backup of `source_menu.ini` so I don't need a fix for this (assuming it doesn't reoccur regularly). Based on the symptoms, it looks like wiiflow is writing data to the wrong file descriptor (perhaps the file descriptor pointing to the `source_menu.ini` file is not being closed properly).

**Comment by eku** [comment]
Under what conditions does this happen?


> I triggered this bug by launching a gba game using mgba and then exiting. I'm not sure if it is reproducible.

Can't reproduce this.

**Comment by kcpants** [comment]
I have also not been able to reproduce it since it occurred. I think this is one of those bugs that would need to be solved by code inspection. If someone was motivated, a good way to start would probably be to figure out where wiiflow writes  `GBA.INPUT.DRCU` etc to a file and work backward to find the file descriptor its writing to then try to find ways that file descriptor may not be pointing to the correct file.

**Comment by eku** [comment]
> I think this is one of those bugs that would need to be solved by code inspection.

I agree with you there. However, as far as I can see in the source code, it is not WFL but mGBA that writes these values.

**Comment by eku** [comment]
> The other strange part about this is that the first block of the overwritten file...
 The only explanation that spontaneously comes to mind would be a corrupt file system. Could you please check this.

**Comment by eku** [comment]
> My `wiiflow.log` file is fairly long

Does it contain where mGBA is called and what arguments are logged?
