### ISSUE TITLE
video mode patching doesn't work

### ISSUE THREAD

**Issue by bibarub** [Fledge68/WiiFlow_Lite#365]
**Describe the bug**
video mode patching doesn't work. the game still uses its desired video mode

**To Reproduce**
1. set "video mode" to "progressive"
2. set "patch video modes" to "all"
3. launch the game
4. see that it's still using 480i

**What version of WiiFlow Lite**
v5.5.4
v5.5.3

**On Wii or Wii U vWii**
Wii

**Screenshots**
not applicable

**Additional context**
tested games: MadWorld (NTSC), Spy Fox in "Dry Cereal" (NTSC)
both games can be patched fine in usb loader gx

**Comment by bibarub** [comment]
last functional in version 5.4.4.

**Comment by bibarub** [comment]
that commit must be the culprit(?)
https://github.com/Fledge68/WiiFlow_Lite/commit/6e580a7dbd6a3a4dd697beb881d334ca1010d52b

**Comment by Fledge68** [comment]
makes sense. this was actually added by @wiidev   blackb0x the current dev of usblgx.  maybe he'll respond. if not i'll contact him on gbatemp.

**Comment by bibarub** [comment]
there was no bug in the first place.

i was trying to use the "Patch video modes" option set to "More" **along** with "Video mode" set to "Progressive".
as evident from line 91 of resources/wiiflow_game_booter/source/main.cpp, any selected "Video mode" sets the Patching mode to "Normal", which (i am not really sure what it does) has no effect on my games. Setting the Video mode to "Game" addresses the issue -- the patching is done as selected.

i am closing the issue for now, though i'm still not sure whether Video mode resetting the Patching to Normal is the intended behavior. i would like you to address this question.

**Comment by bibarub** [comment]
@Fledge68
