### ISSUE TITLE
Some games broken in 5.5.4 14a

### ISSUE THREAD

**Issue by EpicDoodleboy2** [Fledge68/WiiFlow_Lite#368]
**Describe the bug**
When launching some games it justs restarts the system  ex. Mario strikers charged football, Super Paper mario, MkW and Pikmin 2, probs more...

**What version of WiiFlow Lite**
v5.5.4

**On Wii or Wii U vWii**
Wii

**Comment by wiidev** [comment]
Likely the same issue as https://github.com/Fledge68/WiiFlow_Lite/issues/366#issuecomment-1732088298.

Could you share a [SysCheck report](https://wii.guide/syscheck.html) and let us know if you're using a USB drive or an SD card?

**Comment by Fledge68** [comment]
haven't heard from you in over a month so i'm closing. if your still around and still having the issue you can re open this.

**Comment by EpicDoodleboy2** [comment]
Im back with the sys check, forgot this existed... Removed the console id btw
[SysCheck.csv](https://github.com/Fledge68/WiiFlow_Lite/files/13168578/SysCheck.csv)

**Comment by EpicDoodleboy2** [comment]
@Fledge68 can you reopen?

**Comment by EpicDoodleboy2** [comment]
@wiidev You there?
