### ISSUE TITLE
USB stick became inaccessible with v5.5.4

### ISSUE THREAD

**Issue by mardy** [Fledge68/WiiFlow_Lite#370]
**Describe the bug**
While trying the latest version in the hope of getting CoD:MW3 working (see issue #369), WiiFlow sent me back to the Wii system screen (where all the channels are visible), and from that moment on it stopped seeing the USB stick at all (so, it was reporting that I had no games installed).

In the options screen, the devices that I could choose for the Wii games were "SD" and "SD/USB".

In the fole browser, the only device shown was "sd:".

**To Reproduce**
1. Hard to tell. Maybe installing the Italian version of CoD:MW3 will trigger this issue.

**What version of WiiFlow Lite**
v5.5.4

**On Wii or Wii U vWii**
Wii

**Additional context**
I tried all of the following, without success: rebooting the Wii, removing and reinserting the USB stick, inserting it into the USB port closer to the center.

**Comment by Fledge68** [comment]
it sounds to me - at some point the 'sd only' option was changed to ON, possibly automatically do to you trying different things to get the game working. it's probably too late now but at that time you should've went to main settings>startup settings to make sure 'sd only' was OFF.

**Comment by mardy** [comment]
> it sounds to me - at some point the 'sd only' option was changed to ON, possibly automatically do to you trying different things to get the game working. it's probably too late now but at that time you should've went to main settings>startup settings to make sure 'sd only' was OFF.

It's possible, yes, I don't really remember. Well, let's close this, if no one else reported the same it's most likely due to me toggling some other settings.
