### ISSUE TITLE
Shutdown bug

### ISSUE THREAD

**Issue by MeshariHat** [Fledge68/WiiFlow_Lite#372]
If a game is launched through WFL, and then decide to turn of the console through the Wiimote, the Wiiflow lite will take me back to the system menu.

-Start Wiiflow Lite
-Go to settings 
-Go to "Return To Channel" option 
-Set it to Disabled
-Go back to the games page and launch any game
-Turn off the console using the Wiimote
-Now it would take you back to system menu and will not shutdown the system

V5.5.4

Wii U's vWii

**Comment by Fledge68** [comment]
so while you are playing a game you try to turn off the console with the wiimote power button. ummm if that's the case thats not a wfl issue it's the cios. once the game is launched it no longer has anything to do with wfl. the cios controls the inputs and outputs.

**Comment by eku** [comment]
@MeshariHat please don't cross-post https://github.com/DacoTaco/priiloader/issues/360.

**Comment by MeshariHat** [comment]
My bad it was a Priiloader's issue, not WiiFlow lite.

Thank you
