### ISSUE TITLE
Question: Is it possible to have animated backgrounds?

### ISSUE THREAD

**Issue by worstcase-scenario** [Fledge68/WiiFlow_Lite#373]
Hi, 
first: a big thank you for your wonderful app! It is really appreciated. Keep up your good work!

One Question: I was just wondering if Wiiflow is able to show animated backgrounds (like a gif) or just static pngs?

Would be great if someone can answer me this... Thanks!

**Comment by eku** [comment]
Did you know that there's a support forum? Try [gbatemp](https://gbatemp.net/threads/wiiflow-lite.422685/).
GitHub is only for reporting software bugs.

**Comment by worstcase-scenario** [comment]
Sorry, no I didn't know... I'm going to post my question there.... thanks!

**Comment by Fledge68** [comment]
answered your question there, thanks.
