### ISSUE TITLE
[BUG] hard crash (reload type) when choosing "install game" from main/home menu

### ISSUE THREAD

**Issue by gingerbeardman** [Fledge68/WiiFlow_Lite#38]
1. press home button on wii remote
2. press "install game"
= hard crash, will reload WFL after 10 seconds

(no game disc in the drive, if that matters)

previously mentioned in #27

**Comment by Fledge68** [comment]
are you using a language other than the default english?
because all this does is display a message that it's broken and to use clean rip. the only thing i can think of that would cause a crash would be if your language file was corrupted.

**Comment by gingerbeardman** [comment]
No, just default English.

Actually, sd://wiiflow/languages is empty

**Comment by gingerbeardman** [comment]
Maybe a sysCheck would show the difference in our setups?

**Comment by Fledge68** [comment]
so did you fix your rhapsodii theme?

**Comment by gingerbeardman** [comment]
Had to stop after finding the problem, will give back in soon to figure out what exactly is wrong.

**Comment by gingerbeardman** [comment]
My crashing issue

- I recopied Rhapsodii images from a verified unrar, but problem persists
- I reserved all PNG images, bonus is that the [URL=https://forumfiles.com/U9wbp8mab6/Rhapsodii-Beta1-images_zip]total filesize is much reduced[/URL], but problem persists
- to be continued

**Comment by gingerbeardman** [comment]
- reinstalled both WFL and Rhapsodii
- run disk check and repair
= problem persists

Do you think it is something to do with the way I have my CIOS setup?

**Comment by Fledge68** [comment]
background music?

**Comment by gingerbeardman** [comment]
Going to create a separate, minimal Rhapsodii install on a different SD card today

**Comment by gingerbeardman** [comment]
I no longer use background music

**Comment by gingerbeardman** [comment]
Just to keep all discussion here, this crash also happens with Carbonik Abz theme.

Could you perhaps zip up a minimal working install of WFl + theme so I can extract to a different SD card and test? Thanks so much

**Comment by Fledge68** [comment]
what do you mean by minimal? what am i supposed to leave out?

**Comment by gingerbeardman** [comment]
I meant no homebrew channel or anything like that; probably not the best phrasing, sorry

**Comment by Fledge68** [comment]
questions:
is wiiflow lite on SD or USB?
is wiiflow folder with plugins and themes on SD or USB?
where did you put rhapsodii and carbonik themes?
where did you put the default.ini for coverflow?
are you using your own wait animation images?
do you use the source menu?

**Comment by gingerbeardman** [comment]
> is wiiflow lite on SD or USB?
SD

> is wiiflow folder with plugins and themes on SD or USB?
> where did you put rhapsodii and carbonik themes?
> where did you put the default.ini for coverflow?
See my SD card structure: [SD.txt](https://github.com/Fledge68/WiiFlow_Lite/files/2636340/SD.txt)

> are you using your own wait animation images?
No

> do you use the source menu?
No

**Comment by gingerbeardman** [comment]
Also, is it possible to built a debug version with logging so we can see where exactly it is crashing? 

Thank for your help in this. I fully expect it to be user error on my part.

**Comment by Fledge68** [comment]
hmmmm. no source menu?
i take it that means no source_menu.ini inside wiiflow/source_menu?

this might be the problem.  i'm looking into it. but strange the default theme works.

**Comment by gingerbeardman** [comment]
I had it in there, and renamed it as source_menu.inx when I could not get it working. my plan was to revisit that at another point in time

**Comment by Fledge68** [comment]
can you try this one?
[https://www.mediafire.com/file/f8gud49j82b29y0/wfl_boot.dol/file](url)

**Comment by gingerbeardman** [comment]
That has done it! Thank you.

**Comment by gingerbeardman** [comment]
Screens

![GitHawk Upload by gingerbeardman](https://i.imgur.com/58vDZgm.jpg)

![GitHawk Upload by gingerbeardman](https://i.imgur.com/G98iexD.jpg)

**Comment by Fledge68** [comment]
great! i'm surprised that other users without the source menu haven't said anything. maybe they didn't test things thorough like you.

so the problem is since you don't use/have source_menu.ini i wrote the code not to make those buttons and images. 
BUT ... when an error message is displayed it hides some of the menus, one of which is the source menu which in your case was never defined and thus crashes wiiflow lite.

**Comment by gingerbeardman** [comment]
Thanks for the explanation, and for sticking with me on this! I am glad I'm not crazy after all.
