### ISSUE TITLE
Guess what I can't open games (VWII) 5.5.4

### ISSUE THREAD

**Issue by Thiswontworkfu** [Fledge68/WiiFlow_Lite#380]
Select game try to run it Wii flow animation black screen then either I go back to  whatever menu I have Wii flow setup to take me back to.

**Comment by gingerbeardman** [comment]
Dupe #366 

Workaround is to go back to 5.5.3

**Comment by Thiswontworkfu** [comment]
Got it sorry bout the dupe I looked in the closed tickets and didn't find the same issue

**Comment by Thiswontworkfu** [comment]
Dupe

**Comment by gingerbeardman** [comment]
no worries!
