### ISSUE TITLE
[Question] How can I create a channel for a game?

### ISSUE THREAD

**Issue by lundylizard** [Fledge68/WiiFlow_Lite#388]
Hello everyone, I hope you are having a good day. 

How do I make a system menu channel of a game?
I tried the method [of this old forum post](https://gbatemp.net/threads/instaliing-a-channel-for-a-game-in-wiiflow.268752/) which didn't work.

For now, I am trying to make a channel for Mario Party 8, I put my `.wbfs` file (also tried using an `.iso` file) into "CrapV3.3b" (with the custom loaders added from the post) and I install the `.wad` file using "YAWM ModMii Edition". I also selected the working ios number for my Wii system in Crap (249 in my case). The channel shows up, but starting the game results in a black screen, followed by a return to the system menu after about 10 seconds.

I am assuming that the files in the post are completely irrelevant for this version of WiiFlow or that I am completely misunderstanding something. 

If you have further questions, please ask. Any help is welcome, thank you!

**Comment by gingerbeardman** [comment]
This would only give you forwarder channel to load WiiFlow, you would still have to use the interface to choose the game.

If you want the forwarder channel to straight to a game, use this approach: https://wii.hacks.guide/wiigsc

**Comment by lundylizard** [comment]
Thank you, that seemed to help.
It works without issues with Wii Sports Resorts. However, I still have following issue: I splitted the Mario Party 8 wbfs file because of it's size, that one doesn't run and again just sends me back to the System Menu. Do you have any idea what could solve this?

**Comment by gingerbeardman** [comment]
Sorry no, for help with a specific game I can only recommend posting on the GBAtemp forum topic: https://gbatemp.net/threads/wiiflow-lite.422685/
