### ISSUE TITLE
Cannot change Cover directory

### ISSUE THREAD

**Issue by treyus30** [Fledge68/WiiFlow_Lite#392]
Maybe I'm dumb but I cannot figure out how to change the covers, etc download directory to the USB device. My SD card is only 1GB and I have over 1k covers to download so keeping them on the SD is not an option. I tried changing the following:

dir_backgrounds=sd:/wiiflow/backgrounds
dir_banner_cache=sd:/wiiflow/cache/banners
dir_box_covers=sd:/wiiflow/boxcovers
dir_cache=sd:/wiiflow/cache
dir_cart=sd:/wiiflow/cart_disk
dir_cheat=sd:/wiiflow/codes/gct
dir_coverflows=sd:/wiiflow/themes_lite/coverflows
dir_custom_banners=sd:/wiiflow/custom_banners
dir_fanart=sd:/wiiflow/fanart
dir_flat_covers=sd:/wiiflow/covers
dir_help=sd:/wiiflow/help
dir_languages=sd:/wiiflow/languages
dir_list_cache=sd:/wiiflow/cache/lists
dir_music=sd:/wiiflow/music
dir_plugins=sd:/wiiflow/plugins
dir_plugins_data=sd:/wiiflow/plugins_data
dir_screenshot=sd:/wiiflow/screenshots
dir_settings=sd:/wiiflow/settings
dir_snap=sd:/wiiflow/snapshots
dir_source=sd:/wiiflow/source_menu
dir_themes_lite=sd:/wiiflow/themes_lite
dir_trailers=sd:/wiiflow/trailers
dir_txtcheat=sd:/wiiflow/codes
dir_wiitdb=sd:/wiiflow/settings
dir_wip=sd:/wiiflow/codes/wip

to from "sd:/" to "usb:/" and nothing happened

**Comment by gingerbeardman** [comment]
Have you actually run out of space on your SD card? The covers aren't that big.

- boxcovers: ~1MB each
- covers: ~0.1MB each
- custom banners: ~1MB each

**Comment by eku** [comment]
I am afraid that WFL expects the directories on the same medium as it is installed (`apps/wiiflow`). At least that's how I interpret the source code.

**Comment by treyus30** [comment]
Luckily this undocumented feature, is a feature, you just have to specify the *correct* usb. eg: usb1:/ worked for me
