### ISSUE TITLE
incompatible games 

### ISSUE THREAD

**Issue by Mama8315405924998525971827** [Fledge68/WiiFlow_Lite#395]
**Describe the bug**
hello 👋 I wanted to tell you that Wii music does not work on Wiiflow. I prefer to tell you so that maybe it can be fixed. In any case, congratulations for what a great application you know.😀. have a GREAT DAY 

**What version of WiiFlow Lite**
v5.4.9

**On Wii or Wii U**
Wii

**Comment by eku** [comment]
> does not work

Do you want to be precise?

Did you try different IOS as loader?

Please provide a [syscheck](https://wii.hacks.guide/syscheck.html) output.

**Comment by gingerbeardman** [comment]
Please also verify your Wii Music dump is good

**Comment by Mama8315405924998525971827** [comment]
I left tomorrow I can tell you
