### ISSUE TITLE
Interface facelift

### ISSUE THREAD

**Issue by octoshrimpy** [Fledge68/WiiFlow_Lite#4]
Hi! I'm a UX/UI designer and would love to help wiiflow look a little cleaner, maybe even make themes that can be shipped with it. At home I've redone most of the major icons to [FontAwesome](https://fontawesome.com), and would love to help out this project however I can.

**Comment by gingerbeardman** [comment]
I'd also be happy to help give WiiFlowLite a facelift

**Comment by octoshrimpy** [comment]
@gingerbeardman I've recently started redoing the icons with fontAwesome icons. I've gotten them to work on the old wiiflow. Sadly my cousin (somehow) broke my Wii, so I'm starting from scratch on the setup.

If I can find a quick-install guide for wiiflow-lite, I can have PRs with newer icons. I am also aware that @einsteinx2 [has done some UI/UX work](https://github.com/einsteinx2/wiiflow-lite-einstein-mod). we might be able to work with them.

**Comment by octoshrimpy** [comment]
I have installed wiiflow_lite last night, and will be converting the icons to FontAwesome icons over the next couple of days.

**Comment by gingerbeardman** [comment]
I have just seen Rhapsodii and to be honest if it works that will do me

https://gbatemp.net/threads/wiiflow-lite-theme-rhapsodii.511833/
