### ISSUE TITLE
All Wii games boot to black screen (10/10) - UNLESS cache reloaded before boot, then it works (10/10)

### ISSUE THREAD

**Issue by Alexroseajr** [Fledge68/WiiFlow_Lite#400]
**Describe the bug**
Only happens to Wii games not Gamecube.

When I boot Wiiflow Lite (either through a forwarder, vwii mode (no priiloader installed and no hacks), and boot any game off SD://wbfs/, there is no loading bar at the bottom and the console hangs on a black screen

**To Reproduce**
1. .wbfs files placed in correct directories on fat32 formatted SD inside SD://wbfs folder
2. boot wiiflow in any configuration (hbc, vwii forwarder etc.)
3. have ios 58 patch and d2x cios installed with cios 249
4. have many games on the sd. default theme. default settings. have box art and zip downloaded
5. **do not press home and refresh cache** (if you refresh cache it works fine)
6. boot any Wii game
7. note that loading bar never appears, hangs on black screen. console requires hard reset

***Workaround***
1. Refresh cache at any time before boot

**What version of WiiFlow Lite**
v5.5.4-1
vWii, no priiloader, just patched ios58, cios249, hbc, wiiflow. same difference regardless of whether booting from wad, vwii channel, aroma forwarder
no plugins
Startup settings set to: mount sd only: yes. USB port: 0. force cios revision: auto. 

**Additional context**
force load cios: set to on or off makes no difference. changing cios makes no difference. set all my settings to default, made no difference

**Comment by Alexroseajr** [comment]
here's a video of the phenomenon along with my entire settings menu
https://youtu.be/F3h9D2Ck4Ag

**Comment by Alexroseajr** [comment]
Here's an example of the flow when it works (with the cache reload)

```
Welcome to WiiFlow WFL 5.5.4-1!
This is the debug output.
WiiU
vWii Mode
AHBPROT disabled = yes
Found WiiFlow Save
Loading IOS Settings from wiiflow save
Using SD Only Settings from wiiflow save
AHBPROT disabled after IOS Reload: yes
Now using D2X IOS249[56] v11
FAT Partition at sd: mounted.
Wiiflow boot.dol Location: sd:/apps/wiiflow
Data Directory: sd:/wiiflow
Setting Wii games partition to: 0
Wii Games Directory: %s:/wbfs
GameCube Games Directory: %s:/games
Nintendont found
emunand = sd:/vwiinands/default
savesnand = sd:/vwiinands/default
Running sound thread
Loading cIOS map
Found d2x base 56 in slot 249
Found d2x base 57 in slot 250
Found d2x base 58 in slot 251
ListGenerator: fileNameSkipPattern=((dis[ck]|tape|side|track)[ _-]([b-l][^a-z]|0*[2-9]|0*[1-9][0-9]))|(^disc2[.]iso$)|(^neogeo[.]zip$)|(^funboot[.]rom$)|(^(ecs|exec|grom)[.]bin$)
Bootup completed!
Creating Gamelist
Adding wii list
Games found: 68
Displaying covers
Creating Gamelist
Adding wii list
Games found: 68
  cachepath=sd:/wiiflow/cache
  nameorid=RUUE01
  wfcpath=sd:/wiiflow/cache/RUUE01.wfc
//^ the above then loops 67 more times, no issues there]
Displaying covers
Update Play log
Launching game SOUE01
Game ID SOUE01 requested IOS 56.
User selected 0
cIOS slot 249 chosen.
Return to channel DWFA using d2x succeeded.
Cleanup Coverflow
Stopping sound thread
Stopped sound thread
MEM1_freesize(): 8339440
MEM2_freesize(): 42516224
```

and here's when it breaks:
```
Welcome to WiiFlow WFL 5.5.4-1!
This is the debug output.
WiiU
vWii Mode
AHBPROT disabled = yes
Found WiiFlow Save
Loading IOS Settings from wiiflow save
Using SD Only Settings from wiiflow save
AHBPROT disabled after IOS Reload: yes
Now using D2X IOS249[56] v11
FAT Partition at sd: mounted.
Wiiflow boot.dol Location: sd:/apps/wiiflow
Data Directory: sd:/wiiflow
Setting Wii games partition to: 0
Wii Games Directory: %s:/wbfs
GameCube Games Directory: %s:/games
Nintendont found
emunand = sd:/vwiinands/default
savesnand = sd:/vwiinands/default
Running sound thread
Loading cIOS map
Found d2x base 56 in slot 249
Found d2x base 57 in slot 250
Found d2x base 58 in slot 251
ListGenerator: fileNameSkipPattern=((dis[ck]|tape|side|track)[ _-]([b-l][^a-z]|0*[2-9]|0*[1-9][0-9]))|(^disc2[.]iso$)|(^neogeo[.]zip$)|(^funboot[.]rom$)|(^(ecs|exec|grom)[.]bin$)
Bootup completed!
Creating Gamelist
Adding wii list
Games found: 68
Displaying covers
Update Play log
Launching game SOUE01
Game ID SOUE01 requested IOS 56.
User selected 0
cIOS slot 249 chosen.
Return to channel DWFA using d2x succeeded.
Cleanup Coverflow
Stopping sound thread
Stopped sound thread
MEM1_freesize(): 8413168
MEM2_freesize(): 42516224
```

Nothing jumps out at me here. Could it potentially be that the first time the app boots the system has some kind of hook set up that's breaking everything, and when reloading cache it fixes that? I have no idea what the problem is

**Comment by Alexroseajr** [comment]
After reading the codebase I did some more tests to see what reloading cache actually does. I came to the conclusion it sets m_refreshGameList to true and sets the bool "update_cache" to true in the wii and general domain. So I looked for other places where this happens to see if it's the update_cache or the refreshGameList or the combination of both that fixes the problem. but outside of reloading the cache from the menu I can't find a reliable way to fix it:
* reloading cache from the menu = everything works
* reloading cache from a different coverflow view like gamecube = everything works
* setting a different wii path, then setting the original wii path = get a loading bar but stalls
* updating tdb.zip from the wiiflow menu = bar appears, fully loads, then a stack dump appears (image 1)
* deleting sd:/wiiflow/cache/list before boot = stalls on the black screen, no fix
* deleted tdb.zip and the .xml from sd://wiiflow/settings and turned off dump_list=no, update_cache=yes, database titles=no to try and force reading it from boot (I was wondering if having tdb in memory was a problem). result = stack dump (image 2)


![5870553693689070324 (1)](https://github.com/user-attachments/assets/e8daca68-b040-4d05-84c0-7300a2324e68)
![stacktrace 2](https://github.com/user-attachments/assets/d18b8a80-b72c-407e-9cba-8674f37e7e87)

**Comment by eku** [comment]
Could you please test this without EmuNAND and SavesNand?

**Comment by Alexroseajr** [comment]
- NAND Emulation is set to partial (not Full, I have no option to turn it off). Select NAND is set to default (unchangeable), Select Saves NAND is set to default (unchangeable), Saves NAND Emulation is set to off.

logs attached:
[SysCheck.csv](https://github.com/user-attachments/files/16488119/SysCheck.csv)
[IOSsyscheck.log](https://github.com/user-attachments/files/16488118/IOSsyscheck.log)

I also figured something else out. after reverting my settings and deleting gametdb_offsets.bin and wiitdb.xml, the black screen hang is gone (although the stack dump persists. going to turn off database base names again to see if it's hanging because I removed the files)

I don't know if there's a way to get a dump because the log is useless, but 80aa124c is where it hangs every single time, on latest. Any idea if that corresponds to some kind of lookup of the .xml file/offset bin (which is now absent)?

**Comment by Alexroseajr** [comment]
okay I have it isolated with 100% repro. 
database_titles=yes, no database reload -> black screen hang
database_titles=yes, database reload, wiitdb.xml present -> game works
database_titles=yes, database reload, wiitdb.xml absent -> stack dump
database_titles=no -> game works (but all the titles have bad/incorrect names from the iso directly. is there a way to overwrite these manually without wiiflow overwriting titlesdump.ini?)

**Comment by Alexroseajr** [comment]
Okay. somehow, inexplicably, it is now working. the only diff I can find between this and old versions, is that:
in [CHANNELS]:
```emulation=1
update_cache=yes```

in [GENERAL]:
```update_cache=no
dump_list=yes```

in [PLUGINS]:
`database_title=yes`

Here's my working ini file (renamed to .txt for github):
[wiiflow_lite.txt](https://github.com/user-attachments/files/16488254/wiiflow_lite.txt)

and I also wiped, deleted and redownloaded wiitdb.xml through the app

**Comment by eku** [comment]
> I don't know if there's a way to get a dump because the log is useless, but 80aa124c is where it hangs every single time, on latest. Any idea if that corresponds to some kind of lookup of the .xml file/offset bin (which is now absent)?

Well, it's possible to map the stack addresses to functions. However, I haven't done this yet and would have to do my own research first. @Fledge68  might know how.

**Comment by Fledge68** [comment]
i've been reading all your messages/replies.  very interesting issue. i have been quite at a loss. but your testing and reporting is awesome.

database_titles is only used for plugins. wii games are technically not plugins but there is a set of wiiflow plugins one of which is for wii games.  i believe you are using this plugin for your wii source menu button. If you were using the source=wii for your button you probably wouldn't have this issue.

**Comment by Fledge68** [comment]
ok checking code now my brain hurts. database_titles shouldn't effect wii games at all.

question are viewing and playing wii games only? or are you combining wii games with plugin games?

**Comment by Alexroseajr** [comment]
yeah, hopefully it doesn't re-manifest

I have a few theories about why it happened, and it's probably because I'm a tinkerer and it's my own fault but maybe this could help someone else:
1. I originally was unable to find out how to set the file names so e.g. Wii Sports wouldn't show up as "SPORTS PACK FOR REVOLUTION" etc, and at that point without looking into the ini itself or the codebase, using the in-app options only, I found the source list and concluded it must be wiitdb.xml
2. Foolishly, I did NOT find the wiitdb.zip downloader inside the covers downloader menu (despite having used it to download wii/gc games many times to that point), so I manually downloaded it myself and extracted it
3. I did not add a gametdb_offsets.bin myself, although I ended up with one at some point which I backed up before I deleted it, and if I sha1 that against the one I have now it's the same
4. however the sha1 of my downloaded .xml differs from the old one

I know the reason for point 4, incidentally. line 5 of the xml says
`Never modify this file manually, it will get overwritten when you update. You can add games and fixes on the website.` 

I assumed the reason you should never modify this file manually is because it gets overwritten, and I thought that was a non issue since I never planned to overwrite and was unaware that offsets.bin existed, but I have a mod of a gamecube game that doesn't exist in wiitdb so I added an entry for myself. Which did work on the loader, all the metadata I added loaded correctly

So potentially it's possible that offsets.bin was pointing to the wrong place because I added an entry manually? I'm not sure why all of this would still work in the MENU but would crash on BOOT though. But maybe if it was somehow reading those offsets on load for something but if you reload cache it stores it locally and then loads it from memory that might explain what went wrong? Not sure. Or maybe it's just the specific set of options I used fixed it for some reason. Or maybe because I'm loading from an SD my SD is just being incredibly volatile but just so happening to get exactly reproduceable results and sent me on a wild goose chase (but seems very unlikely from how consistent it was)

**Comment by Alexroseajr** [comment]
sorry I only just saw your other post. I have gamecube games (which always worked fine), and wii disc games. No wads, no homebrew, no emulation, no injects, no plugins, no NAND emulation, just simple disc loading from SD

As far as I can tell "Use plugin database titles" makes the games read their IDs from wiitdb.xml instead of parsing them from the .wbfs (which leads to things like MarioParty4 and BillyHatcher instead of Mario Party 4 and Billy Hatcher and the Giant Egg and some really bad titles like "SPORTS PACK FOR REVOLUTION" and "PARTY PACK FOR REVOLUTION" instead of wii sports and wii play, Wii Sports Resort's name inside the iso is an internal development acronym instead of the game name, etc. . I have no idea why that would then stop the game from booting, maybe it's caching something from that xml that it later uses in the boot process?

**Comment by Fledge68** [comment]
do you use the source menu or sourceflow to select wii game covers or gamecube covers?

do you use rhaposodii shima theme and source menu?

**Comment by Alexroseajr** [comment]
I use the default wiiflow-lite menu unthemed. I just select gamecube and wii games from the main menu and press the button to flip between them (I disabled homebrew/plugin buttons, I just display gc/wii). I don't have sourceflow. When I click it it says I don't have it. I'm just running vanilla.

**Comment by Alexroseajr** [comment]
the video in post 2 btw shows my setup so you can see it running in case that's helpful (I also after a couple of boots to show boots work after a reload went through my entire settings menu in the video)

**Comment by Fledge68** [comment]
so after the questions, watching your video, looking at your wiiflow_lite.ini and knowing that you don't use a theme or source menu or plugins. you just have a basic setup with wii and gamecube games. my brain hurts even more.

the use database_title option should have nothing to do with your wii game titles. that is ONLY for plugin roms.
i'm assuming you problem was that you manually editted wiitdb.xml . and now that you deleted it and downloaded a new one everything should be working fine right?

**Comment by Alexroseajr** [comment]
Yes, everything does seem to be working fine now and I do assume that was the problem!
