### ISSUE TITLE
Problem updating to v5.5.4

### ISSUE THREAD

**Issue by AlsoVincent** [Fledge68/WiiFlow_Lite#402]
I'm running WiiFlow version v5.5.3, but when I update to v5.5.4, opening WiiFlow immediately brings me to a black screen for a few seconds, before bringing me back to the Homebrew menu. I made sure my install was clean, my sd card was formatted, and my cios's were done correctly. I'm not sure what's wrong.

**Comment by eku** [comment]
Please use the [support forum](https://gbatemp.net/threads/wiiflow-lite.422685/) for enquiries of this kind.

**Comment by AlsoVincent** [comment]
Got it, thank you!
