### ISSUE TITLE
meta.xml wait_imgs points to /apps/wiiflow/ not /apps/wiiflow_lite/

### ISSUE THREAD

**Issue by gingerbeardman** [Fledge68/WiiFlow_Lite#42]
as title

**Comment by Fledge68** [comment]
thanks matt. it's just an example. i got a little lazy and used the same meta.xml for wfl and wfl as wiiflow. oh well

**Comment by gingerbeardman** [comment]
Hey no worries, I hope you don't mind me posting these small things. I like to be thorough
