### ISSUE TITLE
[/USER] Buttons 3, 4, 5 & 6 Not Appearing

### ISSUE THREAD

**Issue by Hakaisha** [Fledge68/WiiFlow_Lite#44]
I've been attempting to add some small on-screen button guides along the bottom of the screen to the Rhapsodii theme in the [MAIN/] and [GAME/] screens. 

However, I noticed they just don't seem to want to appear if I use the /USER buttons after 1 and 2. Ideally, I can place the guides in USER3 or 4 and hide it separately from USER1 & USER2, utilizing the buttons2_ /ZONES.

I double-checked to make sure buttons2_ and buttons3_ weren't checked to hide, and it still did not display. Out of curiosity, I looked back at another theme I haven't fooled with in a while, which prominently uses MAIN/USER3-6, and they are no longer appearing here either.

Also, on a related note, is it possible to add a /USER button to the SourceFlow screen? I've tried [SOURCEFLOW/USER1], [SOURCE_FLOW/USER1], [SF/USER1] and haven't been able to produce a result. [SOURCE/USER1] does work for the Classic Source Menu screen however.

**Comment by Fledge68** [comment]
lets see if i can explain this.

USER1 and USER2 are textures to appear behind the buttons homebrew, favorites, config, and home.
USER3 and USER4 are textures to appear behind the view button (wii, gc, nand, plugins).
USER5 and USER6 are textures to appear behind the disc button.
these USER's and there buttons are set to only appear when your pointer is in their zone area of the screen.

The zones are specified by "MAIN/ZONES" "buttons#"

sourceflow uses the "MAIN" screen. and all buttons are disabled to not show during sourceflow.

**Comment by Fledge68** [comment]
problem solved. user 3 and 4 didnt show because the view buttons were hidden.
