### ISSUE TITLE
Wiimmfi support broken with recent Wiimmfi update

### ISSUE THREAD

**Issue by Leseratte10** [Fledge68/WiiFlow_Lite#45]
As of November 11th, the automatic Wiimmfi patcher in WiiFlow Lite doesn't work any more for Mario Kart Wii due to server-side changes on Wiimmfi (https://wiimmfi.de/update). 

I have already written an update for the USB-Loader GX implementing support for this new Wiimmfi update, would you be interested in having that in WiiFlow Lite as well (to restore the server patch functionality for Mario Kart Wii)?

If so, I would try to adapt it so it works with WiiFlow and open a pull request to add that.

**Comment by Fledge68** [comment]
yes please .... funny i just replied to your post on gbatemp usbloader gx thread. i asked if you could do the patch for wiiflow lite and then came here to see this.

**Comment by Fledge68** [comment]
wiiflow lite is compiled with ppc r30 and libogc 1.8.19.

**Comment by Leseratte10** [comment]
I just tried fixing the errors but I just had new ones appear every time I fixed one. Could you try making the necessary changes so it compiles with r32 or r33? I do have libogc 1.8.19 somewhere but i couldn't find a working download for devkitPPC-r30 anywhere (for linux), and libogc 1.8.19 doesn't work properly with devkitPPC-r32.

**Comment by gingerbeardman** [comment]
Great news, thanks @Leseratte10 !

**Comment by Leseratte10** [comment]
I'm kinda having trouble finding a place in code where to apply my patches to the game. 

In resources/wiiflow_game_booter/source/apploader.c at the end of Apploader_Run (right before the return statement), the DOL should be loaded into memory, right?

But adding these two lines of code, which should alter a value in the game's memory (just for testing)
```
*((u32*)0x802759f4) = 0xfefe7474; 
DCFlushRange((void*)0x802759f4, 4);
```
and then checking with the USB-Gecko, this change isn't present. Unfortunately, printf calls in wiiflow_game_booter are neither printed to screen nor to SD so I can't even check if I am in the correct method. 

Is there another place (right before the game boots) where I can perform changes to the memory?

**Comment by Fledge68** [comment]
good idea. makes sense. thanks again.

**Comment by gingerbeardman** [comment]
@Leseratte10 I read that there's an updated Wiimmfi patch? Do you plan to update WFL to apply this new patch?

https://wiimmfi.de/update

Continued thanks!

**Comment by Leseratte10** [comment]
Yeah, I plan to do that. In fact, I already did; I just need to verify that my patched version still works. I'll make another PR in the next couple days.

**Comment by gingerbeardman** [comment]
Thank you! I just finished reading the page and saw that you were on it. 

> If you are using your USB Loaders custom server patch (for example in the USB-Loader GX or in WiiFlow Lite), you will have to wait a little while. We've prepared updated versions of these two USB Loaders and we will create the appropriate Pull Requests within the next couple days. In the meantime, you can use the ISO patchers to patch your images for Wiimmfi if you want to play games that require the new patchers.
