### ISSUE TITLE
Missed back covers result in stretched cover

### ISSUE THREAD

**Issue by bell07** [Fledge68/WiiFlow_Lite#49]
For example "AMF Bowling World Lanes" [[R6WP58]](https://www.gametdb.com/Wii/R6WP68). Some games does not have an full "coverfullHQ" cover. Updating such games result in "only front cover downloaded" message. that is fine.
But in coverflow this covers are displayed stretched trough both sites. Expected behaviour is the front site should be shown only on the front side. I remember in older versions there was an "standard back cover" shown for such games.

**Comment by Fledge68** [comment]
thanks for finding and reporting this.
