### ISSUE TITLE
FTP server

### ISSUE THREAD

**Issue by markthewolf90** [Fledge68/WiiFlow_Lite#5]
Mind if I ask how to un-remove FTP, because I find that Wiiflow's works better than WiiXplorer for me due to WiiXplorer not being able to show your USB directory.

**Comment by Fledge68** [comment]
what do you mean WiiXplorer can't show your USB directory?

**Comment by markthewolf90** [comment]
Yeah, sorry. I suppose what I said was kinda hard to understand. In
WiiFlow's FTP, you could access either your USB or SD card. But with
WiiXplorer, you can only access your SD card.

**Comment by gingerbeardman** [comment]
@markthewolf90 you can access SD or USB using WiiXplorer

click the SD card icon and you get to pick which device to browse

![https://wiibrew.org/w/images/2/28/Wiixplorer.png](https://wiibrew.org/w/images/2/28/Wiixplorer.png)
