### ISSUE TITLE
Custom missing / blank covers not showing up

### ISSUE THREAD

**Issue by iamerror80** [Fledge68/WiiFlow_Lite#54]
Former versions of Wiiflow (as well as WFL einstein mod btw) use to display custom generic covers for games with missing covers, a different one for each plugin, defined under [BLANK_COVERS] in theme.ini, with jpeg files located in boxcovers folder.
Now missing covers only display the default.png file, no matter which coverflow is launched.

**Comment by Hakaisha** [comment]
I can confirm that I am having this issue as well. Carbonik Abz custom missing covers defined by magic# in theme.ini are not being utilized when the theme is loaded, or with any other theme that utilizes custom missing covers.

**Comment by iamerror80** [comment]
It seems that this issue was introduced in WFL r1150.

**Comment by iamerror80** [comment]
Thanks. Didn't know magic numbers could be used as jpg filename.
