### ISSUE TITLE
Theme config not saved after pressing 1 in Home menu

### ISSUE THREAD

**Issue by iamerror80** [Fledge68/WiiFlow_Lite#55]
Theme.ini is not updated with new labels and buttons after pressing 1 in Home menu. Default.ini is not created either when using default theme.
The issue seems to have been introduced in r1150 with the theme unloading function (issue related to my other issue #54).

**Comment by Fledge68** [comment]
another good find! didn't realize anyone actually used this. will be fixed next commit.
