### ISSUE TITLE
Some magic numbers declared for short covers plugins result in normal coverflows

### ISSUE THREAD

**Issue by iamerror80** [Fledge68/WiiFlow_Lite#56]
The following magic numbers won't display "short covers" flows :
"56424168", //VbaGX GB
"56424178", //VbaGX GBC
"56424188", //VbaGX GBA
"4d45445e", //WiiMednafen GB
"4d45446e", //WiiMednafen GBC
"4d45447e", //WiiMednafen GBA
"57495358",	//WiiSX - playstation
"51304dxx" //QuakeGX Modloader wild cards

It seems there's a typo in _shortCover function, looking for ARRAY_SIZE(sideCovers) instead of ARRAY_SIZE(shortCovers).

**Comment by Fledge68** [comment]
Good find! will be fixed next commit.
