### ISSUE TITLE
RealNand/EmuNand Autoboot

### ISSUE THREAD

**Issue by Hakaisha** [Fledge68/WiiFlow_Lite#57]
Straight to the point: 

[BUTTON]
source=realnand
source=emunand

Both sources used with autoboot commands under a source_menu.ini [BUTTON] will boot to whichever Channels type is currently selected in WFL, rather than what is defined in the text. If "Both" Channels types are selected in WFL, these autoboot command sources always boot to emunand.

Long Story:
I've been experimenting and working on SourceFlow tiers. My base menu (source_menu.ini) comprises of several autoboot [BUTTON]s, some of them are homebrew apps and some are NAND channels.

I'm attempting to have autoboot buttons that boot up realnand channels such as the Mii Channel, Wii Shop Channel, Forecast, Photo, etc, while keeping emunand as my preferred source for everything else. 

In the past, I have been able to use real_nand_miis=yes in wiiflow_lite.ini to make the Mii Channel autoboot from realnand. However, in the latest WFL, real_nand_miis somehow always defaults back to no, after booting up WFL again.

**Comment by Fledge68** [comment]
thanks for the heads up.

1. both sources show what channels type is set to - that works correctly. but i have decided to use 3 sources for nand source buttons now.
source=realnand
source=emunand
source=bothnand

2. when set to Both autoboot tries to only use emunand is a mistake. i have found and fixed the problem for that.

**Comment by Fledge68** [comment]
also real_nand_miis=yes means wiiflow (lite) will copy your real nand miis from real nand to your emu nand when booting a emu nand channel. and when its done  real_nand_miis is set to no. same goes for real_nand_config. they don't need to be set to yes again unless your real nand miis or config has changed and you want to copy them to emu nand.
