### ISSUE TITLE
After deleting a game you have to wait ~1m to return to flow channel

### ISSUE THREAD

**Issue by Ntemis** [Fledge68/WiiFlow_Lite#58]
As per title you have to wait over a minute to return back to the game list.
My hdd used is a usb-3.0 maxtor M3 portable 2tb just for reference

**Comment by gingerbeardman** [comment]
What version?

I have not had this experience.

**Comment by Ntemis** [comment]
I have the latest version 5.1.0

**Comment by Fledge68** [comment]
very strange. the code is simple.
it stops coverflow's cover loader and clears all the covers' textures 
then deletes the box cover, front cover, and cover's wfc texture file.
and finally restarts coverflow's cover loader which reload's all the covers' textures but will obviously not find the current games' wfc texture file.

all i can recommend is do a chkdisk on your USB HDD and SD card if you use one. maybe something is corrupted.

**Comment by gingerbeardman** [comment]
How many games? Is there a progress bar? Can you share a video?

**Comment by Ntemis** [comment]
No progress bar. Hdd is brand new formatted by xbox360 to gain the appropriate compatibility with ps3 and wii. It has wii Nintendont and N64 games converted by hand by injection to Nintendo emulator. You realise thats a lot of games on it. Sure i can provide a video tomorrow no problem there.

**Comment by Ntemis** [comment]
Then it might be my naming as to keep compatibility with ps3 launchers the folder is named GAMES(capital letters) and though it works it might be the culprit of this bug.

**Comment by gingerbeardman** [comment]
GAMES is correct

**Comment by Fledge68** [comment]
so what type of game are you deleting?
is it a wii game?
is it gamecube game?
what folder is your wii games in?
what folder is your gamecube games in?
how many partitions does your usb HDD have?
are your wii games on FAT32, NTFS, or WBFS partition?
i assume your gamecube games are on FAT32 partition?
I don't understand why you don't see a progress bar ... after deleting the game wiiflow lite does a reload cache and then rechecks the wfc texture files while displaying a progress bar.

**Comment by gingerbeardman** [comment]
Note: the download above is 0.5GB

**Comment by gingerbeardman** [comment]
OK, so 2 hours later I have downloaded the video.

- you do get progress bar (it's very quick because there is only one game and the delete is almost instant)
- you can press a button A/B to dismiss the game deleted message
- please next time, help us help you

![easy](https://user-images.githubusercontent.com/49612/51266048-18a74800-19b2-11e9-8791-64b3d6f15c2c.gif)

**Comment by Ntemis** [comment]
I will sent a new video pressing A/B and still wait over a minute, also if you have a timeout of over one minute after delete that should be changed too anyway.

**Comment by Fledge68** [comment]
yes send another video. this one does not show coverflow after deleting the game. that is where the wait is.

**Comment by gingerbeardman** [comment]
Please upload to YouTube or somewhere that we can view it more quickly.
