### ISSUE TITLE
Return to channel autochanges to WiiFlow

### ISSUE THREAD

**Issue by SirMrMister** [Fledge68/WiiFlow_Lite#6]
Using latest pre-built version avaliable of the as-WiiFlow version.

As the title says - I want the "Return to channel" option as Disabled, so that an in-game shutdown signal results in the Wii entering into standby (yellow light), which allows it to power the Wiimote battery chargers/holsters I've got connected to its other USB port. Setting it to WiiFlow instead results in it returning to WiiFlow, and since a shutdown signal while in WiiFlow results in the wii shutting down to the red light state (which does NOT give power to USB devices), that is indesireable (I have the Wii set to load WiiFlow's forwarder on boot anyway, so no time lost there).

However, every time WiiFlow starts up (be it from a shutdown, standby or return to channel), the cheeky fucker will have set itself back to WiiFlow. Setting it manually to Disabled saves that value for that session, as starting a game and then ordering a shutdown will indeed send it into yellow light standby, so it's not as if the setting isn't setting into the SD or memory.

**Comment by Fledge68** [comment]
Thanks for pointing this out. i can see where the problem is in the code and will fix it in the next commit.

**Comment by SirMrMister** [comment]
Oh, and incidentally, the normal not-as-wiiflow version doesn’t have this bug, but instead will blackscreen freeze most of the time when shutting down a loaded game with this setting disabled (wii’s light will still be green after sending shutdown command while in-game, and will require the forced hold-wii-power-button-4-seconds shutdown).

**Comment by Fledge68** [comment]
not sure why it would be different but that sounds like the issue tetsuo shima reported on the gbatemp wiiflow lite thread. and i posted a download that he says fixed it for him. 

here try this wfl as wiiflow - i just fixed your issue (it should be fixed)
[https://www.mediafire.com/file/ea9bdkcywmyktjj/boot.dol/file](url)

**Comment by SirMrMister** [comment]
It wokrs indeed - thanks.
