### ISSUE TITLE
Some games dont load 

### ISSUE THREAD

**Issue by Ntemis** [Fledge68/WiiFlow_Lite#62]
I have issues launching 
- Calling [SCAE18] 
It boots on USBloader just fine
- Far Cry Vengeance [RCVE41]
I didn't manage to launch it yet even after my own iso rip

**Comment by gingerbeardman** [comment]
What happens exactly?

**Comment by Ntemis** [comment]
Exception DSI occured

**Comment by gingerbeardman** [comment]
Sorry, I don't have either of those

**Comment by Hakaisha** [comment]
Hey, I have these games. And from the same region. Just tried booting up both using the latest WFL release, and both games seem to load/play fine without issue.

I should note that I convert my Wii ISOs to WBFS format, and have WFL set to force cIOS 250 [57] d2x v10 beta52 at startup.

It's strange that you're getting an exception. A cIOS issue usually tends to just crash with a black screen, after attempting to load the game. 

Have you reloaded the cache, after placing the newer ISO rips on your USB/SD? WFL could possibly still be searching for and trying to load the older cached version of the game files you previously had, and therefore throwing the exception when they aren't found.

**Comment by Ntemis** [comment]
FYI i have updated my wii to 4.3(was at 4.2E) and problem is solved by it self
