### ISSUE TITLE
How can I display debug information?

### ISSUE THREAD

**Issue by Zootwem** [Fledge68/WiiFlow_Lite#65]
I was playing fine yesterday, but today I can't open any Wii games, when I open a game the WiiFlow logo appears moving and then it just returns to the system menu.

GameCube games work just fine, so i want to see if it's a configuration problem or a bug in the launcher.

Is there a way to save the debug information so I can post it here?

Thanks 👍

**Comment by Fledge68** [comment]
you have to open wiiflow_lite.ini with a text editor (notepad++). under [Debug] set sd_write_log=yes. when you run wiiflow lite a wiiflow.log file will be written to the root of your sd card. 

so did you change anything from yesterday to today?  any setting changes? maybe emunand stuff?

**Comment by Zootwem** [comment]
> 
> 
> you have to open wiiflow_lite.ini with a text editor (notepad++). under [Debug] set sd_write_log=yes. when you run wiiflow lite a wiiflow.log file will be written to the root of your sd card.

What if I'm not using a SD card? Can I write the info in my USB unit?

>
>
> so did you change anything from yesterday to today? any setting changes? maybe emunand stuff?

I'm new in modding the Wii, so I haven't changed anything related to emunand. I changed mostly system language settings and cover settings.

I deleted the config files and I'll try again, now with an SD card connected to get the debug information 😃
