### ISSUE TITLE
[BUG] Music stops playing when returning to WiiFlow Lite

### ISSUE THREAD

**Issue by Zootwem** [Fledge68/WiiFlow_Lite#69]
Hello, I have a song in my music folder that works fine, but in Settings I changed Return To Channel>WiiFlow Lite, and uppon returning from a game to WiiFlow the music doesn't start playing, just the sound effects from WiiFlow, but the music from the folder doesn't work.

**Comment by Fledge68** [comment]
how did you or do you launch wiiflow lite the first time? homebrew channel? or forwarder?
this one is very hard to believe. there's nothing about returning to wiiflow lite that should cause your background song to not play.
i assume when you restart wiiflow lite the song plays?

**Comment by Zootwem** [comment]
> 
> 
> how did you or do you launch wiiflow lite the first time? homebrew channel? or forwarder?
> this one is very hard to believe. there's nothing about returning to wiiflow lite that should cause your background song to not play.
> i assume when you restart wiiflow lite the song plays?

Fixed it! I had changed Music fade rate>0 and that made the bug appear.

You can mark this as solved 😄
