### ISSUE TITLE
Cannot use Patched games

### ISSUE THREAD

**Issue by BestNoob** [Fledge68/WiiFlow_Lite#71]
I cannot use already patched games. Patched with wiimmfi-patcher-v4.
Unpatched games working fine.

(Had no problems with wiimmfi-patcher-v3 and older USBLoaderGX /WiiFlow Lite versions)

**Comment by gingerbeardman** [comment]
What happens?

**Comment by Fledge68** [comment]
if the games already patched then make sure in the game's settings 'private server' is off.
if game is not patched then in game setting's set 'private server' to on.

mario kart wii is the only game affected by the new wiimfi patches that leseratte added to wiiflow lite.

**Comment by BestNoob** [comment]
Thanks, yes i missed that, just wondered about that it was working fine before, but its good to know, now you do not longer need to patch games (only for Dolphin Emulator)
