### ISSUE TITLE
[REQ] Add deadzone to navigation with Nunchuck

### ISSUE THREAD

**Issue by Zootwem** [Fledge68/WiiFlow_Lite#72]
Hello, when I was navigating disks with the nunchuck it had no deadzone, causing problems when I moved it too fast to one way and then releasing it, going back to where it was because of the natural movement towards the center position caused a little movement in the opposite way where the controller was.

**Comment by gingerbeardman** [comment]
Can you please post a video?

**Comment by Zootwem** [comment]
> 
> 
> Can you please post a video of what you're seeing?

Just barely move the nunchuck stick and the games menu will move 👍 
It doesn't happen with regular Wii apps/games because of the deadzone

Is not a big deal, but adds consistency with other Wii menus
