### ISSUE TITLE
Clearify WiiFlow_Lite as WiiFlow and WiiFlow Lite

### ISSUE THREAD

**Issue by BestNoob** [Fledge68/WiiFlow_Lite#74]
Hello,
i just saw that there is no info about installing and using WiiFlow Lite (yes i know you can use WiiFlow Wiki/iInstallation Help) . And its not clearyfied that you can use WiiFlow Lite as fresh Loader or as WiiFlow Update/Replacement.

And youre talking about thats Lite is using the WiiFlow folders buts not clear which.
And you didnt linked the Forwarder in the new Releases.

**Comment by Zootwem** [comment]
> 
> And you didnt linked the Forwarder in the new Releases.

The forwarder in the old release still works if you need it [https://github.com/Fledge68/WiiFlow_Lite/releases/download/v4.4.0-r1161/wfl_forwarders.zip](https://github.com/Fledge68/WiiFlow_Lite/releases/download/v4.4.0-r1161/wfl_forwarders.zip)

**Comment by Fledge68** [comment]
installing wiiflow lite and wfl as wiiflow is in the readme of this repository. you just need to scroll down to read it.
also install and more is in the first post of the gbatemp thread - [https://gbatemp.net/threads/wiiflow-lite.422685/](url)

plus in the releases if you scroll all the way down to the first release you will find the forwarders.

and to top it all off. when i release v5.2.0 soon, there no longer will be 2 seperate versions. you will just replace wiiflow with wiiflow lite and then use wiiflow forwarders.

**Comment by BestNoob** [comment]
Okay. For me it felt like all informations are spread everywhere, but nothing concrete. I mainly use USBLoaderGX but for some things/games WiiFlow is better. Great to hear that youre working on a new version =)
