### ISSUE TITLE
Wiinnertag not longer working

### ISSUE THREAD

**Issue by Zootwem** [Fledge68/WiiFlow_Lite#75]
I saw this line of code

`[GAMERCARD]
dutag_key=
dutag_url=http://tag.darkumbra.net/{KEY}.update={ID6}
gamercards=wiinnertag|dutag
gamercards_enable=no
wiinnertag_key=
wiinnertag_url=http://www.wiinnertag.com/wiinnertag_scripts/update_sign.php?key={KEY}&game_id={ID6}`

And tried reaching the url to see if it was still working. It doesn't work anymore, so could you remove it?

**Comment by Fledge68** [comment]
are you a darkumbra member? this is for darkumbra members only. i'm not sure about wiinertag. it's not hurting anything to keep it in there.
