### ISSUE TITLE
[BUG] No apps found in sd:/apps

### ISSUE THREAD

**Issue by Zootwem** [Fledge68/WiiFlow_Lite#76]
I have all my apps on my USB drive, so it should show usb1:/apps instead of sd:/apps

**Comment by gingerbeardman** [comment]
There's an option for that

**Comment by Zootwem** [comment]
> 
> 
> There's an option for that

Where? I cannot find it in the directories settings

**Comment by Zootwem** [comment]
> 
> 
> There's an option for that

I cheched it again but couldn't find it, could you point me where is that option please? I want to launch my apps without going back to HBC. Also a shutdown option would be nice 👍

**Comment by Zootwem** [comment]
I cannot execute RetroArch, but no error code is shown on the debug information, how do I fix it?

`Welcome to WiiFlow Lite 5.1.0!
This is the debug output.
Real Wii
AHBPROT disabled = yes
IOS58 v6176
patched isfs_permissions 1 times.
patched es_setuid 1 times.
patched es_identify 1 times.
patched hash_check 0 times.
patched new_hash_check 1 times.
Init ISFS
Found WiiFlow Save
FAT Partition at sd: mounted.
Changing USB port to port 0....
 * * * * * * * * * * * *
 * HDD Information
 * Sectors: 121307135
 * Size [Sector Size]: 57 GB [512]
 * * * * * * * * * * * *
FAT Partition at usb1: mounted.
Running sound thread
Wiiflow boot.dol Location: usb1:/apps/wiiflow_lite
Data Directory: usb1:/wiiflow
Wii Games Directory: %s:/wbfs
Nintendont found
GameCube Games Directory: %s:/games
Loading cIOS map
Found d2x base 56 in slot 249
Found d2x base 57 in slot 250
Setting Wii games partition to: 1
Creating Gamelist
Games found: 12
Coverflow started!
wiiflow main screen ready!
Coverflow stopped!
**Apps found: 5
Coverflow started!
Launching game HB_APP
launching homebrew app
Coverflow stopped!
Cleanup Coverflow
Stopping sound thread
Stopped sound thread
MEM1_freesize(): 10297328
MEM2_freesize(): 40976512**
 
Welcome to WiiFlow Lite 5.1.0!
This is the debug output.`

**Comment by Fledge68** [comment]
i have no idea why retroarch didn't run for you. does it load via HBC?

**Comment by Zootwem** [comment]
> 
> 
> i have no idea why retroarch didn't run for you. does it load via HBC?

Yes, it does run via HBC. Could you add more debug information in the next release? So I can send more detailed logs 😃

**Comment by Fledge68** [comment]
no. once wiiflow is done then no more debug info. if there's an error on wiiflows part its happening after wiiflow closes and the app launcher takes over. maybe someone else has the same version of retroarch as you and can try it on their wii to see if they get the same results. that why you should ask this on gbatemp so more people can reply. what version is your retroarch?

**Comment by Fledge68** [comment]
i have retroarch 1.7.5 and launching it via wiiflow as a homebrew app works fine. no problem at all.
