### ISSUE TITLE
[REQ] Change font color in game titles and in menus

### ISSUE THREAD

**Issue by Zootwem** [Fledge68/WiiFlow_Lite#77]
I want to make a Nintendo Switch theme, but the colors don't fit with the light background. Also an option to always show UI icons would be nice, I'll be posting a theme concept soonTM.

**Comment by Zootwem** [comment]
![wiiconcept](https://user-images.githubusercontent.com/22050470/53075114-2bd69780-34cb-11e9-9a65-efeed7457318.png)
@Fledge68 A concept I had about a WiiFlow Lite theme 😁 , can you help me develop it? I have the coverflow spot on and the background, everything else I don't know how to do it 😭

**Comment by Fledge68** [comment]
sorry i really don't have the time. and you really should be posting this stuff on gbatemp. not here.
plus there's been a recent post about help with themes on gbatemp. here - [https://gbatemp.net/threads/wiiflow-lite.422685/page-66#post-8504768](url)
