### ISSUE TITLE
[BUG] Partitions stuck on SD setting, cannot change to USBx

### ISSUE THREAD

**Issue by gingerbeardman** [Fledge68/WiiFlow_Lite#8]
1. Have `games` and `wbfs`, each containing games, present on SD
2. Have `games` and `wbfs`, each containing games, present on USBx
3. in WFL set partitions for GC&Wii games to `SD`
4. restart WFL
5. in WFL attempt to set partitions for GC&Wii games to `USBx`

expected
- should be able to select `USBx`

actual
- cannot select `USBx`
- stuck on `SD`

versions
4.4.0 r1161
and  https://www.mediafire.com/file/i5g59c678l39t9n/wfl_10-17-18.zip/file

**Comment by Fledge68** [comment]
this is fixed when i added the 5 extra pages of main settings. on page 11 there is an option to set sd only to off or no. you will have to exit wiiflow lite and restart it. with sd only set to no then wiiflow lite will mount usb devices allowing you to change partitions. there is a mediafire link on the wiiflow lite gbatemp thread to download a boot dol or wait for me to release wiiflow lite 5 which i plan to do soon.

**Comment by gingerbeardman** [comment]
thanks, i'll wait ✌️

**Comment by Fledge68** [comment]
did v5.0.0 fix this problem?
remember set sd only to off or no on page 11 of main settings. then exit wiiflow lite and restart it.

**Comment by easzzb** [comment]
i’m having this issue with the current latest version on wiiflow wfl

**Comment by eku** [comment]
> yes, i set sd only to off

@easzzb  I suggest to open a new bug issue. This one is already closed. Don't forget to provide more information about your setup as well as a copy of your `wiiflow_lite.ini`.
