### ISSUE TITLE
[DISCUSS] patching games for correct 480p settings

### ISSUE THREAD

**Issue by gingerbeardman** [Fledge68/WiiFlow_Lite#86]
https://shmups.system11.org/viewtopic.php?p=1361335#p1361335

> Extrems wrote:
> It was a configuration oversight all along.
> 
> https://github.com/ExtremsCorner/libogc-rice/commit/941d687e271fada68c359bbed98bed1fbb454448
> 
> Here's a before/after:
> 
> ![https://files.extremscorner.org/wii/screenshots/480p-comparison.png](https://files.extremscorner.org/wii/screenshots/480p-comparison.png)
> 
> Not64 was updated. Set "VideoWidth = 0" for pixel perfect.
> An update for Enhanced mGBA is in the works.
> 
> On the left is what all versions of the Revolution SDK does. libogc also happen to use decompiled Revolution SDK code.
> 
> Every piece of software ever released on the Wii that supports 480p is affected

I wonder if this can be patched through a universal cheat code? Until then, every homebrew will need to be recompiled using the fixed libogc.

**Comment by Fledge68** [comment]
Hi Matt! so i've seen this on gbatemp. I see the patch for libogc but i have know idea how to apply this to every game wiiflow launches. if you know something let me know.

**Comment by Hakaisha** [comment]
This is quite a fascinating discovery! Props to Extrems for finding this. It would be interesting to be able to play all of our games with this fix applied. 

Perhaps at least the WiiFlow app itself could benefit from this 480p fix? I can only imagine how nice it would look, especially combined with the FSAA x8 CoverFlows.

**Comment by gingerbeardman** [comment]
Apparently there's a fix being worked on that will install into BootMii (or thereabouts) which will apply the fix for all games.

**Comment by gingerbeardman** [comment]
Here are some photos of my 640x480p LCD displaying Mario Kart Wii both with and without the 480p fix. This is great because the 1:1 pixel output allows you to see the differences at a sub-pixel resolution.

**Places to look for differences**
1. e of Channel
2. inside the a of Back
3. glasses frame on my Mii
4. Ms of Main Menu

**Conclusion**
- fixed: graphics are pixel aligned horizontally
- original: graphics are not pixel aligned horizontally

cropped photo album
https://imgur.com/a/Ef02mmz

full size photo album
https://imgur.com/a/R0k3igo

fixed: single pixel wide glasses frame
![IMG_6337](https://user-images.githubusercontent.com/49612/58809533-0867d080-8614-11e9-9455-5102df8e4c24.jpg)

original: double pixel wide glasses frame
![IMG_6341](https://user-images.githubusercontent.com/49612/58809538-0aca2a80-8614-11e9-8eb2-99bc0cfcd369.jpg)

fixed: m starts on pixel boundary
![IMG_6338](https://user-images.githubusercontent.com/49612/58809544-10c00b80-8614-11e9-98eb-8b0e48da4d99.jpg)

original: m starts half way through a pixel
![IMG_6342](https://user-images.githubusercontent.com/49612/58809548-11f13880-8614-11e9-838b-578fe61bbdf2.jpg)

**Comment by Fledge68** [comment]
the vertical line of the M is easy to see. and on the glasses the vertical line out in the light blue is more defined.  on the 'a' the leading left vertical line of the small loop is more defined. so its basically (to me) the the left edges are more defined (darker and less transparent).

**Comment by gingerbeardman** [comment]
Yes, exactly.

**Comment by Fledge68** [comment]
doesn't this fix only apply to older wii's? or for people using composite cables instead of component?

**Comment by gingerbeardman** [comment]
480p is only available over component. 

apparently the later models (not sure which) worked around the problem with a hardware change.

**Comment by Senseless-Creature** [comment]
This would be so cool

**Comment by Leseratte10** [comment]
I just noticed this issue report - I already wrote such a patch for the USB-Loader GX, it can be found in `trunk/source/patches/gamepatches.c` in the USB-Loader GX sources: https://sourceforge.net/p/usbloadergx/code/1272/tree//trunk/source/patches/gamepatches.c#l119

Should be fairly easy to adapt this to Wiiflow Lite, I could try adapting it at some point if needed; but someone else would need to add the code to add a setting to the game settings to allow players to disable it. It could probably be enabled by default but there should still be a setting to disable it in cas it causes problems.

**Comment by Fledge68** [comment]
@Leseratte10 i'm in the process of adding/copying your code from usbloader gx to wiiflow 5. i got an error at hexdump(x, y). if i understand the code that function is used just to gprintf out the hexcode patches. it's not really needed. and was mainly used for debugging when you wrote the code. is this correct.

i commented those out and the code compiled without errors. now to add the option to the settings menu so users can turn it on or off.

**Comment by Leseratte10** [comment]
That's correct, the hexdump calls are just for debugging.

**Comment by Fledge68** [comment]
@gingerbeardman should this patch have a global default setting or default to off and you have to set each game to on?

**Comment by Fledge68** [comment]
@gingerbeardman here it is wf5 5.3 beta 8 with Leseratte's 480p pixel patch.
[https://www.mediafire.com/file/g1mlr8owau8hprb/wf5_480p_pixel_patch.zip/file](url)
ext_booter.bin goes in the bins folder of course.

there is a globale default setting in main settings pg 13
and each game has a setting on page 5 that can be default, off, or on.

i tried it on a couple of games. can't tell much but they did seem a bit crisper. i figured i'd let the expert Matt try it.

oh but i did not modify my libogc so wiiflow 5 is not compiled with the fix.

**Comment by gingerbeardman** [comment]
Great! Will test tonight.

ps: your external links never work, I have to copy and paste them. you need to replace the URL if using formatting, or just paste the link and let GitHub format it (my preference)

**Comment by Fledge68** [comment]
thanks for heads up about the links. strange they show up fine but when you click them they dont work properly. i got rid of the []url and it works fine now.

so i guess you haven't had time to test yet?

**Comment by gingerbeardman** [comment]
Not yet, will do ASAP

**Comment by Fledge68** [comment]
@gingerbeardman any progress? don't mean to rush.

**Comment by gingerbeardman** [comment]
Sorry not yet will do so ASAP

**Comment by Fledge68** [comment]
seems to work no ones reported it don't.

**Comment by gingerbeardman** [comment]
I'll finally be home and able to test tonight

**Comment by gingerbeardman** [comment]
Works!
