### ISSUE TITLE
[BUG] Download Cheats (Ocarina) doesn't work

### ISSUE THREAD

**Issue by ajcasanova** [Fledge68/WiiFlow_Lite#87]
Always fails when trying to download any cheat code from any game. Wiiflow freezes.
Last try: Mario Kart Double Dash (PAL)

**Comment by ajcasanova** [comment]
Sorry, more information, of course:
Trying to get GeckoCodes from my PC, it shows just the first time a "DdosProtection by...". Maybe is this the problem?. Second time I can access perfectly without this kind of preload from my PC browser.
I'm using:
Wii U black, reading Wii homebrew and games from 256 Gb Samsung EVO plus SD card, FAT32 formated.
Not all games freezes, some just get a "can't get code" or something like that, even if they've got a cheat code in database

**Comment by Fledge68** [comment]
yes the DDOS protection is the problem. downloading cheats on usb loader gx doesn't work either because of it. and I don't know how to patch wiiflow to get by it. if anyone does please let me know. until then we can only download them manually via our pc's.

**Comment by Alex4nder001** [comment]
IMO a simple solution would be if Wiiflow downloaded cheats from another server.

**Comment by gingerbeardman** [comment]
Is USBloaderGX affected? If not, how do they get around it?

**Comment by Fledge68** [comment]
usbloader gx is affected too. cyan was going to work on it at one time but that's pretty much hopeless now. he seems to always be too busy and hasn't done much of anything with usbloader gx for quite some time.

**Comment by Fledge68** [comment]
seems to be a guy on gbatemp that seems to have patched usb loader gx to download from gecko codes. but the code has big changes. i'll look into fixing this but doubt if I can.
