### ISSUE TITLE
Broken and won't show any games

### ISSUE THREAD

**Issue by Alex4nder001** [Fledge68/WiiFlow_Lite#88]
Started using Wiiflow, worked perfectly but today I launched Wiiflow and I got something like this:
![Untitled](https://user-images.githubusercontent.com/38557087/56382025-4f3d6a80-620e-11e9-91ad-c6f569c721d7.png)
I used Dolphin to take the screenshot (to give a rough idea of what I get), but I am using this on real hardware. On my Wii U, all the GUI graphics are missing, but I can still navigate the menu. The main screen shows the text "No games in sd:/wbfs" or something like that. However, I have Wiiflow on my USB HDD (usb1:/apps/wiiflow/boot.dol) which is FAT32 with 32K clusters, formatted using Wii Backup manager. I tried changing wii/gamecube game paths manually in the wiiflow_lite.ini file, but that didn't solve the problem. Any help?

**Comment by gingerbeardman** [comment]
Any ideas what you changed to make this happen?

**Comment by Alex4nder001** [comment]
Actually, I figured out what happened - the wiiflow_lite.ini file must have gotten corrupted. I opened it in notepad++ and there was an unrecognized character at the end of the file. So I deleted it and Wiiflow functions normally now.

Great loader, by the way. I'm glad I made the switch from USB Loader GX (only reason was that a few games didn't work).

**Comment by Fledge68** [comment]
hmmm, i've had a mysterious NULL character appear a the end of mine in the past but not in long time. i wish i knew why but i don't. glad you figured it out.
