### ISSUE TITLE
Broken and refuses to display games (again)

### ISSUE THREAD

**Issue by Alex4nder001** [Fledge68/WiiFlow_Lite#89]
Sorry about this. This time the same happened again, and editing/deleting the wiiflow_lite.ini file didn't help. The GUI graphics are missing, and it refuses to show USB games (even though I loaded WiiFlow from my properly formatted USB HDD). USB Loader GX works, though.
![IMG-0178](https://user-images.githubusercontent.com/38557087/56393893-95ee8d00-622d-11e9-89ef-67c30e0093af.JPG)
![IMG-0177](https://user-images.githubusercontent.com/38557087/56393899-98e97d80-622d-11e9-835a-2be966c2d08d.JPG)

**Comment by Fledge68** [comment]
so ... seeing as how you have apps/wiiflow on USB and the above picture says sd:/wbfs.
my logical guess is wiiflow thinks you want sd only. 
try going to main settings>startup settings and set sd only to no. when the rebooting message appears press B to reboot wiiflow.

personally if you have an SD card you should have apps/wiiflow on SD not USB.

**Comment by Alex4nder001** [comment]
Basically, I used to have USBloader GX on USB because my HDD would not be properly connected (after I plug it into my PC to add games then plug it back into my Wii U), and the only time it would load was when the USB drive was connected (otherwise if it was on the SD card, it would tell me that there are no games, and when I did reconnect the HDD I’d have to change the settings to make it show games again, which was annoying). This is the reason I put all loaders on USB. This doesn’t happen with my new HDD, but IDK if I’ll have the same issues with this drive.

Anyway, I do not have “SD only” enabled. I moved Wiiflow and Nintendont to the SD card, and it works fine, apart from Gamecube games (my controller doesn’t work, I’m using an official GC controller with the Mayflash GC controller adaptor for PC/Wii U).

**Comment by Fledge68** [comment]
random freezes? are we talking wii games or gc games?

if it's wii games, i highly recommend main settings>startup settings and set force cios to on and let wiiflow reboot.

if it's gc games, that's odd. i have my apps/nintendont on sd card but my games folder is on USB. everything works fine for me.

**Comment by DD2XAlpha** [comment]
Does it take a lot for rebooting Wiiflow when setting cIOS on? because is taking a lot for me

**Comment by gingerbeardman** [comment]
>Does it take a lot for rebooting Wiiflow when setting cIOS on? because is taking a lot for me

@DD2XAlpha I had to hard power off/on as it seemed to have become stuck
