### ISSUE TITLE
[REQ] Option to hide second disc of two disc games

### ISSUE THREAD

**Issue by gingerbeardman** [Fledge68/WiiFlow_Lite#9]
eg. GameCube game _Freaky Flyers_ [GFFE5D]

game.iso
disc2.iso

**Comment by Fledge68** [comment]
hiding disc 2 is done by using a category.

access the categories menu by pressing the 'B' button while your pointer is pointing at the Favorites Star.
once there click on category 1 until it changes to an 'X' which means any games in this category will be hidden.
now exit back to your covers and choose the game cover you want to hide.
on the game selected screen either press 'B' while pointing at the favorites star or goto the games settings and select categories.
once on the games category menu put a check mark in category 1.
exit back to your covers and the cover should be gone.
to see it again goto the main categories menu and remove the 'X' .
of course this will unhide all hidden covers. put it back to 'X' to hide them again.

**Comment by gingerbeardman** [comment]
🤯

Thank you

**Comment by gingerbeardman** [comment]
Just done this, worked a treat! Cheers
