### ISSUE TITLE
Add Option to Keep Emunand 'System settings' in Sync with the Real Nand 

### ISSUE THREAD

**Issue by dekkit** [Fledge68/WiiFlow_Lite#90]
The wii stores linked wii remote settings under:
/shared2/sys/SYSCONF

Currently, if you add any wii remote's after creating your emunand, they may not work for virtual console /wii ware running from emunand (If set to full or via need2o)

Currently to get new wii remotes to sync in emunands, you need to copy the folder

NAND
/shared2/sys/SYSCONF

to
Emunand 
/shared2/sys/SYSCONF

Can we add an option in the Wii flow settings under emunand, to keep system settings in sync with real nand?

So that on loading of wii flow lite, if emunand is enabled, it will check if the files are the same.

If not the same, it will copy the updated system files (for wii mote especially) into the emunand.  Otherwise if same it will not change it. 

The benefit is that you can sync your wii remote in the wii normal system menus (easy) and it will automatically flow through to other nands.

Useful if you ever lose your wii remote or move wii remotes between systems.

**Comment by Fledge68** [comment]
this is an option i have planned on adding for quite some time but have yet to do so.

i believe in wiiflow lite ini under [CHANNELS] you can set use_realnand_config=yes and the next time you launch a emunand game it will auto copy sysconf first then launch the game.

**Comment by dekkit** [comment]
awesome thanks for the additional info.

**Comment by Fledge68** [comment]
added and closed
