### ISSUE TITLE
[BUG] Some plugin covers will not show up

### ISSUE THREAD

**Issue by iamerror80** [Fledge68/WiiFlow_Lite#92]
I have a few rom games with covers that won't load using 5.2.0. They load fine with 5.1.0.
Some examples of games (but there are more) :
Super Mario Advance 2 - Super Mario World (Europe) (En,Fr,De,Es).gba
Legend of Zelda, The - Oracle of Seasons (Europe) (En,Fr,De,Es,It).gbc

I tried to compile using the old coverflow.cpp and hpp from 5.1.0, and the former :
		if(!CoverFlow.findId(cur_item, true, path))
			CoverFlow.defaultLoad();
instead of :
		if(!CoverFlow._setCurPosToID(cur_item, true, path))
			CoverFlow._setCurPos(0);
in CMenu::_initCF (menu.cpp), and it works fine this way.

**Comment by Fledge68** [comment]
this is a weird issue. i haven't had any problem loading covers on either version. and the find id and setCurPos has nothing to do with loading covers. it only sets the center cover to the correct cover. replacing coverflow.cpp and hpp maybe helped you but i have no idea why.

maybe those filenames are just way too long. try shortening them by removing the languages in parenthesis.

try wiiflow 5.3.0beta4 - [http://www.mediafire.com/file/j7dy21g7xfdavko/wiiflow_5.3.0_beta4.zip/file](url)

**Comment by iamerror80** [comment]
Sorry I was wrong, in fact the problem was not present in 5.2.0, here is some more accurate information : the bug has been introduced later in March 27 commit, probably when changing wfctitle from const char * to char[64] in CCoverFlow::_loadCoverTex.

Rom titles are very often longer than 64 chars, especially if you're using smokemonster database system, so maybe it would be better to increase the length.

Thanks for the beta 4.

**Comment by Fledge68** [comment]
i figured it was something to do with char[64]. i honestly don't see why people need or even want a game filename longer than that but i'll go ahead and double it to 128. surely that will be long enough.
