### ISSUE TITLE
Wiiflow Support for .GCM file extension for presenting Gamecube Games

### ISSUE THREAD

**Issue by dekkit** [Fledge68/WiiFlow_Lite#93]
Been doing some further testing on Wiiflow lite (5.1.0) and was surprised when a few of gamecube games were missing from the wiiflow coverflow due to having the .gcm extension.

Currently wiiflow will show a gamecube game if the folder is setup as follows and the game has the .iso extension.

Example = working
SD:\games\Mario Kart Double Dash [GM4P01]\game.iso

if the gamecube game is in the other common format (.gcm), then it will not appear in the coverflow.

Example = not working
SD:\games\Mario Kart Double Dash [GM4P01]\game.gcm

Can wiiflow lite be updated to support scanning for both .gcm and .iso files in the gamecube folder? (as per other wii gameloaders)

Note: an interim workaround is simply to rename each game.gcm to game.iso (confirmed working)

**Comment by Fledge68** [comment]
i was not aware that nintendont can read gcm games. it doesn't say that on the OP of the gbatemp thread. it wasn't until i checked nintendont on github that i see it does so i will add it to wiiflow 5.
