### ISSUE TITLE
Setting up Neek2o to work with Wiiflow / Wiiflow lite 

### ISSUE THREAD

**Issue by dekkit** [Fledge68/WiiFlow_Lite#94]
Is it possible to include a tool in a future wii flow lite release to download and build the required Neek2o files for use with the emunand to support virtual console / wii ware titles and simplify the process?  Not a small task but would greatly assist a good number of users.

There is a mish mash of old guides on the web that make it very confusing for noobies to setup sneek and neek2o - when the need for wiiflow is very targeted.

**Note** 
For those looking for a simple and straight forward guide to setup neek2o for wiiflow as well, the simplest found was in the following post by Cyan (GBA temp):  https://tinyurl.com/y2eucupx
see "TUTORIAL FOR COMPILING NEEK​"

What I learnt through this process (that may help)
- Neek2o files need to be compiled/merged before it can be used (Crediar's Sneek installer v0.7a  is a small app that does this quickly - or you can via modmii which is more complx)
- you need the original sneek/uneek base files (r194)
- you need the neek2o base files (r96)
- you need a few key files from official IOS80 (obtained via NUSDownloader)
- then the installer will use these files specifically to compile a neek2o that  connects to
a) emunand on the SD card; 
OR
b) emunand on a usb device
(once compiled, they are not interchangable - so take note of your setup)

For further context, neek2o accesses that same emunand that was extracted via wiiflow.  The way it accesses them however is different from the way gameloaders typically do (its at a much lower system level and therefore doesn't conflict with virtual console software - most noticeable in N64 titles where 54% will crash otherwise).

N64 Titles 
`
The following 12 x virtual console N64 titles need **NEEK2O**  in wiiflow otherwise will crash/freeze at certain points (typically after the connect controller message etc)

Bomberman Hero
Cruis in USA
Kirby 64 Crystal Shards
Mario Golf 64
Mario Party 2
Mario Tennis
Ogre Battle 64
Paper Mario
Pokemon Puzzle League
Super Smash Bros
The Legend of Zelda Majoras Mask

The remaining 10 are fine (so long as have setup your custom cIOS correctly) and **do not** need neek2o:
  1080 Snowboarding 
  F-ZERO X 
  Mario Kart 64 
  Pokemon Snap 
  Sin & Punishment 
  StarFox 64 
  Super Mario 64 
  TLOZ Ocarina of Time 
  Wave Race 64 
  Yoshis Story 
`

**Comment by Fledge68** [comment]
basically no. neek2o (sneek/uneek) is just simply a sneek folder with a kernal.bin and some other files.  and neek2o has a few args you can send it. basically the emunand and the game id to launch. so wiiflow just basically launches it with those args.
