### ISSUE TITLE
Include basic source_menu files with wii flow lite

### ISSUE THREAD

**Issue by dekkit** [Fledge68/WiiFlow_Lite#96]
A really great feature of Wii Flow Lite is the source menu, however you need to download additional files to use it.

This is a suggestion to include a basic set of source menu files (with the base install package).   

This is to keep the initial download small, whilst also enabling new users the chance explore what the source menu can offer, namely a great way to combine all your Wii games, Game cube games, and Virtual Console games (and any other items) into a single cover flow.

Example - Wii games / Gamecube / Virtual Console + Wiiware
**source_menu.ini**
` 
[BUTTON_0]
image=Wii.png
image_s=Wiib.png
title=Wii
source=wii
magic=
emuflow=

[BUTTON_1]
image=Gamecube.png
image_s=Gamecubeb.png
title=Gamecube
source=dml
magic=
emuflow=

[BUTTON_2]
image=Emunand.png
image_s=Emunandb.png
title=
source=emunand
magic=
emuflow=
`

Package Example
[source_menu.zip](https://github.com/Fledge68/WiiFlow_Lite/files/3134769/source_menu.zip)

**Comment by Fledge68** [comment]
noted.  a source menu with just the basic source choices and no plugins. should be do-able.

my only problem is some people don't want or like the source menu. and wiiflow is currently coded to check if source_menu.ini exist and if so use the source menu. if not then no source menu. 
your idea would force everyone to use this basic source menu. unless they deleted it from the source menu folder.
