### ISSUE TITLE
Additional HID Controller support

### ISSUE THREAD

**Issue by dekkit** [Fledge68/WiiFlow_Lite#98]
Wii flow lite currently has support for a few controllers (Wii mote, classic pad, game cube, Wii u, ps3).

Is it possible to support the same customisable HID controller scheme the as featured in Nintendont (ie sd:/controllers/..list of .ini files) for navigating the wii flow cover flows and to launch games/ home brew.

This would avoid the need for the wii mote to navigate and launch gamecube / retroarch / emulator's that feature support for custom HID devices (various game pad's,  arcade sticks etc). 

ie
User boot's straight into wiiflow (via priiloader), user selects gamecube game ( ie using their custom arcade stick), then launches game.

After exiting game, the same controller can then be used to select next game.

This would enable setups that can work without needing to reach for a wii remote/ game cube controller.

**Comment by gingerbeardman** [comment]
Supporting links:
- https://gbatemp.net/threads/nintendont.349258/#Controllers
- https://github.com/FIX94/Nintendont/tree/master/controllerconfigs

**Comment by Fledge68** [comment]
This feature would be very nice but is beyond my coding capabilities. most likely would need to use devkit arm but i don't know how.
