### ISSUE TITLE
Turning force cIOS on takes a lot of time to reboot

### ISSUE THREAD

**Issue by DD2XAlpha** [Fledge68/WiiFlow_Lite#99]
Hello, I appreciate all the hard work on Wiiflow.

The screen get stuck when I turn on the force cIOS to on with the text "Rebooting" and also (I don't know if is helpful) a sign of "!" appears.

I've been in this screen for almost like a hour. I can still move the cursor of the wiimote, but nothing happens after this

**Comment by gingerbeardman** [comment]
@DD2XAlpha I had to hard power off/on as it seemed to have become stuck

**Comment by DD2XAlpha** [comment]
Now it has glitched graphics, also it doesn't find my games on the SD card (yes I have my wbfs folder on the SD).

**Comment by DD2XAlpha** [comment]
Ok so, cIOS 249 crashes while 250 works ok? Please if you could work on this would be great! Thanks for this awesome work

**Comment by Fledge68** [comment]
@DD2XAlpha the screen isn't stuck. did you even try to press a or b on your controller? its called an error message in wiiflow whenever you see a message with a ! then you need to press a or b to exit the message.

by the way i changed that in wf 5.3.0 beta 5 to say 'press A to reload wiiflow'. if you look on gbatemp you can find the download for it.

as for your cIOS why don't you post a syscheck so we can see what cIOS you have installed.
get syscheck here - [https://gbatemp.net/threads/syscheck-hacksden-edition.356133/](url)

**Comment by DD2XAlpha** [comment]
Sure, when I get time I will
